# 04 ADS-B movement

Turns the filtered ADS-B positions from `03_adsb_fetch` into one trajectory per departure and finds the moment the
aircraft first starts to move on the ground. Also measures how far that point is from the stand and from the runway
threshold.

On 32 cores this takes several hours; it was run as a Slurm batch job with
`jupyter nbconvert --to notebook --execute`. Results are never overwritten, so each run has its own `RUN_NAME`.

In [1]:
RUN_NAME = "movement_1s_v5"
MAX_WORKERS = 32
RAM_BUDGET_GIB = 96        # planning budget for the worker count, not a hard limit
N_BUCKETS = 512

In [2]:
import os
for variable in ["OMP_NUM_THREADS", "OPENBLAS_NUM_THREADS", "MKL_NUM_THREADS", "NUMEXPR_NUM_THREADS"]:
    os.environ[variable] = "1"
import json
import sys
import uuid
from pathlib import Path

import pandas as pd
import pyarrow.parquet as pq
from IPython.display import display

ROOT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "data").is_dir() and (p / "pyproject.toml").is_file())
sys.path.insert(0, str(ROOT / "data"))
import adsb_cleanup_worker as workflow      # spawn workers need importable modules
import adsb_extra_features as extra

config = workflow.Config(max_workers=MAX_WORKERS, ram_budget_gib=RAM_BUDGET_GIB, n_buckets=N_BUCKETS)
SOURCES = sorted((ROOT / "data/04_additional_data/adsb_lol").glob("????-??.parquet"))
PROCESSED = ROOT / "data/04_additional_data/adsb_lol_processed" / RUN_NAME
FEATURES = ROOT / "data/03_features" / f"adsb_movement_{RUN_NAME}.parquet"
SCRATCH = Path(os.environ.get("SLURM_TMPDIR", ROOT / "data/04_additional_data/.adsb_prepare_tmp"))
assert not PROCESSED.exists() and not FEATURES.exists(), f"{RUN_NAME} exists already; choose a new RUN_NAME"
display(workflow.inspect_sources(SOURCES))
workflow.resource_report(config)

               file      rows      bytes  parquet_uncompressed_bytes
0   2024-12.parquet         0       1713                           0
1   2025-01.parquet  12378515  225618101                   303414779
2   2025-02.parquet  11506193  208742609                   280363028
3   2025-03.parquet  14715531  265159596                   356434888
4   2025-04.parquet  14598531  262299205                   353212338
5   2025-05.parquet  18804458  335084785                   453064766
6   2025-06.parquet  22113183  385877998                   524356280
7   2025-07.parquet  20734636  365314796                   497666750
8   2025-08.parquet  21577197  377863422                   514470187
9   2025-09.parquet  21039894  369191523                   503017530
10  2025-10.parquet  22748730  397603405                   541772860
11  2025-11.parquet  20953222  367719403                   499935530
12  2025-12.parquet  22256185  387112852                   527509602
13  2026-01.parquet  20097056  351086765                   478691502
14  2026-02.parquet  18711010  326473617                   446379853
15  2026-03.parquet         0       1713                           0
16  2026-05.parquet       269      11696                        9772
17  2026-06.parquet  21859609  380688176                   519764123
18  2026-07.parquet  23928990  417298999                   569426710
19  2026-08.parquet         0       1713                           0

{'cpu_affinity': [9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120],
 'cpu_count': 192,
 'SLURM_CPUS_PER_TASK': '32',
 'configured_MAX_WORKERS': 32,
 'effective_workers': 29,
 'available_ram_gib': 2108.6728591918945,
 'process_rss_gib': 0.21870040893554688,
 'N_BUCKETS': 512}

## Stand and runway positions

Matches every departure's stand and runway to coordinates (OpenStreetMap stands, X-Plane runways), so the distances
of the first movement point can be measured later. Runs first because it is quick and fails early on bad input.

In [3]:
context = FEATURES.parent / f".{FEATURES.stem}.context-{uuid.uuid4().hex}"
# ranking.parquet is left out: its January/July rows are the final ranking rows with slightly shifted times.
CLEAN_FILES = [ROOT / "data/02_clean" / name for name in
               ["train_DEP_merged_sorted.parquet", "train_ARR_merged_sorted.parquet", "final_ranking.parquet"]]
extra.build_context(CLEAN_FILES, context, config.n_buckets)
print("Matching audit:", context.relative_to(ROOT))

Clean metadata: train_DEP_merged_sorted.parquet

Clean metadata: train_ARR_merged_sorted.parquet

Clean metadata: final_ranking.parquet

Geometry: EDDF, matching 256 stands

Geometry EDDF: {'exact': 167, 'normalized_ref': 41, 'mean_same_ref': 20, 'missing': 16, 'parent_stand_estimate': 6, 'xplane_fallback': 3, 'mean_variants': 1, 'ambiguous_spread': 1, 'gate_estimate': 1}

Geometry: EDDM, matching 215 stands

Geometry EDDM: {'exact': 110, 'xplane_fallback': 45, 'missing': 36, 'mean_variants': 24}

Geometry: EGLL, matching 233 stands

Geometry EGLL: {'exact': 165, 'mean_same_ref': 51, 'missing': 14, 'xplane_fallback': 2, 'gate_estimate': 1}

Geometry: EHAM, matching 264 stands

Geometry EHAM: {'exact': 168, 'missing': 44, 'normalized_ref': 40, 'xplane_fallback': 8, 'gate_estimate': 4}

Geometry: LEBL, matching 235 stands

Geometry LEBL: {'exact': 115, 'xplane_fallback': 55, 'mean_same_ref': 49, 'missing': 10, 'parent_stand_estimate': 6}

Geometry: LEMD, matching 384 stands

Geometry LEMD: {'exact': 368, 'mean_same_ref': 9, 'missing': 5, 'xplane_fallback': 2}

Geometry: LFPG, matching 416 stands

Geometry LFPG: {'mean_same_ref': 216, 'exact': 155, 'xplane_fallback': 25, 'normalized_ref': 11, 'missing': 6, 'parent_stand_estimate': 2, 'ambiguous_spread': 1}

Geometry: LIRF, matching 143 stands

Geometry LIRF: {'exact': 92, 'mean_same_ref': 41, 'missing': 6, 'xplane_fallback': 4}

Geometry: LSZH, matching 220 stands

Geometry LSZH: {'exact': 184, 'missing': 23, 'mean_same_ref': 13}

Geometry: LTFM, matching 422 stands

Geometry LTFM: {'exact': 238, 'mean_same_ref': 146, 'ambiguous_spread': 19, 'missing': 17, 'parent_stand_estimate': 1, 'xplane_fallback': 1}

Geometry metadata: 32/512 buckets saved

Geometry metadata: 64/512 buckets saved

Geometry metadata: 96/512 buckets saved

Geometry metadata: 128/512 buckets saved

Geometry metadata: 160/512 buckets saved

Geometry metadata: 192/512 buckets saved

Geometry metadata: 224/512 buckets saved

Geometry metadata: 256/512 buckets saved

Geometry metadata: 288/512 buckets saved

Geometry metadata: 320/512 buckets saved

Geometry metadata: 352/512 buckets saved

Geometry metadata: 384/512 buckets saved

Geometry metadata: 416/512 buckets saved

Geometry metadata: 448/512 buckets saved

Geometry metadata: 480/512 buckets saved

Geometry metadata: 512/512 buckets saved

Matching audit: data/03_features/.adsb_movement_movement_1s_v5.context-ab48871f516c4900bdb1e1b200cf9646

## Stage A: one trajectory per departure

Positions are grouped by departure, split into physical flights with `traffic`, and the flight that contains the
take-off (or starts right after it) is kept and resampled to one second. Ties stay unresolved instead of guessed.

In [4]:
stage_a = workflow.stage_a(SOURCES, PROCESSED, SCRATCH, config)
pd.Series(stage_a["totals"])

{
  "cpu_affinity": [
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    105,
    106,
    107,
    108,
    109,
    110,
    111,
    112,
    113,
    114,
    115,
    116,
    117,
    118,
    119,
    120
  ],
  "cpu_count": 192,
  "SLURM_CPUS_PER_TASK": "32",
  "configured_MAX_WORKERS": 32,
  "effective_workers": 29,
  "available_ram_gib": 2107.8302688598633,
  "process_rss_gib": 0.3297004699707031,
  "N_BUCKETS": 512
}
Hash pass: 2024-12.parquet; 0 rows staged

Hash pass: 2025-01.parquet; 12,378,515 rows staged

Hash pass: 2025-02.parquet; 23,884,708 rows staged

Hash pass: 2025-03.parquet; 38,600,239 rows staged

Hash pass: 2025-04.parquet; 53,198,770 rows staged

Hash pass: 2025-05.parquet; 72,003,228 rows staged

Hash pass: 2025-06.parquet; 94,116,411 rows staged

Hash pass: 2025-07.parquet; 114,851,047 rows staged

Hash pass: 2025-08.parquet; 136,428,244 rows staged

Hash pass: 2025-09.parquet; 157,468,138 rows staged

Hash pass: 2025-10.parquet; 180,216,868 rows staged

Hash pass: 2025-11.parquet; 201,170,090 rows staged

Hash pass: 2025-12.parquet; 223,426,275 rows staged

Hash pass: 2026-01.parquet; 243,523,331 rows staged

Hash pass: 2026-02.parquet; 262,234,341 rows staged

Hash pass: 2026-03.parquet; 262,234,341 rows staged

Hash pass: 2026-05.parquet; 262,234,610 rows staged

Hash pass: 2026-06.parquet; 284,094,219 rows staged

Hash pass: 2026-07.parquet; 308,023,209 rows staged

Hash pass: 2026-08.parquet; 308,023,209 rows staged

{'buckets': '0/512', 'elapsed_sec': 30.1, 'mvts_per_sec': 0.0, 'rss_gib': 2.153270721435547}

{'buckets': '0/512', 'elapsed_sec': 60.1, 'mvts_per_sec': 0.0, 'rss_gib': 2.1532745361328125}

{'buckets': '0/512', 'elapsed_sec': 90.1, 'mvts_per_sec': 0.0, 'rss_gib': 2.1532745361328125}

{'buckets': '0/512', 'elapsed_sec': 120.1, 'mvts_per_sec': 0.0, 'rss_gib': 2.1532745361328125}

{'buckets': '0/512', 'elapsed_sec': 150.1, 'mvts_per_sec': 0.0, 'rss_gib': 2.1532745361328125}

{'buckets': '1/512', 'mvts': 4626, 'assigned_mvts': 4610, 'single': 4358, 'multiple': 252, 'physical_flights': 4882, 'max_physical_flights': 5, 'selected': 4559, 'resampled': 4559, 'rows': 2591188, 'unresolved': 67, 'contains_mvt': 2967, 'starts_after_mvt': 1585, 'ends_before_mvt': 7, 'elapsed_sec': 150.2, 'mvts_per_sec': 30.79, 'rss_gib': 2.153278350830078}

{'buckets': '2/512', 'mvts': 9235, 'assigned_mvts': 9210, 'single': 8713, 'multiple': 497, 'physical_flights': 9745, 'max_physical_flights': 5, 'selected': 9107, 'resampled': 9107, 'rows': 5157820, 'unresolved': 128, 'contains_mvt': 5972, 'starts_after_mvt': 3126, 'ends_before_mvt': 9, 'elapsed_sec': 154.6, 'mvts_per_sec': 59.75, 'rss_gib': 2.153278350830078}

{'buckets': '3/512', 'mvts': 13777, 'assigned_mvts': 13743, 'single': 12995, 'multiple': 748, 'physical_flights': 14544, 'max_physical_flights': 5, 'selected': 13592, 'resampled': 13592, 'rows': 7734556, 'unresolved': 185, 'contains_mvt': 8925, 'starts_after_mvt': 4652, 'ends_before_mvt': 15, 'elapsed_sec': 184.4, 'mvts_per_sec': 74.72, 'rss_gib': 2.153278350830078}

{'buckets': '4/512', 'mvts': 18262, 'assigned_mvts': 18220, 'single': 17247, 'multiple': 973, 'physical_flights': 19265, 'max_physical_flights': 5, 'selected': 18035, 'resampled': 18035, 'rows': 10193429, 'unresolved': 227, 'contains_mvt': 11769, 'starts_after_mvt': 6246, 'ends_before_mvt': 20, 'elapsed_sec': 184.7, 'mvts_per_sec': 98.89, 'rss_gib': 2.153278350830078}

{'buckets': '5/512', 'mvts': 22867, 'assigned_mvts': 22820, 'single': 21599, 'multiple': 1221, 'physical_flights': 24131, 'max_physical_flights': 5, 'selected': 22598, 'resampled': 22598, 'rows': 12750742, 'unresolved': 269, 'contains_mvt': 14759, 'starts_after_mvt': 7813, 'ends_before_mvt': 26, 'elapsed_sec': 186.5, 'mvts_per_sec': 122.63, 'rss_gib': 2.153278350830078}

{'buckets': '6/512', 'mvts': 27408, 'assigned_mvts': 27350, 'single': 25905, 'multiple': 1445, 'physical_flights': 28903, 'max_physical_flights': 5, 'selected': 27085, 'resampled': 27085, 'rows': 15292137, 'unresolved': 323, 'contains_mvt': 17685, 'starts_after_mvt': 9367, 'ends_before_mvt': 33, 'elapsed_sec': 188.0, 'mvts_per_sec': 145.75, 'rss_gib': 2.153278350830078}

{'buckets': '7/512', 'mvts': 31903, 'assigned_mvts': 31836, 'single': 30154, 'multiple': 1682, 'physical_flights': 33641, 'max_physical_flights': 5, 'selected': 31520, 'resampled': 31520, 'rows': 17774420, 'unresolved': 383, 'contains_mvt': 20565, 'starts_after_mvt': 10918, 'ends_before_mvt': 37, 'elapsed_sec': 189.3, 'mvts_per_sec': 168.57, 'rss_gib': 2.153278350830078}

{'buckets': '8/512', 'mvts': 36391, 'assigned_mvts': 36307, 'single': 34394, 'multiple': 1913, 'physical_flights': 38358, 'max_physical_flights': 5, 'selected': 35947, 'resampled': 35947, 'rows': 20266968, 'unresolved': 444, 'contains_mvt': 23430, 'starts_after_mvt': 12470, 'ends_before_mvt': 47, 'elapsed_sec': 189.5, 'mvts_per_sec': 192.01, 'rss_gib': 2.153278350830078}

{'buckets': '9/512', 'mvts': 40984, 'assigned_mvts': 40888, 'single': 38745, 'multiple': 2143, 'physical_flights': 43181, 'max_physical_flights': 5, 'selected': 40466, 'resampled': 40466, 'rows': 22799987, 'unresolved': 518, 'contains_mvt': 26338, 'starts_after_mvt': 14076, 'ends_before_mvt': 52, 'elapsed_sec': 191.2, 'mvts_per_sec': 214.34, 'rss_gib': 2.153278350830078}

{'buckets': '10/512', 'mvts': 45552, 'assigned_mvts': 45442, 'single': 43057, 'multiple': 2385, 'physical_flights': 47992, 'max_physical_flights': 5, 'selected': 44969, 'resampled': 44969, 'rows': 25314295, 'unresolved': 583, 'contains_mvt': 29237, 'starts_after_mvt': 15674, 'ends_before_mvt': 58, 'elapsed_sec': 195.6, 'mvts_per_sec': 232.87, 'rss_gib': 2.153278350830078}

{'buckets': '11/512', 'mvts': 50183, 'assigned_mvts': 50062, 'single': 47435, 'multiple': 2627, 'physical_flights': 52868, 'max_physical_flights': 5, 'selected': 49542, 'resampled': 49542, 'rows': 27882064, 'unresolved': 641, 'contains_mvt': 32212, 'starts_after_mvt': 17264, 'ends_before_mvt': 66, 'elapsed_sec': 195.9, 'mvts_per_sec': 256.17, 'rss_gib': 2.1532821655273438}

{'buckets': '12/512', 'mvts': 54699, 'assigned_mvts': 54567, 'single': 51713, 'multiple': 2854, 'physical_flights': 57606, 'max_physical_flights': 5, 'selected': 54000, 'resampled': 54000, 'rows': 30356971, 'unresolved': 699, 'contains_mvt': 35080, 'starts_after_mvt': 18848, 'ends_before_mvt': 72, 'elapsed_sec': 198.2, 'mvts_per_sec': 276.0, 'rss_gib': 2.1532821655273438}

{'buckets': '13/512', 'mvts': 59311, 'assigned_mvts': 59168, 'single': 56096, 'multiple': 3072, 'physical_flights': 62442, 'max_physical_flights': 5, 'selected': 58556, 'resampled': 58556, 'rows': 32923771, 'unresolved': 755, 'contains_mvt': 38035, 'starts_after_mvt': 20442, 'ends_before_mvt': 79, 'elapsed_sec': 202.9, 'mvts_per_sec': 292.3, 'rss_gib': 2.1532821655273438}

{'buckets': '14/512', 'mvts': 63932, 'assigned_mvts': 63775, 'single': 60473, 'multiple': 3302, 'physical_flights': 67290, 'max_physical_flights': 5, 'selected': 63111, 'resampled': 63111, 'rows': 35439643, 'unresolved': 821, 'contains_mvt': 40978, 'starts_after_mvt': 22049, 'ends_before_mvt': 84, 'elapsed_sec': 204.2, 'mvts_per_sec': 313.15, 'rss_gib': 2.1532821655273438}

{'buckets': '15/512', 'mvts': 68499, 'assigned_mvts': 68332, 'single': 64793, 'multiple': 3539, 'physical_flights': 72098, 'max_physical_flights': 5, 'selected': 67609, 'resampled': 67609, 'rows': 38011949, 'unresolved': 890, 'contains_mvt': 43886, 'starts_after_mvt': 23634, 'ends_before_mvt': 89, 'elapsed_sec': 205.1, 'mvts_per_sec': 334.04, 'rss_gib': 2.1532821655273438}

{'buckets': '16/512', 'mvts': 73040, 'assigned_mvts': 72863, 'single': 69140, 'multiple': 3723, 'physical_flights': 76820, 'max_physical_flights': 5, 'selected': 72087, 'resampled': 72087, 'rows': 40506016, 'unresolved': 953, 'contains_mvt': 46728, 'starts_after_mvt': 25265, 'ends_before_mvt': 94, 'elapsed_sec': 205.8, 'mvts_per_sec': 354.83, 'rss_gib': 2.1532821655273438}

{'buckets': '17/512', 'mvts': 77599, 'assigned_mvts': 77414, 'single': 73469, 'multiple': 3945, 'physical_flights': 81612, 'max_physical_flights': 5, 'selected': 76597, 'resampled': 76597, 'rows': 43042906, 'unresolved': 1002, 'contains_mvt': 49661, 'starts_after_mvt': 26840, 'ends_before_mvt': 96, 'elapsed_sec': 206.9, 'mvts_per_sec': 375.01, 'rss_gib': 2.1532821655273438}

{'buckets': '18/512', 'mvts': 82257, 'assigned_mvts': 82064, 'single': 77873, 'multiple': 4191, 'physical_flights': 86524, 'max_physical_flights': 5, 'selected': 81200, 'resampled': 81200, 'rows': 45619595, 'unresolved': 1057, 'contains_mvt': 52663, 'starts_after_mvt': 28435, 'ends_before_mvt': 102, 'elapsed_sec': 207.0, 'mvts_per_sec': 397.38, 'rss_gib': 2.1532821655273438}

{'buckets': '19/512', 'mvts': 86845, 'assigned_mvts': 86642, 'single': 82237, 'multiple': 4405, 'physical_flights': 91321, 'max_physical_flights': 5, 'selected': 85723, 'resampled': 85723, 'rows': 48243375, 'unresolved': 1122, 'contains_mvt': 55593, 'starts_after_mvt': 30023, 'ends_before_mvt': 107, 'elapsed_sec': 207.4, 'mvts_per_sec': 418.74, 'rss_gib': 2.1532821655273438}

{'buckets': '20/512', 'mvts': 91300, 'assigned_mvts': 91090, 'single': 86458, 'multiple': 4632, 'physical_flights': 96010, 'max_physical_flights': 5, 'selected': 90121, 'resampled': 90121, 'rows': 50711490, 'unresolved': 1179, 'contains_mvt': 58439, 'starts_after_mvt': 31571, 'ends_before_mvt': 111, 'elapsed_sec': 207.9, 'mvts_per_sec': 439.09, 'rss_gib': 2.1532859802246094}

{'buckets': '21/512', 'mvts': 95896, 'assigned_mvts': 95677, 'single': 90804, 'multiple': 4873, 'physical_flights': 100856, 'max_physical_flights': 5, 'selected': 94662, 'resampled': 94662, 'rows': 53222610, 'unresolved': 1234, 'contains_mvt': 61338, 'starts_after_mvt': 33209, 'ends_before_mvt': 115, 'elapsed_sec': 208.7, 'mvts_per_sec': 459.53, 'rss_gib': 2.1532859802246094}

{'buckets': '22/512', 'mvts': 100502, 'assigned_mvts': 100273, 'single': 95197, 'multiple': 5076, 'physical_flights': 105666, 'max_physical_flights': 5, 'selected': 99207, 'resampled': 99207, 'rows': 55713026, 'unresolved': 1295, 'contains_mvt': 64256, 'starts_after_mvt': 34831, 'ends_before_mvt': 120, 'elapsed_sec': 209.4, 'mvts_per_sec': 480.07, 'rss_gib': 2.1532859802246094}

{'buckets': '23/512', 'mvts': 105124, 'assigned_mvts': 104885, 'single': 99576, 'multiple': 5309, 'physical_flights': 110516, 'max_physical_flights': 5, 'selected': 103771, 'resampled': 103771, 'rows': 58314134, 'unresolved': 1353, 'contains_mvt': 67224, 'starts_after_mvt': 36424, 'ends_before_mvt': 123, 'elapsed_sec': 210.1, 'mvts_per_sec': 500.32, 'rss_gib': 2.1532859802246094}

{'buckets': '24/512', 'mvts': 109757, 'assigned_mvts': 109513, 'single': 103955, 'multiple': 5558, 'physical_flights': 115412, 'max_physical_flights': 5, 'selected': 108351, 'resampled': 108351, 'rows': 60904882, 'unresolved': 1406, 'contains_mvt': 70211, 'starts_after_mvt': 38012, 'ends_before_mvt': 128, 'elapsed_sec': 210.4, 'mvts_per_sec': 521.69, 'rss_gib': 2.1532859802246094}

{'buckets': '25/512', 'mvts': 114313, 'assigned_mvts': 114061, 'single': 108286, 'multiple': 5775, 'physical_flights': 120187, 'max_physical_flights': 5, 'selected': 112851, 'resampled': 112851, 'rows': 63444953, 'unresolved': 1462, 'contains_mvt': 73122, 'starts_after_mvt': 39594, 'ends_before_mvt': 135, 'elapsed_sec': 211.1, 'mvts_per_sec': 541.41, 'rss_gib': 2.1532859802246094}

{'buckets': '26/512', 'mvts': 118975, 'assigned_mvts': 118709, 'single': 112674, 'multiple': 6035, 'physical_flights': 125114, 'max_physical_flights': 5, 'selected': 117462, 'resampled': 117462, 'rows': 66017146, 'unresolved': 1513, 'contains_mvt': 76106, 'starts_after_mvt': 41216, 'ends_before_mvt': 140, 'elapsed_sec': 211.6, 'mvts_per_sec': 562.38, 'rss_gib': 2.1532859802246094}

{'buckets': '27/512', 'mvts': 123637, 'assigned_mvts': 123357, 'single': 117087, 'multiple': 6270, 'physical_flights': 130004, 'max_physical_flights': 5, 'selected': 122066, 'resampled': 122066, 'rows': 68588413, 'unresolved': 1571, 'contains_mvt': 79074, 'starts_after_mvt': 42847, 'ends_before_mvt': 145, 'elapsed_sec': 213.3, 'mvts_per_sec': 579.68, 'rss_gib': 2.1532859802246094}

{'buckets': '28/512', 'mvts': 128226, 'assigned_mvts': 127935, 'single': 121419, 'multiple': 6516, 'physical_flights': 134848, 'max_physical_flights': 5, 'selected': 126595, 'resampled': 126595, 'rows': 71127420, 'unresolved': 1631, 'contains_mvt': 82010, 'starts_after_mvt': 44437, 'ends_before_mvt': 148, 'elapsed_sec': 213.8, 'mvts_per_sec': 599.84, 'rss_gib': 2.1532859802246094}

{'buckets': '29/512', 'mvts': 132894, 'assigned_mvts': 132591, 'single': 125854, 'multiple': 6737, 'physical_flights': 139737, 'max_physical_flights': 5, 'selected': 131192, 'resampled': 131192, 'rows': 73752395, 'unresolved': 1702, 'contains_mvt': 84985, 'starts_after_mvt': 46056, 'ends_before_mvt': 151, 'elapsed_sec': 215.1, 'mvts_per_sec': 617.94, 'rss_gib': 2.1532859802246094}

{'buckets': '29/512', 'mvts': 132894, 'assigned_mvts': 132591, 'single': 125854, 'multiple': 6737, 'physical_flights': 139737, 'max_physical_flights': 5, 'selected': 131192, 'resampled': 131192, 'rows': 73752395, 'unresolved': 1702, 'contains_mvt': 84985, 'starts_after_mvt': 46056, 'ends_before_mvt': 151, 'elapsed_sec': 245.1, 'mvts_per_sec': 542.28, 'rss_gib': 2.1532859802246094}

{'buckets': '29/512', 'mvts': 132894, 'assigned_mvts': 132591, 'single': 125854, 'multiple': 6737, 'physical_flights': 139737, 'max_physical_flights': 5, 'selected': 131192, 'resampled': 131192, 'rows': 73752395, 'unresolved': 1702, 'contains_mvt': 84985, 'starts_after_mvt': 46056, 'ends_before_mvt': 151, 'elapsed_sec': 275.1, 'mvts_per_sec': 483.14, 'rss_gib': 2.153289794921875}

{'buckets': '29/512', 'mvts': 132894, 'assigned_mvts': 132591, 'single': 125854, 'multiple': 6737, 'physical_flights': 139737, 'max_physical_flights': 5, 'selected': 131192, 'resampled': 131192, 'rows': 73752395, 'unresolved': 1702, 'contains_mvt': 84985, 'starts_after_mvt': 46056, 'ends_before_mvt': 151, 'elapsed_sec': 305.1, 'mvts_per_sec': 435.62, 'rss_gib': 2.153289794921875}

{'buckets': '30/512', 'mvts': 137478, 'assigned_mvts': 137168, 'single': 130167, 'multiple': 7001, 'physical_flights': 144599, 'max_physical_flights': 5, 'selected': 135726, 'resampled': 135726, 'rows': 76300828, 'unresolved': 1752, 'contains_mvt': 87894, 'starts_after_mvt': 47676, 'ends_before_mvt': 156, 'elapsed_sec': 317.1, 'mvts_per_sec': 433.61, 'rss_gib': 2.153289794921875}

{'buckets': '31/512', 'mvts': 142094, 'assigned_mvts': 141774, 'single': 134535, 'multiple': 7239, 'physical_flights': 149449, 'max_physical_flights': 5, 'selected': 140300, 'resampled': 140300, 'rows': 78904815, 'unresolved': 1794, 'contains_mvt': 90855, 'starts_after_mvt': 49287, 'ends_before_mvt': 158, 'elapsed_sec': 339.4, 'mvts_per_sec': 418.67, 'rss_gib': 2.153289794921875}

{'buckets': '32/512', 'mvts': 146806, 'assigned_mvts': 146476, 'single': 138992, 'multiple': 7484, 'physical_flights': 154415, 'max_physical_flights': 5, 'selected': 144949, 'resampled': 144949, 'rows': 81545555, 'unresolved': 1857, 'contains_mvt': 93888, 'starts_after_mvt': 50895, 'ends_before_mvt': 166, 'elapsed_sec': 347.8, 'mvts_per_sec': 422.12, 'rss_gib': 2.153289794921875}

{'buckets': '33/512', 'mvts': 151344, 'assigned_mvts': 151004, 'single': 143269, 'multiple': 7735, 'physical_flights': 159214, 'max_physical_flights': 5, 'selected': 149440, 'resampled': 149440, 'rows': 84061757, 'unresolved': 1904, 'contains_mvt': 96833, 'starts_after_mvt': 52438, 'ends_before_mvt': 169, 'elapsed_sec': 354.8, 'mvts_per_sec': 426.59, 'rss_gib': 2.153289794921875}

{'buckets': '34/512', 'mvts': 156000, 'assigned_mvts': 155651, 'single': 147676, 'multiple': 7975, 'physical_flights': 164114, 'max_physical_flights': 5, 'selected': 154043, 'resampled': 154043, 'rows': 86604552, 'unresolved': 1957, 'contains_mvt': 99792, 'starts_after_mvt': 54076, 'ends_before_mvt': 175, 'elapsed_sec': 364.8, 'mvts_per_sec': 427.62, 'rss_gib': 2.153289794921875}

{'buckets': '35/512', 'mvts': 160498, 'assigned_mvts': 160139, 'single': 151921, 'multiple': 8218, 'physical_flights': 168855, 'max_physical_flights': 5, 'selected': 158499, 'resampled': 158499, 'rows': 89064758, 'unresolved': 1999, 'contains_mvt': 102669, 'starts_after_mvt': 55651, 'ends_before_mvt': 179, 'elapsed_sec': 378.0, 'mvts_per_sec': 424.61, 'rss_gib': 2.153289794921875}

{'buckets': '36/512', 'mvts': 165009, 'assigned_mvts': 164634, 'single': 156204, 'multiple': 8430, 'physical_flights': 173577, 'max_physical_flights': 5, 'selected': 162948, 'resampled': 162948, 'rows': 91550817, 'unresolved': 2061, 'contains_mvt': 105553, 'starts_after_mvt': 57213, 'ends_before_mvt': 182, 'elapsed_sec': 385.6, 'mvts_per_sec': 427.88, 'rss_gib': 2.153289794921875}

{'buckets': '37/512', 'mvts': 169551, 'assigned_mvts': 169164, 'single': 160489, 'multiple': 8675, 'physical_flights': 178367, 'max_physical_flights': 5, 'selected': 167440, 'resampled': 167440, 'rows': 94023304, 'unresolved': 2111, 'contains_mvt': 108459, 'starts_after_mvt': 58794, 'ends_before_mvt': 187, 'elapsed_sec': 390.8, 'mvts_per_sec': 433.83, 'rss_gib': 2.153289794921875}

{'buckets': '38/512', 'mvts': 174222, 'assigned_mvts': 173828, 'single': 164913, 'multiple': 8915, 'physical_flights': 183290, 'max_physical_flights': 5, 'selected': 172053, 'resampled': 172053, 'rows': 96627403, 'unresolved': 2169, 'contains_mvt': 111486, 'starts_after_mvt': 60377, 'ends_before_mvt': 190, 'elapsed_sec': 391.5, 'mvts_per_sec': 445.04, 'rss_gib': 2.153289794921875}

{'buckets': '39/512', 'mvts': 178719, 'assigned_mvts': 178313, 'single': 169182, 'multiple': 9131, 'physical_flights': 188011, 'max_physical_flights': 5, 'selected': 176497, 'resampled': 176497, 'rows': 99137058, 'unresolved': 2222, 'contains_mvt': 114342, 'starts_after_mvt': 61960, 'ends_before_mvt': 195, 'elapsed_sec': 392.9, 'mvts_per_sec': 454.84, 'rss_gib': 2.153289794921875}

{'buckets': '40/512', 'mvts': 183273, 'assigned_mvts': 182852, 'single': 173499, 'multiple': 9353, 'physical_flights': 192786, 'max_physical_flights': 5, 'selected': 180984, 'resampled': 180984, 'rows': 101641750, 'unresolved': 2289, 'contains_mvt': 117275, 'starts_after_mvt': 63510, 'ends_before_mvt': 199, 'elapsed_sec': 397.1, 'mvts_per_sec': 461.57, 'rss_gib': 2.153289794921875}

{'buckets': '41/512', 'mvts': 187901, 'assigned_mvts': 187466, 'single': 177872, 'multiple': 9594, 'physical_flights': 197655, 'max_physical_flights': 6, 'selected': 185546, 'resampled': 185546, 'rows': 104174065, 'unresolved': 2355, 'contains_mvt': 120186, 'starts_after_mvt': 65157, 'ends_before_mvt': 203, 'elapsed_sec': 397.2, 'mvts_per_sec': 473.1, 'rss_gib': 2.153289794921875}

{'buckets': '42/512', 'mvts': 192569, 'assigned_mvts': 192124, 'single': 182314, 'multiple': 9810, 'physical_flights': 202546, 'max_physical_flights': 6, 'selected': 190160, 'resampled': 190160, 'rows': 106813188, 'unresolved': 2409, 'contains_mvt': 123190, 'starts_after_mvt': 66763, 'ends_before_mvt': 207, 'elapsed_sec': 398.8, 'mvts_per_sec': 482.85, 'rss_gib': 2.153289794921875}

{'buckets': '43/512', 'mvts': 197253, 'assigned_mvts': 196797, 'single': 186750, 'multiple': 10047, 'physical_flights': 207470, 'max_physical_flights': 6, 'selected': 194795, 'resampled': 194795, 'rows': 109447249, 'unresolved': 2458, 'contains_mvt': 126193, 'starts_after_mvt': 68393, 'ends_before_mvt': 209, 'elapsed_sec': 399.9, 'mvts_per_sec': 493.29, 'rss_gib': 2.153289794921875}

{'buckets': '44/512', 'mvts': 201802, 'assigned_mvts': 201337, 'single': 191079, 'multiple': 10258, 'physical_flights': 212237, 'max_physical_flights': 6, 'selected': 199293, 'resampled': 199293, 'rows': 111948999, 'unresolved': 2509, 'contains_mvt': 129115, 'starts_after_mvt': 69965, 'ends_before_mvt': 213, 'elapsed_sec': 401.2, 'mvts_per_sec': 503.0, 'rss_gib': 2.153289794921875}

{'buckets': '45/512', 'mvts': 206469, 'assigned_mvts': 205999, 'single': 195491, 'multiple': 10508, 'physical_flights': 217159, 'max_physical_flights': 6, 'selected': 203912, 'resampled': 203912, 'rows': 114595170, 'unresolved': 2557, 'contains_mvt': 132148, 'starts_after_mvt': 71549, 'ends_before_mvt': 215, 'elapsed_sec': 402.2, 'mvts_per_sec': 513.37, 'rss_gib': 2.153289794921875}

{'buckets': '46/512', 'mvts': 211018, 'assigned_mvts': 210537, 'single': 199773, 'multiple': 10764, 'physical_flights': 221968, 'max_physical_flights': 6, 'selected': 208400, 'resampled': 208400, 'rows': 117085506, 'unresolved': 2618, 'contains_mvt': 135013, 'starts_after_mvt': 73168, 'ends_before_mvt': 219, 'elapsed_sec': 404.1, 'mvts_per_sec': 522.18, 'rss_gib': 2.153289794921875}

{'buckets': '47/512', 'mvts': 215606, 'assigned_mvts': 215120, 'single': 204104, 'multiple': 11016, 'physical_flights': 226820, 'max_physical_flights': 6, 'selected': 212947, 'resampled': 212947, 'rows': 119668599, 'unresolved': 2659, 'contains_mvt': 137965, 'starts_after_mvt': 74760, 'ends_before_mvt': 222, 'elapsed_sec': 405.4, 'mvts_per_sec': 531.82, 'rss_gib': 2.153289794921875}

{'buckets': '48/512', 'mvts': 220138, 'assigned_mvts': 219643, 'single': 208358, 'multiple': 11285, 'physical_flights': 231628, 'max_physical_flights': 6, 'selected': 217413, 'resampled': 217413, 'rows': 122134250, 'unresolved': 2725, 'contains_mvt': 140873, 'starts_after_mvt': 76316, 'ends_before_mvt': 224, 'elapsed_sec': 406.2, 'mvts_per_sec': 542.01, 'rss_gib': 2.153289794921875}

{'buckets': '49/512', 'mvts': 224696, 'assigned_mvts': 224194, 'single': 212674, 'multiple': 11520, 'physical_flights': 236431, 'max_physical_flights': 6, 'selected': 221906, 'resampled': 221906, 'rows': 124622459, 'unresolved': 2790, 'contains_mvt': 143714, 'starts_after_mvt': 77963, 'ends_before_mvt': 229, 'elapsed_sec': 406.2, 'mvts_per_sec': 553.18, 'rss_gib': 2.153289794921875}

{'buckets': '50/512', 'mvts': 229200, 'assigned_mvts': 228686, 'single': 216924, 'multiple': 11762, 'physical_flights': 241184, 'max_physical_flights': 6, 'selected': 226360, 'resampled': 226360, 'rows': 127083180, 'unresolved': 2840, 'contains_mvt': 146570, 'starts_after_mvt': 79558, 'ends_before_mvt': 232, 'elapsed_sec': 408.1, 'mvts_per_sec': 561.61, 'rss_gib': 2.153289794921875}

{'buckets': '51/512', 'mvts': 233729, 'assigned_mvts': 233207, 'single': 221207, 'multiple': 12000, 'physical_flights': 245951, 'max_physical_flights': 6, 'selected': 230838, 'resampled': 230838, 'rows': 129627689, 'unresolved': 2891, 'contains_mvt': 149480, 'starts_after_mvt': 81123, 'ends_before_mvt': 235, 'elapsed_sec': 410.5, 'mvts_per_sec': 569.42, 'rss_gib': 2.153289794921875}

{'buckets': '52/512', 'mvts': 238401, 'assigned_mvts': 237868, 'single': 225639, 'multiple': 12229, 'physical_flights': 250858, 'max_physical_flights': 6, 'selected': 235458, 'resampled': 235458, 'rows': 132201568, 'unresolved': 2943, 'contains_mvt': 152452, 'starts_after_mvt': 82766, 'ends_before_mvt': 240, 'elapsed_sec': 410.9, 'mvts_per_sec': 580.18, 'rss_gib': 2.153289794921875}

{'buckets': '53/512', 'mvts': 242957, 'assigned_mvts': 242411, 'single': 229960, 'multiple': 12451, 'physical_flights': 255636, 'max_physical_flights': 6, 'selected': 239953, 'resampled': 239953, 'rows': 134743270, 'unresolved': 3004, 'contains_mvt': 155326, 'starts_after_mvt': 84382, 'ends_before_mvt': 245, 'elapsed_sec': 411.9, 'mvts_per_sec': 589.87, 'rss_gib': 2.153289794921875}

{'buckets': '54/512', 'mvts': 247573, 'assigned_mvts': 247018, 'single': 234349, 'multiple': 12669, 'physical_flights': 260473, 'max_physical_flights': 6, 'selected': 244512, 'resampled': 244512, 'rows': 137285704, 'unresolved': 3061, 'contains_mvt': 158265, 'starts_after_mvt': 86000, 'ends_before_mvt': 247, 'elapsed_sec': 414.3, 'mvts_per_sec': 597.55, 'rss_gib': 2.153289794921875}

{'buckets': '55/512', 'mvts': 252064, 'assigned_mvts': 251502, 'single': 238588, 'multiple': 12914, 'physical_flights': 265222, 'max_physical_flights': 6, 'selected': 248953, 'resampled': 248953, 'rows': 139776396, 'unresolved': 3111, 'contains_mvt': 161107, 'starts_after_mvt': 87599, 'ends_before_mvt': 247, 'elapsed_sec': 415.0, 'mvts_per_sec': 607.44, 'rss_gib': 2.153289794921875}

{'buckets': '56/512', 'mvts': 256800, 'assigned_mvts': 256231, 'single': 243045, 'multiple': 13186, 'physical_flights': 270238, 'max_physical_flights': 6, 'selected': 253627, 'resampled': 253627, 'rows': 142432622, 'unresolved': 3173, 'contains_mvt': 164138, 'starts_after_mvt': 89239, 'ends_before_mvt': 250, 'elapsed_sec': 415.9, 'mvts_per_sec': 617.52, 'rss_gib': 2.153289794921875}

{'buckets': '57/512', 'mvts': 261404, 'assigned_mvts': 260822, 'single': 247402, 'multiple': 13420, 'physical_flights': 275079, 'max_physical_flights': 6, 'selected': 258172, 'resampled': 258172, 'rows': 144952590, 'unresolved': 3232, 'contains_mvt': 167088, 'starts_after_mvt': 90829, 'ends_before_mvt': 255, 'elapsed_sec': 417.1, 'mvts_per_sec': 626.66, 'rss_gib': 2.153289794921875}

{'buckets': '58/512', 'mvts': 266032, 'assigned_mvts': 265441, 'single': 251774, 'multiple': 13667, 'physical_flights': 279963, 'max_physical_flights': 6, 'selected': 262737, 'resampled': 262737, 'rows': 147513148, 'unresolved': 3295, 'contains_mvt': 170040, 'starts_after_mvt': 92440, 'ends_before_mvt': 257, 'elapsed_sec': 417.5, 'mvts_per_sec': 637.22, 'rss_gib': 2.1532936096191406}

{'buckets': '58/512', 'mvts': 266032, 'assigned_mvts': 265441, 'single': 251774, 'multiple': 13667, 'physical_flights': 279963, 'max_physical_flights': 6, 'selected': 262737, 'resampled': 262737, 'rows': 147513148, 'unresolved': 3295, 'contains_mvt': 170040, 'starts_after_mvt': 92440, 'ends_before_mvt': 257, 'elapsed_sec': 447.5, 'mvts_per_sec': 594.5, 'rss_gib': 2.1532936096191406}

{'buckets': '58/512', 'mvts': 266032, 'assigned_mvts': 265441, 'single': 251774, 'multiple': 13667, 'physical_flights': 279963, 'max_physical_flights': 6, 'selected': 262737, 'resampled': 262737, 'rows': 147513148, 'unresolved': 3295, 'contains_mvt': 170040, 'starts_after_mvt': 92440, 'ends_before_mvt': 257, 'elapsed_sec': 477.5, 'mvts_per_sec': 557.14, 'rss_gib': 2.1532936096191406}

{'buckets': '58/512', 'mvts': 266032, 'assigned_mvts': 265441, 'single': 251774, 'multiple': 13667, 'physical_flights': 279963, 'max_physical_flights': 6, 'selected': 262737, 'resampled': 262737, 'rows': 147513148, 'unresolved': 3295, 'contains_mvt': 170040, 'starts_after_mvt': 92440, 'ends_before_mvt': 257, 'elapsed_sec': 507.5, 'mvts_per_sec': 524.2, 'rss_gib': 2.1532936096191406}

{'buckets': '59/512', 'mvts': 270634, 'assigned_mvts': 270031, 'single': 256130, 'multiple': 13901, 'physical_flights': 284796, 'max_physical_flights': 6, 'selected': 267282, 'resampled': 267282, 'rows': 150067929, 'unresolved': 3352, 'contains_mvt': 173018, 'starts_after_mvt': 94004, 'ends_before_mvt': 260, 'elapsed_sec': 523.9, 'mvts_per_sec': 516.55, 'rss_gib': 2.1532936096191406}

{'buckets': '60/512', 'mvts': 275340, 'assigned_mvts': 274726, 'single': 260578, 'multiple': 14148, 'physical_flights': 289753, 'max_physical_flights': 6, 'selected': 271926, 'resampled': 271926, 'rows': 152714858, 'unresolved': 3414, 'contains_mvt': 176029, 'starts_after_mvt': 95632, 'ends_before_mvt': 265, 'elapsed_sec': 539.1, 'mvts_per_sec': 510.7, 'rss_gib': 2.1532936096191406}

{'buckets': '61/512', 'mvts': 279915, 'assigned_mvts': 279292, 'single': 264885, 'multiple': 14407, 'physical_flights': 294595, 'max_physical_flights': 6, 'selected': 276460, 'resampled': 276460, 'rows': 155254754, 'unresolved': 3455, 'contains_mvt': 178897, 'starts_after_mvt': 97290, 'ends_before_mvt': 273, 'elapsed_sec': 547.1, 'mvts_per_sec': 511.63, 'rss_gib': 2.1532936096191406}

{'buckets': '62/512', 'mvts': 284471, 'assigned_mvts': 283842, 'single': 269198, 'multiple': 14644, 'physical_flights': 299401, 'max_physical_flights': 6, 'selected': 280967, 'resampled': 280967, 'rows': 157832024, 'unresolved': 3504, 'contains_mvt': 181861, 'starts_after_mvt': 98829, 'ends_before_mvt': 277, 'elapsed_sec': 549.2, 'mvts_per_sec': 517.93, 'rss_gib': 2.1532936096191406}

{'buckets': '63/512', 'mvts': 289243, 'assigned_mvts': 288607, 'single': 273731, 'multiple': 14876, 'physical_flights': 304415, 'max_physical_flights': 6, 'selected': 285677, 'resampled': 285677, 'rows': 160487496, 'unresolved': 3566, 'contains_mvt': 184956, 'starts_after_mvt': 100440, 'ends_before_mvt': 281, 'elapsed_sec': 551.5, 'mvts_per_sec': 524.43, 'rss_gib': 2.1532936096191406}

{'buckets': '64/512', 'mvts': 293934, 'assigned_mvts': 293287, 'single': 278183, 'multiple': 15104, 'physical_flights': 309339, 'max_physical_flights': 6, 'selected': 290312, 'resampled': 290312, 'rows': 163049833, 'unresolved': 3622, 'contains_mvt': 187929, 'starts_after_mvt': 102100, 'ends_before_mvt': 283, 'elapsed_sec': 555.6, 'mvts_per_sec': 529.05, 'rss_gib': 2.1532936096191406}

{'buckets': '65/512', 'mvts': 298511, 'assigned_mvts': 297855, 'single': 282531, 'multiple': 15324, 'physical_flights': 314141, 'max_physical_flights': 6, 'selected': 294824, 'resampled': 294824, 'rows': 165564813, 'unresolved': 3687, 'contains_mvt': 190828, 'starts_after_mvt': 103708, 'ends_before_mvt': 288, 'elapsed_sec': 558.8, 'mvts_per_sec': 534.15, 'rss_gib': 2.1532936096191406}

{'buckets': '66/512', 'mvts': 303100, 'assigned_mvts': 302435, 'single': 286870, 'multiple': 15565, 'physical_flights': 318980, 'max_physical_flights': 6, 'selected': 299364, 'resampled': 299364, 'rows': 168051618, 'unresolved': 3736, 'contains_mvt': 193732, 'starts_after_mvt': 105339, 'ends_before_mvt': 293, 'elapsed_sec': 562.2, 'mvts_per_sec': 539.1, 'rss_gib': 2.1532936096191406}

{'buckets': '67/512', 'mvts': 307729, 'assigned_mvts': 307047, 'single': 291257, 'multiple': 15790, 'physical_flights': 323829, 'max_physical_flights': 6, 'selected': 303934, 'resampled': 303934, 'rows': 170646990, 'unresolved': 3795, 'contains_mvt': 196766, 'starts_after_mvt': 106869, 'ends_before_mvt': 299, 'elapsed_sec': 572.9, 'mvts_per_sec': 537.1, 'rss_gib': 2.1532936096191406}

{'buckets': '68/512', 'mvts': 312280, 'assigned_mvts': 311593, 'single': 295563, 'multiple': 16030, 'physical_flights': 328629, 'max_physical_flights': 6, 'selected': 308438, 'resampled': 308438, 'rows': 173099823, 'unresolved': 3842, 'contains_mvt': 199618, 'starts_after_mvt': 108517, 'ends_before_mvt': 303, 'elapsed_sec': 574.2, 'mvts_per_sec': 543.85, 'rss_gib': 2.1532936096191406}

{'buckets': '69/512', 'mvts': 316894, 'assigned_mvts': 316194, 'single': 299943, 'multiple': 16251, 'physical_flights': 333466, 'max_physical_flights': 6, 'selected': 312989, 'resampled': 312989, 'rows': 175678690, 'unresolved': 3905, 'contains_mvt': 202585, 'starts_after_mvt': 110097, 'ends_before_mvt': 307, 'elapsed_sec': 579.8, 'mvts_per_sec': 546.54, 'rss_gib': 2.1532936096191406}

{'buckets': '70/512', 'mvts': 321330, 'assigned_mvts': 320626, 'single': 304166, 'multiple': 16460, 'physical_flights': 338122, 'max_physical_flights': 6, 'selected': 317373, 'resampled': 317373, 'rows': 178155720, 'unresolved': 3957, 'contains_mvt': 205455, 'starts_after_mvt': 111608, 'ends_before_mvt': 310, 'elapsed_sec': 590.2, 'mvts_per_sec': 544.46, 'rss_gib': 2.1532936096191406}

{'buckets': '71/512', 'mvts': 325950, 'assigned_mvts': 325233, 'single': 308514, 'multiple': 16719, 'physical_flights': 343006, 'max_physical_flights': 6, 'selected': 321936, 'resampled': 321936, 'rows': 180786042, 'unresolved': 4014, 'contains_mvt': 208508, 'starts_after_mvt': 113116, 'ends_before_mvt': 312, 'elapsed_sec': 592.3, 'mvts_per_sec': 550.29, 'rss_gib': 2.1532936096191406}

{'buckets': '72/512', 'mvts': 330550, 'assigned_mvts': 329825, 'single': 312890, 'multiple': 16935, 'physical_flights': 347830, 'max_physical_flights': 6, 'selected': 326485, 'resampled': 326485, 'rows': 183389853, 'unresolved': 4065, 'contains_mvt': 211551, 'starts_after_mvt': 114615, 'ends_before_mvt': 319, 'elapsed_sec': 597.3, 'mvts_per_sec': 553.39, 'rss_gib': 2.1532936096191406}

{'buckets': '73/512', 'mvts': 335166, 'assigned_mvts': 334437, 'single': 317269, 'multiple': 17168, 'physical_flights': 352688, 'max_physical_flights': 6, 'selected': 331053, 'resampled': 331053, 'rows': 185890605, 'unresolved': 4113, 'contains_mvt': 214506, 'starts_after_mvt': 116221, 'ends_before_mvt': 326, 'elapsed_sec': 599.3, 'mvts_per_sec': 559.3, 'rss_gib': 2.1532936096191406}

{'buckets': '74/512', 'mvts': 339745, 'assigned_mvts': 339007, 'single': 321613, 'multiple': 17394, 'physical_flights': 357507, 'max_physical_flights': 6, 'selected': 335572, 'resampled': 335572, 'rows': 188491125, 'unresolved': 4173, 'contains_mvt': 217459, 'starts_after_mvt': 117785, 'ends_before_mvt': 328, 'elapsed_sec': 599.8, 'mvts_per_sec': 566.4, 'rss_gib': 2.1532936096191406}

{'buckets': '75/512', 'mvts': 344405, 'assigned_mvts': 343656, 'single': 326013, 'multiple': 17643, 'physical_flights': 362419, 'max_physical_flights': 6, 'selected': 340173, 'resampled': 340173, 'rows': 191026461, 'unresolved': 4232, 'contains_mvt': 220429, 'starts_after_mvt': 119412, 'ends_before_mvt': 332, 'elapsed_sec': 603.2, 'mvts_per_sec': 571.0, 'rss_gib': 2.1532936096191406}

{'buckets': '76/512', 'mvts': 349097, 'assigned_mvts': 348341, 'single': 330453, 'multiple': 17888, 'physical_flights': 367356, 'max_physical_flights': 6, 'selected': 344821, 'resampled': 344821, 'rows': 193677244, 'unresolved': 4276, 'contains_mvt': 223440, 'starts_after_mvt': 121042, 'ends_before_mvt': 339, 'elapsed_sec': 604.8, 'mvts_per_sec': 577.2, 'rss_gib': 2.1532936096191406}

{'buckets': '77/512', 'mvts': 353695, 'assigned_mvts': 352926, 'single': 334813, 'multiple': 18113, 'physical_flights': 372185, 'max_physical_flights': 6, 'selected': 349364, 'resampled': 349364, 'rows': 196179923, 'unresolved': 4331, 'contains_mvt': 226328, 'starts_after_mvt': 122693, 'ends_before_mvt': 343, 'elapsed_sec': 606.9, 'mvts_per_sec': 582.75, 'rss_gib': 2.1532936096191406}

{'buckets': '78/512', 'mvts': 358281, 'assigned_mvts': 357497, 'single': 339161, 'multiple': 18336, 'physical_flights': 376991, 'max_physical_flights': 6, 'selected': 353882, 'resampled': 353882, 'rows': 198688045, 'unresolved': 4399, 'contains_mvt': 229204, 'starts_after_mvt': 124332, 'ends_before_mvt': 346, 'elapsed_sec': 608.9, 'mvts_per_sec': 588.37, 'rss_gib': 2.1532936096191406}

{'buckets': '79/512', 'mvts': 362873, 'assigned_mvts': 362080, 'single': 343529, 'multiple': 18551, 'physical_flights': 381802, 'max_physical_flights': 6, 'selected': 358421, 'resampled': 358421, 'rows': 201297202, 'unresolved': 4452, 'contains_mvt': 232145, 'starts_after_mvt': 125926, 'ends_before_mvt': 350, 'elapsed_sec': 613.6, 'mvts_per_sec': 591.41, 'rss_gib': 2.1532936096191406}

{'buckets': '80/512', 'mvts': 367462, 'assigned_mvts': 366663, 'single': 347886, 'multiple': 18777, 'physical_flights': 386621, 'max_physical_flights': 6, 'selected': 362961, 'resampled': 362961, 'rows': 203839713, 'unresolved': 4501, 'contains_mvt': 235084, 'starts_after_mvt': 127523, 'ends_before_mvt': 354, 'elapsed_sec': 615.3, 'mvts_per_sec': 597.18, 'rss_gib': 2.1532936096191406}

{'buckets': '81/512', 'mvts': 371930, 'assigned_mvts': 371115, 'single': 352089, 'multiple': 19026, 'physical_flights': 391336, 'max_physical_flights': 6, 'selected': 367370, 'resampled': 367370, 'rows': 206266404, 'unresolved': 4560, 'contains_mvt': 237939, 'starts_after_mvt': 129073, 'ends_before_mvt': 358, 'elapsed_sec': 616.1, 'mvts_per_sec': 603.72, 'rss_gib': 2.1532936096191406}

{'buckets': '82/512', 'mvts': 376470, 'assigned_mvts': 375645, 'single': 356408, 'multiple': 19237, 'physical_flights': 396088, 'max_physical_flights': 6, 'selected': 371853, 'resampled': 371853, 'rows': 208743155, 'unresolved': 4617, 'contains_mvt': 240846, 'starts_after_mvt': 130644, 'ends_before_mvt': 363, 'elapsed_sec': 619.2, 'mvts_per_sec': 608.0, 'rss_gib': 2.1532936096191406}

{'buckets': '83/512', 'mvts': 381122, 'assigned_mvts': 380290, 'single': 360822, 'multiple': 19468, 'physical_flights': 400981, 'max_physical_flights': 6, 'selected': 376450, 'resampled': 376450, 'rows': 211296558, 'unresolved': 4672, 'contains_mvt': 243839, 'starts_after_mvt': 132241, 'ends_before_mvt': 370, 'elapsed_sec': 620.1, 'mvts_per_sec': 614.6, 'rss_gib': 2.1532936096191406}

{'buckets': '84/512', 'mvts': 385703, 'assigned_mvts': 384863, 'single': 365145, 'multiple': 19718, 'physical_flights': 405820, 'max_physical_flights': 6, 'selected': 380971, 'resampled': 380971, 'rows': 213869392, 'unresolved': 4732, 'contains_mvt': 246771, 'starts_after_mvt': 133827, 'ends_before_mvt': 373, 'elapsed_sec': 621.6, 'mvts_per_sec': 620.47, 'rss_gib': 2.1532936096191406}

{'buckets': '85/512', 'mvts': 390373, 'assigned_mvts': 389527, 'single': 369573, 'multiple': 19954, 'physical_flights': 410735, 'max_physical_flights': 6, 'selected': 385577, 'resampled': 385577, 'rows': 216405480, 'unresolved': 4796, 'contains_mvt': 249750, 'starts_after_mvt': 135450, 'ends_before_mvt': 377, 'elapsed_sec': 623.2, 'mvts_per_sec': 626.36, 'rss_gib': 2.1532936096191406}

{'buckets': '86/512', 'mvts': 394956, 'assigned_mvts': 394106, 'single': 373930, 'multiple': 20176, 'physical_flights': 415551, 'max_physical_flights': 6, 'selected': 390119, 'resampled': 390119, 'rows': 218964725, 'unresolved': 4837, 'contains_mvt': 252728, 'starts_after_mvt': 137013, 'ends_before_mvt': 378, 'elapsed_sec': 627.5, 'mvts_per_sec': 629.43, 'rss_gib': 2.1532936096191406}

{'buckets': '87/512', 'mvts': 399605, 'assigned_mvts': 398740, 'single': 378315, 'multiple': 20425, 'physical_flights': 420453, 'max_physical_flights': 6, 'selected': 394715, 'resampled': 394715, 'rows': 221542607, 'unresolved': 4890, 'contains_mvt': 255672, 'starts_after_mvt': 138661, 'ends_before_mvt': 382, 'elapsed_sec': 630.6, 'mvts_per_sec': 633.67, 'rss_gib': 2.1532936096191406}

{'buckets': '87/512', 'mvts': 399605, 'assigned_mvts': 398740, 'single': 378315, 'multiple': 20425, 'physical_flights': 420453, 'max_physical_flights': 6, 'selected': 394715, 'resampled': 394715, 'rows': 221542607, 'unresolved': 4890, 'contains_mvt': 255672, 'starts_after_mvt': 138661, 'ends_before_mvt': 382, 'elapsed_sec': 660.6, 'mvts_per_sec': 604.9, 'rss_gib': 2.1532936096191406}

{'buckets': '88/512', 'mvts': 404271, 'assigned_mvts': 403392, 'single': 382752, 'multiple': 20640, 'physical_flights': 425332, 'max_physical_flights': 6, 'selected': 399314, 'resampled': 399314, 'rows': 224069718, 'unresolved': 4957, 'contains_mvt': 258604, 'starts_after_mvt': 140323, 'ends_before_mvt': 387, 'elapsed_sec': 679.2, 'mvts_per_sec': 595.21, 'rss_gib': 2.1532936096191406}

{'buckets': '89/512', 'mvts': 408810, 'assigned_mvts': 407924, 'single': 387040, 'multiple': 20884, 'physical_flights': 430129, 'max_physical_flights': 6, 'selected': 403796, 'resampled': 403796, 'rows': 226525186, 'unresolved': 5014, 'contains_mvt': 261493, 'starts_after_mvt': 141914, 'ends_before_mvt': 389, 'elapsed_sec': 691.6, 'mvts_per_sec': 591.07, 'rss_gib': 2.1532936096191406}

{'buckets': '90/512', 'mvts': 413474, 'assigned_mvts': 412581, 'single': 391443, 'multiple': 21138, 'physical_flights': 435052, 'max_physical_flights': 6, 'selected': 408402, 'resampled': 408402, 'rows': 229199270, 'unresolved': 5072, 'contains_mvt': 264535, 'starts_after_mvt': 143473, 'ends_before_mvt': 394, 'elapsed_sec': 721.6, 'mvts_per_sec': 572.98, 'rss_gib': 2.1532936096191406}

{'buckets': '91/512', 'mvts': 418128, 'assigned_mvts': 417224, 'single': 395858, 'multiple': 21366, 'physical_flights': 439935, 'max_physical_flights': 6, 'selected': 412999, 'resampled': 412999, 'rows': 231812542, 'unresolved': 5129, 'contains_mvt': 267529, 'starts_after_mvt': 145070, 'ends_before_mvt': 400, 'elapsed_sec': 732.5, 'mvts_per_sec': 570.86, 'rss_gib': 2.1532936096191406}

{'buckets': '92/512', 'mvts': 422690, 'assigned_mvts': 421776, 'single': 400166, 'multiple': 21610, 'physical_flights': 444745, 'max_physical_flights': 6, 'selected': 417511, 'resampled': 417511, 'rows': 234348559, 'unresolved': 5179, 'contains_mvt': 270472, 'starts_after_mvt': 146636, 'ends_before_mvt': 403, 'elapsed_sec': 738.9, 'mvts_per_sec': 572.07, 'rss_gib': 2.1532936096191406}

{'buckets': '93/512', 'mvts': 427316, 'assigned_mvts': 426394, 'single': 404539, 'multiple': 21855, 'physical_flights': 449624, 'max_physical_flights': 6, 'selected': 422078, 'resampled': 422078, 'rows': 236905283, 'unresolved': 5238, 'contains_mvt': 273436, 'starts_after_mvt': 148236, 'ends_before_mvt': 406, 'elapsed_sec': 740.2, 'mvts_per_sec': 577.26, 'rss_gib': 2.1532936096191406}

{'buckets': '94/512', 'mvts': 431844, 'assigned_mvts': 430911, 'single': 408825, 'multiple': 22086, 'physical_flights': 454385, 'max_physical_flights': 6, 'selected': 426536, 'resampled': 426536, 'rows': 239438617, 'unresolved': 5308, 'contains_mvt': 276302, 'starts_after_mvt': 149823, 'ends_before_mvt': 411, 'elapsed_sec': 741.9, 'mvts_per_sec': 582.05, 'rss_gib': 2.1532936096191406}

{'buckets': '95/512', 'mvts': 436433, 'assigned_mvts': 435487, 'single': 413148, 'multiple': 22339, 'physical_flights': 459229, 'max_physical_flights': 8, 'selected': 431071, 'resampled': 431071, 'rows': 242025898, 'unresolved': 5362, 'contains_mvt': 279229, 'starts_after_mvt': 151425, 'ends_before_mvt': 417, 'elapsed_sec': 766.0, 'mvts_per_sec': 569.78, 'rss_gib': 2.1532936096191406}

{'buckets': '96/512', 'mvts': 441149, 'assigned_mvts': 440195, 'single': 417624, 'multiple': 22571, 'physical_flights': 464184, 'max_physical_flights': 8, 'selected': 435732, 'resampled': 435732, 'rows': 244617838, 'unresolved': 5417, 'contains_mvt': 282284, 'starts_after_mvt': 153028, 'ends_before_mvt': 420, 'elapsed_sec': 768.5, 'mvts_per_sec': 574.01, 'rss_gib': 2.1532936096191406}

{'buckets': '97/512', 'mvts': 445819, 'assigned_mvts': 444858, 'single': 422040, 'multiple': 22818, 'physical_flights': 469116, 'max_physical_flights': 8, 'selected': 440353, 'resampled': 440353, 'rows': 247219033, 'unresolved': 5466, 'contains_mvt': 285287, 'starts_after_mvt': 154642, 'ends_before_mvt': 424, 'elapsed_sec': 773.9, 'mvts_per_sec': 576.06, 'rss_gib': 2.1532936096191406}

{'buckets': '98/512', 'mvts': 450437, 'assigned_mvts': 449470, 'single': 426407, 'multiple': 23063, 'physical_flights': 473982, 'max_physical_flights': 8, 'selected': 444911, 'resampled': 444911, 'rows': 249773450, 'unresolved': 5526, 'contains_mvt': 288269, 'starts_after_mvt': 156215, 'ends_before_mvt': 427, 'elapsed_sec': 777.5, 'mvts_per_sec': 579.33, 'rss_gib': 2.1532936096191406}

{'buckets': '99/512', 'mvts': 454981, 'assigned_mvts': 454008, 'single': 430694, 'multiple': 23314, 'physical_flights': 478789, 'max_physical_flights': 8, 'selected': 449409, 'resampled': 449409, 'rows': 252321257, 'unresolved': 5572, 'contains_mvt': 291183, 'starts_after_mvt': 157794, 'ends_before_mvt': 432, 'elapsed_sec': 777.6, 'mvts_per_sec': 585.1, 'rss_gib': 2.1532936096191406}

{'buckets': '100/512', 'mvts': 459523, 'assigned_mvts': 458542, 'single': 434992, 'multiple': 23550, 'physical_flights': 483571, 'max_physical_flights': 8, 'selected': 453890, 'resampled': 453890, 'rows': 254827745, 'unresolved': 5633, 'contains_mvt': 294127, 'starts_after_mvt': 159328, 'ends_before_mvt': 435, 'elapsed_sec': 780.2, 'mvts_per_sec': 588.98, 'rss_gib': 2.1532936096191406}

{'buckets': '101/512', 'mvts': 464034, 'assigned_mvts': 463043, 'single': 439273, 'multiple': 23770, 'physical_flights': 488305, 'max_physical_flights': 8, 'selected': 458342, 'resampled': 458342, 'rows': 257340716, 'unresolved': 5692, 'contains_mvt': 296994, 'starts_after_mvt': 160908, 'ends_before_mvt': 440, 'elapsed_sec': 786.8, 'mvts_per_sec': 589.75, 'rss_gib': 2.1532936096191406}

{'buckets': '102/512', 'mvts': 468536, 'assigned_mvts': 467536, 'single': 443529, 'multiple': 24007, 'physical_flights': 493045, 'max_physical_flights': 8, 'selected': 462785, 'resampled': 462785, 'rows': 259825719, 'unresolved': 5751, 'contains_mvt': 299819, 'starts_after_mvt': 162524, 'ends_before_mvt': 442, 'elapsed_sec': 799.3, 'mvts_per_sec': 586.15, 'rss_gib': 2.1532936096191406}

{'buckets': '103/512', 'mvts': 472988, 'assigned_mvts': 471979, 'single': 447752, 'multiple': 24227, 'physical_flights': 497723, 'max_physical_flights': 8, 'selected': 467192, 'resampled': 467192, 'rows': 262295895, 'unresolved': 5796, 'contains_mvt': 302672, 'starts_after_mvt': 164071, 'ends_before_mvt': 449, 'elapsed_sec': 807.0, 'mvts_per_sec': 586.09, 'rss_gib': 2.1532936096191406}

{'buckets': '104/512', 'mvts': 477615, 'assigned_mvts': 476593, 'single': 452148, 'multiple': 24445, 'physical_flights': 502564, 'max_physical_flights': 8, 'selected': 471761, 'resampled': 471761, 'rows': 264842361, 'unresolved': 5854, 'contains_mvt': 305648, 'starts_after_mvt': 165662, 'ends_before_mvt': 451, 'elapsed_sec': 810.1, 'mvts_per_sec': 589.6, 'rss_gib': 2.1532936096191406}

{'buckets': '105/512', 'mvts': 482235, 'assigned_mvts': 481206, 'single': 456518, 'multiple': 24688, 'physical_flights': 507443, 'max_physical_flights': 8, 'selected': 476331, 'resampled': 476331, 'rows': 267409465, 'unresolved': 5904, 'contains_mvt': 308592, 'starts_after_mvt': 167281, 'ends_before_mvt': 458, 'elapsed_sec': 810.8, 'mvts_per_sec': 594.73, 'rss_gib': 2.1532936096191406}

{'buckets': '106/512', 'mvts': 486734, 'assigned_mvts': 485691, 'single': 460770, 'multiple': 24921, 'physical_flights': 512177, 'max_physical_flights': 8, 'selected': 480770, 'resampled': 480770, 'rows': 269866206, 'unresolved': 5964, 'contains_mvt': 311396, 'starts_after_mvt': 168912, 'ends_before_mvt': 462, 'elapsed_sec': 811.0, 'mvts_per_sec': 600.16, 'rss_gib': 2.1532936096191406}

{'buckets': '107/512', 'mvts': 491378, 'assigned_mvts': 490328, 'single': 465160, 'multiple': 25168, 'physical_flights': 517074, 'max_physical_flights': 8, 'selected': 485367, 'resampled': 485367, 'rows': 272411254, 'unresolved': 6011, 'contains_mvt': 314339, 'starts_after_mvt': 170558, 'ends_before_mvt': 470, 'elapsed_sec': 812.5, 'mvts_per_sec': 604.8, 'rss_gib': 2.1532936096191406}

{'buckets': '108/512', 'mvts': 496003, 'assigned_mvts': 494949, 'single': 469554, 'multiple': 25395, 'physical_flights': 521939, 'max_physical_flights': 8, 'selected': 489926, 'resampled': 489926, 'rows': 274902546, 'unresolved': 6077, 'contains_mvt': 317278, 'starts_after_mvt': 172176, 'ends_before_mvt': 472, 'elapsed_sec': 814.8, 'mvts_per_sec': 608.77, 'rss_gib': 2.1532936096191406}

{'buckets': '109/512', 'mvts': 500455, 'assigned_mvts': 499395, 'single': 473761, 'multiple': 25634, 'physical_flights': 526638, 'max_physical_flights': 8, 'selected': 494334, 'resampled': 494334, 'rows': 277340085, 'unresolved': 6121, 'contains_mvt': 320132, 'starts_after_mvt': 173721, 'ends_before_mvt': 481, 'elapsed_sec': 816.4, 'mvts_per_sec': 613.01, 'rss_gib': 2.1532936096191406}

{'buckets': '110/512', 'mvts': 505094, 'assigned_mvts': 504020, 'single': 478132, 'multiple': 25888, 'physical_flights': 531529, 'max_physical_flights': 8, 'selected': 498912, 'resampled': 498912, 'rows': 279916419, 'unresolved': 6182, 'contains_mvt': 323094, 'starts_after_mvt': 175334, 'ends_before_mvt': 484, 'elapsed_sec': 819.7, 'mvts_per_sec': 616.16, 'rss_gib': 2.1532936096191406}

{'buckets': '111/512', 'mvts': 509613, 'assigned_mvts': 508528, 'single': 482395, 'multiple': 26133, 'physical_flights': 536295, 'max_physical_flights': 8, 'selected': 503374, 'resampled': 503374, 'rows': 282399185, 'unresolved': 6239, 'contains_mvt': 325984, 'starts_after_mvt': 176900, 'ends_before_mvt': 490, 'elapsed_sec': 821.1, 'mvts_per_sec': 620.66, 'rss_gib': 2.1532936096191406}

{'buckets': '112/512', 'mvts': 514264, 'assigned_mvts': 513167, 'single': 486778, 'multiple': 26389, 'physical_flights': 541204, 'max_physical_flights': 8, 'selected': 507968, 'resampled': 507968, 'rows': 284992721, 'unresolved': 6296, 'contains_mvt': 329043, 'starts_after_mvt': 178429, 'ends_before_mvt': 496, 'elapsed_sec': 821.2, 'mvts_per_sec': 626.24, 'rss_gib': 2.1532936096191406}

{'buckets': '113/512', 'mvts': 518934, 'assigned_mvts': 517827, 'single': 491191, 'multiple': 26636, 'physical_flights': 546129, 'max_physical_flights': 8, 'selected': 512568, 'resampled': 512568, 'rows': 287632216, 'unresolved': 6366, 'contains_mvt': 332041, 'starts_after_mvt': 180025, 'ends_before_mvt': 502, 'elapsed_sec': 822.3, 'mvts_per_sec': 631.07, 'rss_gib': 2.1532936096191406}

{'buckets': '114/512', 'mvts': 523507, 'assigned_mvts': 522391, 'single': 495540, 'multiple': 26851, 'physical_flights': 550919, 'max_physical_flights': 8, 'selected': 517089, 'resampled': 517089, 'rows': 290179166, 'unresolved': 6418, 'contains_mvt': 334925, 'starts_after_mvt': 181655, 'ends_before_mvt': 509, 'elapsed_sec': 827.8, 'mvts_per_sec': 632.43, 'rss_gib': 2.1532936096191406}

{'buckets': '115/512', 'mvts': 528112, 'assigned_mvts': 526990, 'single': 499891, 'multiple': 27099, 'physical_flights': 555794, 'max_physical_flights': 8, 'selected': 521641, 'resampled': 521641, 'rows': 292751200, 'unresolved': 6471, 'contains_mvt': 337906, 'starts_after_mvt': 183224, 'ends_before_mvt': 511, 'elapsed_sec': 831.5, 'mvts_per_sec': 635.15, 'rss_gib': 2.1532936096191406}

{'buckets': '116/512', 'mvts': 532687, 'assigned_mvts': 531558, 'single': 504220, 'multiple': 27338, 'physical_flights': 560612, 'max_physical_flights': 8, 'selected': 526146, 'resampled': 526146, 'rows': 295266256, 'unresolved': 6541, 'contains_mvt': 340819, 'starts_after_mvt': 184812, 'ends_before_mvt': 515, 'elapsed_sec': 836.3, 'mvts_per_sec': 636.93, 'rss_gib': 2.1532936096191406}

{'buckets': '116/512', 'mvts': 532687, 'assigned_mvts': 531558, 'single': 504220, 'multiple': 27338, 'physical_flights': 560612, 'max_physical_flights': 8, 'selected': 526146, 'resampled': 526146, 'rows': 295266256, 'unresolved': 6541, 'contains_mvt': 340819, 'starts_after_mvt': 184812, 'ends_before_mvt': 515, 'elapsed_sec': 866.3, 'mvts_per_sec': 614.87, 'rss_gib': 2.1532936096191406}

{'buckets': '117/512', 'mvts': 537235, 'assigned_mvts': 536099, 'single': 508521, 'multiple': 27578, 'physical_flights': 565406, 'max_physical_flights': 8, 'selected': 530638, 'resampled': 530638, 'rows': 297837895, 'unresolved': 6597, 'contains_mvt': 343728, 'starts_after_mvt': 186393, 'ends_before_mvt': 517, 'elapsed_sec': 872.1, 'mvts_per_sec': 616.05, 'rss_gib': 2.1532974243164062}

{'buckets': '118/512', 'mvts': 541730, 'assigned_mvts': 540582, 'single': 512745, 'multiple': 27837, 'physical_flights': 570158, 'max_physical_flights': 8, 'selected': 535065, 'resampled': 535065, 'rows': 300356943, 'unresolved': 6665, 'contains_mvt': 346603, 'starts_after_mvt': 187945, 'ends_before_mvt': 517, 'elapsed_sec': 883.4, 'mvts_per_sec': 613.26, 'rss_gib': 2.1532974243164062}

{'buckets': '119/512', 'mvts': 546317, 'assigned_mvts': 545158, 'single': 517075, 'multiple': 28083, 'physical_flights': 574999, 'max_physical_flights': 8, 'selected': 539598, 'resampled': 539598, 'rows': 302916118, 'unresolved': 6719, 'contains_mvt': 349500, 'starts_after_mvt': 189577, 'ends_before_mvt': 521, 'elapsed_sec': 890.8, 'mvts_per_sec': 613.26, 'rss_gib': 2.1532974243164062}

{'buckets': '120/512', 'mvts': 550883, 'assigned_mvts': 549715, 'single': 521397, 'multiple': 28318, 'physical_flights': 579805, 'max_physical_flights': 8, 'selected': 544114, 'resampled': 544114, 'rows': 305453944, 'unresolved': 6769, 'contains_mvt': 352414, 'starts_after_mvt': 191175, 'ends_before_mvt': 525, 'elapsed_sec': 898.4, 'mvts_per_sec': 613.18, 'rss_gib': 2.1532974243164062}

{'buckets': '121/512', 'mvts': 555468, 'assigned_mvts': 554289, 'single': 525722, 'multiple': 28567, 'physical_flights': 584635, 'max_physical_flights': 8, 'selected': 548644, 'resampled': 548644, 'rows': 308031991, 'unresolved': 6824, 'contains_mvt': 355371, 'starts_after_mvt': 192742, 'ends_before_mvt': 531, 'elapsed_sec': 922.5, 'mvts_per_sec': 602.16, 'rss_gib': 2.1532974243164062}

{'buckets': '122/512', 'mvts': 560069, 'assigned_mvts': 558883, 'single': 530115, 'multiple': 28768, 'physical_flights': 589437, 'max_physical_flights': 8, 'selected': 553207, 'resampled': 553207, 'rows': 310524726, 'unresolved': 6862, 'contains_mvt': 358285, 'starts_after_mvt': 194385, 'ends_before_mvt': 537, 'elapsed_sec': 939.4, 'mvts_per_sec': 596.19, 'rss_gib': 2.1532974243164062}

{'buckets': '123/512', 'mvts': 564532, 'assigned_mvts': 563329, 'single': 534338, 'multiple': 28991, 'physical_flights': 594127, 'max_physical_flights': 8, 'selected': 557613, 'resampled': 557613, 'rows': 312977335, 'unresolved': 6919, 'contains_mvt': 361143, 'starts_after_mvt': 195929, 'ends_before_mvt': 541, 'elapsed_sec': 944.2, 'mvts_per_sec': 597.88, 'rss_gib': 2.1532974243164062}

{'buckets': '124/512', 'mvts': 569186, 'assigned_mvts': 567968, 'single': 538760, 'multiple': 29208, 'physical_flights': 598997, 'max_physical_flights': 8, 'selected': 562209, 'resampled': 562209, 'rows': 315548459, 'unresolved': 6977, 'contains_mvt': 364114, 'starts_after_mvt': 197549, 'ends_before_mvt': 546, 'elapsed_sec': 944.7, 'mvts_per_sec': 602.53, 'rss_gib': 2.1532974243164062}

{'buckets': '125/512', 'mvts': 573622, 'assigned_mvts': 572391, 'single': 542963, 'multiple': 29428, 'physical_flights': 603653, 'max_physical_flights': 8, 'selected': 566589, 'resampled': 566589, 'rows': 317980778, 'unresolved': 7033, 'contains_mvt': 366943, 'starts_after_mvt': 199096, 'ends_before_mvt': 550, 'elapsed_sec': 946.3, 'mvts_per_sec': 606.15, 'rss_gib': 2.1532974243164062}

{'buckets': '126/512', 'mvts': 578035, 'assigned_mvts': 576795, 'single': 547158, 'multiple': 29637, 'physical_flights': 608282, 'max_physical_flights': 8, 'selected': 570944, 'resampled': 570944, 'rows': 320399041, 'unresolved': 7091, 'contains_mvt': 369731, 'starts_after_mvt': 200658, 'ends_before_mvt': 555, 'elapsed_sec': 955.3, 'mvts_per_sec': 605.09, 'rss_gib': 2.1532974243164062}

{'buckets': '127/512', 'mvts': 582571, 'assigned_mvts': 581321, 'single': 551453, 'multiple': 29868, 'physical_flights': 613049, 'max_physical_flights': 8, 'selected': 575435, 'resampled': 575435, 'rows': 322959161, 'unresolved': 7136, 'contains_mvt': 372678, 'starts_after_mvt': 202200, 'ends_before_mvt': 557, 'elapsed_sec': 968.6, 'mvts_per_sec': 601.43, 'rss_gib': 2.1532974243164062}

{'buckets': '128/512', 'mvts': 587099, 'assigned_mvts': 585840, 'single': 555735, 'multiple': 30105, 'physical_flights': 617824, 'max_physical_flights': 8, 'selected': 579915, 'resampled': 579915, 'rows': 325488839, 'unresolved': 7184, 'contains_mvt': 375585, 'starts_after_mvt': 203769, 'ends_before_mvt': 561, 'elapsed_sec': 970.7, 'mvts_per_sec': 604.83, 'rss_gib': 2.1532974243164062}

{'buckets': '129/512', 'mvts': 591642, 'assigned_mvts': 590371, 'single': 560027, 'multiple': 30344, 'physical_flights': 622605, 'max_physical_flights': 8, 'selected': 584403, 'resampled': 584403, 'rows': 328031145, 'unresolved': 7239, 'contains_mvt': 378497, 'starts_after_mvt': 205339, 'ends_before_mvt': 567, 'elapsed_sec': 971.8, 'mvts_per_sec': 608.8, 'rss_gib': 2.1532974243164062}

{'buckets': '130/512', 'mvts': 596225, 'assigned_mvts': 594942, 'single': 564360, 'multiple': 30582, 'physical_flights': 627427, 'max_physical_flights': 8, 'selected': 588926, 'resampled': 588926, 'rows': 330523668, 'unresolved': 7299, 'contains_mvt': 381411, 'starts_after_mvt': 206943, 'ends_before_mvt': 572, 'elapsed_sec': 974.5, 'mvts_per_sec': 611.82, 'rss_gib': 2.1532974243164062}

{'buckets': '131/512', 'mvts': 600848, 'assigned_mvts': 599553, 'single': 568722, 'multiple': 30831, 'physical_flights': 632296, 'max_physical_flights': 8, 'selected': 593488, 'resampled': 593488, 'rows': 333060931, 'unresolved': 7360, 'contains_mvt': 384367, 'starts_after_mvt': 208543, 'ends_before_mvt': 578, 'elapsed_sec': 981.1, 'mvts_per_sec': 612.4, 'rss_gib': 2.1532974243164062}

{'buckets': '132/512', 'mvts': 605365, 'assigned_mvts': 604057, 'single': 573002, 'multiple': 31055, 'physical_flights': 637036, 'max_physical_flights': 8, 'selected': 597949, 'resampled': 597949, 'rows': 335642959, 'unresolved': 7416, 'contains_mvt': 387308, 'starts_after_mvt': 210059, 'ends_before_mvt': 582, 'elapsed_sec': 984.7, 'mvts_per_sec': 614.75, 'rss_gib': 2.1532974243164062}

{'buckets': '133/512', 'mvts': 609849, 'assigned_mvts': 608530, 'single': 577231, 'multiple': 31299, 'physical_flights': 641775, 'max_physical_flights': 8, 'selected': 602383, 'resampled': 602383, 'rows': 338091596, 'unresolved': 7466, 'contains_mvt': 390150, 'starts_after_mvt': 211647, 'ends_before_mvt': 586, 'elapsed_sec': 988.1, 'mvts_per_sec': 617.18, 'rss_gib': 2.1532974243164062}

{'buckets': '134/512', 'mvts': 614404, 'assigned_mvts': 613076, 'single': 581514, 'multiple': 31562, 'physical_flights': 646601, 'max_physical_flights': 8, 'selected': 606885, 'resampled': 606885, 'rows': 340603874, 'unresolved': 7519, 'contains_mvt': 393041, 'starts_after_mvt': 213257, 'ends_before_mvt': 587, 'elapsed_sec': 1000.0, 'mvts_per_sec': 614.38, 'rss_gib': 2.1532974243164062}

{'buckets': '135/512', 'mvts': 618818, 'assigned_mvts': 617479, 'single': 585693, 'multiple': 31786, 'physical_flights': 651244, 'max_physical_flights': 8, 'selected': 611237, 'resampled': 611237, 'rows': 343091030, 'unresolved': 7581, 'contains_mvt': 395851, 'starts_after_mvt': 214794, 'ends_before_mvt': 592, 'elapsed_sec': 1010.9, 'mvts_per_sec': 612.16, 'rss_gib': 2.1532974243164062}

{'buckets': '136/512', 'mvts': 623469, 'assigned_mvts': 622120, 'single': 590110, 'multiple': 32010, 'physical_flights': 656116, 'max_physical_flights': 8, 'selected': 615838, 'resampled': 615838, 'rows': 345670296, 'unresolved': 7631, 'contains_mvt': 398848, 'starts_after_mvt': 216395, 'ends_before_mvt': 595, 'elapsed_sec': 1016.6, 'mvts_per_sec': 613.27, 'rss_gib': 2.1532974243164062}

{'buckets': '137/512', 'mvts': 627977, 'assigned_mvts': 626612, 'single': 594364, 'multiple': 32248, 'physical_flights': 660859, 'max_physical_flights': 8, 'selected': 620295, 'resampled': 620295, 'rows': 348241820, 'unresolved': 7682, 'contains_mvt': 401818, 'starts_after_mvt': 217877, 'ends_before_mvt': 600, 'elapsed_sec': 1019.2, 'mvts_per_sec': 616.18, 'rss_gib': 2.1532974243164062}

{'buckets': '138/512', 'mvts': 632494, 'assigned_mvts': 631122, 'single': 598639, 'multiple': 32483, 'physical_flights': 665622, 'max_physical_flights': 8, 'selected': 624760, 'resampled': 624760, 'rows': 350723909, 'unresolved': 7734, 'contains_mvt': 404697, 'starts_after_mvt': 219453, 'ends_before_mvt': 610, 'elapsed_sec': 1019.3, 'mvts_per_sec': 620.5, 'rss_gib': 2.1532974243164062}

{'buckets': '139/512', 'mvts': 637020, 'assigned_mvts': 635639, 'single': 602932, 'multiple': 32707, 'physical_flights': 670373, 'max_physical_flights': 8, 'selected': 629237, 'resampled': 629237, 'rows': 353215746, 'unresolved': 7783, 'contains_mvt': 407566, 'starts_after_mvt': 221056, 'ends_before_mvt': 615, 'elapsed_sec': 1020.5, 'mvts_per_sec': 624.2, 'rss_gib': 2.1532974243164062}

{'buckets': '140/512', 'mvts': 641675, 'assigned_mvts': 640286, 'single': 607341, 'multiple': 32945, 'physical_flights': 675275, 'max_physical_flights': 8, 'selected': 633833, 'resampled': 633833, 'rows': 355770827, 'unresolved': 7842, 'contains_mvt': 410532, 'starts_after_mvt': 222683, 'ends_before_mvt': 618, 'elapsed_sec': 1024.8, 'mvts_per_sec': 626.15, 'rss_gib': 2.1532974243164062}

{'buckets': '141/512', 'mvts': 646314, 'assigned_mvts': 644913, 'single': 611733, 'multiple': 33180, 'physical_flights': 680154, 'max_physical_flights': 8, 'selected': 638408, 'resampled': 638408, 'rows': 358246230, 'unresolved': 7906, 'contains_mvt': 413408, 'starts_after_mvt': 224379, 'ends_before_mvt': 621, 'elapsed_sec': 1028.7, 'mvts_per_sec': 628.26, 'rss_gib': 2.1532974243164062}

{'buckets': '142/512', 'mvts': 651022, 'assigned_mvts': 649613, 'single': 616158, 'multiple': 33455, 'physical_flights': 685145, 'max_physical_flights': 8, 'selected': 643063, 'resampled': 643063, 'rows': 360852112, 'unresolved': 7959, 'contains_mvt': 416417, 'starts_after_mvt': 226021, 'ends_before_mvt': 625, 'elapsed_sec': 1029.6, 'mvts_per_sec': 632.29, 'rss_gib': 2.1532974243164062}

{'buckets': '143/512', 'mvts': 655535, 'assigned_mvts': 654119, 'single': 620433, 'multiple': 33686, 'physical_flights': 689898, 'max_physical_flights': 8, 'selected': 647515, 'resampled': 647515, 'rows': 363384057, 'unresolved': 8020, 'contains_mvt': 419338, 'starts_after_mvt': 227549, 'ends_before_mvt': 628, 'elapsed_sec': 1031.7, 'mvts_per_sec': 635.42, 'rss_gib': 2.1532974243164062}

{'buckets': '144/512', 'mvts': 660094, 'assigned_mvts': 658670, 'single': 624757, 'multiple': 33913, 'physical_flights': 694685, 'max_physical_flights': 8, 'selected': 652024, 'resampled': 652024, 'rows': 365949876, 'unresolved': 8070, 'contains_mvt': 422282, 'starts_after_mvt': 229113, 'ends_before_mvt': 629, 'elapsed_sec': 1034.5, 'mvts_per_sec': 638.11, 'rss_gib': 2.1532974243164062}

{'buckets': '145/512', 'mvts': 664663, 'assigned_mvts': 663225, 'single': 629092, 'multiple': 34133, 'physical_flights': 699471, 'max_physical_flights': 8, 'selected': 656538, 'resampled': 656538, 'rows': 368383663, 'unresolved': 8125, 'contains_mvt': 425190, 'starts_after_mvt': 230715, 'ends_before_mvt': 633, 'elapsed_sec': 1044.2, 'mvts_per_sec': 636.54, 'rss_gib': 2.1532974243164062}

{'buckets': '146/512', 'mvts': 669222, 'assigned_mvts': 667777, 'single': 633427, 'multiple': 34350, 'physical_flights': 704257, 'max_physical_flights': 8, 'selected': 661029, 'resampled': 661029, 'rows': 370916240, 'unresolved': 8193, 'contains_mvt': 428092, 'starts_after_mvt': 232302, 'ends_before_mvt': 635, 'elapsed_sec': 1066.9, 'mvts_per_sec': 627.24, 'rss_gib': 2.1532974243164062}

{'buckets': '147/512', 'mvts': 673747, 'assigned_mvts': 672296, 'single': 637725, 'multiple': 34571, 'physical_flights': 709010, 'max_physical_flights': 8, 'selected': 665503, 'resampled': 665503, 'rows': 373436565, 'unresolved': 8244, 'contains_mvt': 430960, 'starts_after_mvt': 233905, 'ends_before_mvt': 638, 'elapsed_sec': 1072.7, 'mvts_per_sec': 628.08, 'rss_gib': 2.1532974243164062}

{'buckets': '148/512', 'mvts': 678416, 'assigned_mvts': 676954, 'single': 642129, 'multiple': 34825, 'physical_flights': 713936, 'max_physical_flights': 8, 'selected': 670128, 'resampled': 670128, 'rows': 376001370, 'unresolved': 8288, 'contains_mvt': 433988, 'starts_after_mvt': 235500, 'ends_before_mvt': 640, 'elapsed_sec': 1076.9, 'mvts_per_sec': 629.99, 'rss_gib': 2.1532974243164062}

{'buckets': '149/512', 'mvts': 682972, 'assigned_mvts': 681503, 'single': 646443, 'multiple': 35060, 'physical_flights': 718733, 'max_physical_flights': 8, 'selected': 674635, 'resampled': 674635, 'rows': 378580180, 'unresolved': 8337, 'contains_mvt': 436936, 'starts_after_mvt': 237053, 'ends_before_mvt': 646, 'elapsed_sec': 1106.2, 'mvts_per_sec': 617.4, 'rss_gib': 2.1532974243164062}

{'buckets': '150/512', 'mvts': 687665, 'assigned_mvts': 686189, 'single': 650923, 'multiple': 35266, 'physical_flights': 723640, 'max_physical_flights': 8, 'selected': 679267, 'resampled': 679267, 'rows': 381142489, 'unresolved': 8398, 'contains_mvt': 439897, 'starts_after_mvt': 238713, 'ends_before_mvt': 657, 'elapsed_sec': 1110.6, 'mvts_per_sec': 619.16, 'rss_gib': 2.1532974243164062}

{'buckets': '151/512', 'mvts': 692155, 'assigned_mvts': 690672, 'single': 655176, 'multiple': 35496, 'physical_flights': 728359, 'max_physical_flights': 8, 'selected': 683692, 'resampled': 683692, 'rows': 383616090, 'unresolved': 8463, 'contains_mvt': 442817, 'starts_after_mvt': 240213, 'ends_before_mvt': 662, 'elapsed_sec': 1116.9, 'mvts_per_sec': 619.72, 'rss_gib': 2.1532974243164062}

{'buckets': '152/512', 'mvts': 696721, 'assigned_mvts': 695224, 'single': 659490, 'multiple': 35734, 'physical_flights': 733166, 'max_physical_flights': 8, 'selected': 688205, 'resampled': 688205, 'rows': 386091071, 'unresolved': 8516, 'contains_mvt': 445686, 'starts_after_mvt': 241855, 'ends_before_mvt': 664, 'elapsed_sec': 1121.5, 'mvts_per_sec': 621.23, 'rss_gib': 2.1532974243164062}

{'buckets': '153/512', 'mvts': 701301, 'assigned_mvts': 699790, 'single': 663825, 'multiple': 35965, 'physical_flights': 737974, 'max_physical_flights': 8, 'selected': 692729, 'resampled': 692729, 'rows': 388594715, 'unresolved': 8572, 'contains_mvt': 448629, 'starts_after_mvt': 243434, 'ends_before_mvt': 666, 'elapsed_sec': 1131.2, 'mvts_per_sec': 619.94, 'rss_gib': 2.1532974243164062}

{'buckets': '154/512', 'mvts': 705830, 'assigned_mvts': 704303, 'single': 668089, 'multiple': 36214, 'physical_flights': 742758, 'max_physical_flights': 8, 'selected': 697202, 'resampled': 697202, 'rows': 391061980, 'unresolved': 8628, 'contains_mvt': 451500, 'starts_after_mvt': 245032, 'ends_before_mvt': 670, 'elapsed_sec': 1136.1, 'mvts_per_sec': 621.26, 'rss_gib': 2.1532974243164062}

{'buckets': '155/512', 'mvts': 710571, 'assigned_mvts': 709035, 'single': 672567, 'multiple': 36468, 'physical_flights': 747754, 'max_physical_flights': 8, 'selected': 701875, 'resampled': 701875, 'rows': 393666998, 'unresolved': 8696, 'contains_mvt': 454520, 'starts_after_mvt': 246683, 'ends_before_mvt': 672, 'elapsed_sec': 1149.0, 'mvts_per_sec': 618.42, 'rss_gib': 2.1532974243164062}

{'buckets': '156/512', 'mvts': 715215, 'assigned_mvts': 713667, 'single': 676932, 'multiple': 36735, 'physical_flights': 752665, 'max_physical_flights': 8, 'selected': 706468, 'resampled': 706468, 'rows': 396252695, 'unresolved': 8747, 'contains_mvt': 457520, 'starts_after_mvt': 248272, 'ends_before_mvt': 676, 'elapsed_sec': 1149.1, 'mvts_per_sec': 622.41, 'rss_gib': 2.1532974243164062}

{'buckets': '157/512', 'mvts': 719768, 'assigned_mvts': 718203, 'single': 681223, 'multiple': 36980, 'physical_flights': 757467, 'max_physical_flights': 8, 'selected': 710956, 'resampled': 710956, 'rows': 398811076, 'unresolved': 8812, 'contains_mvt': 460425, 'starts_after_mvt': 249849, 'ends_before_mvt': 682, 'elapsed_sec': 1163.0, 'mvts_per_sec': 618.9, 'rss_gib': 2.1532974243164062}

{'buckets': '158/512', 'mvts': 724353, 'assigned_mvts': 722780, 'single': 685550, 'multiple': 37230, 'physical_flights': 762316, 'max_physical_flights': 8, 'selected': 715492, 'resampled': 715492, 'rows': 401285541, 'unresolved': 8861, 'contains_mvt': 463325, 'starts_after_mvt': 251478, 'ends_before_mvt': 689, 'elapsed_sec': 1163.1, 'mvts_per_sec': 622.78, 'rss_gib': 2.1532974243164062}

{'buckets': '159/512', 'mvts': 728891, 'assigned_mvts': 727311, 'single': 689838, 'multiple': 37473, 'physical_flights': 767106, 'max_physical_flights': 8, 'selected': 719977, 'resampled': 719977, 'rows': 403837112, 'unresolved': 8914, 'contains_mvt': 466216, 'starts_after_mvt': 253067, 'ends_before_mvt': 694, 'elapsed_sec': 1165.4, 'mvts_per_sec': 625.42, 'rss_gib': 2.1532974243164062}

{'buckets': '160/512', 'mvts': 733414, 'assigned_mvts': 731822, 'single': 694120, 'multiple': 37702, 'physical_flights': 771860, 'max_physical_flights': 8, 'selected': 724435, 'resampled': 724435, 'rows': 406280530, 'unresolved': 8979, 'contains_mvt': 469058, 'starts_after_mvt': 254677, 'ends_before_mvt': 700, 'elapsed_sec': 1167.8, 'mvts_per_sec': 628.03, 'rss_gib': 2.1532974243164062}

{'buckets': '161/512', 'mvts': 738113, 'assigned_mvts': 736510, 'single': 698560, 'multiple': 37950, 'physical_flights': 776810, 'max_physical_flights': 8, 'selected': 729073, 'resampled': 729073, 'rows': 408829935, 'unresolved': 9040, 'contains_mvt': 472069, 'starts_after_mvt': 256300, 'ends_before_mvt': 704, 'elapsed_sec': 1180.6, 'mvts_per_sec': 625.2, 'rss_gib': 2.1532974243164062}

{'buckets': '162/512', 'mvts': 742674, 'assigned_mvts': 741061, 'single': 702873, 'multiple': 38188, 'physical_flights': 781616, 'max_physical_flights': 8, 'selected': 733574, 'resampled': 733574, 'rows': 411402941, 'unresolved': 9100, 'contains_mvt': 475010, 'starts_after_mvt': 257855, 'ends_before_mvt': 709, 'elapsed_sec': 1187.5, 'mvts_per_sec': 625.4, 'rss_gib': 2.1532974243164062}

{'buckets': '163/512', 'mvts': 747178, 'assigned_mvts': 745559, 'single': 707129, 'multiple': 38430, 'physical_flights': 786368, 'max_physical_flights': 8, 'selected': 738034, 'resampled': 738034, 'rows': 413902558, 'unresolved': 9144, 'contains_mvt': 477852, 'starts_after_mvt': 259464, 'ends_before_mvt': 718, 'elapsed_sec': 1190.2, 'mvts_per_sec': 627.79, 'rss_gib': 2.1532974243164062}

{'buckets': '164/512', 'mvts': 751703, 'assigned_mvts': 750069, 'single': 711427, 'multiple': 38642, 'physical_flights': 791104, 'max_physical_flights': 8, 'selected': 742504, 'resampled': 742504, 'rows': 416420938, 'unresolved': 9199, 'contains_mvt': 480809, 'starts_after_mvt': 260976, 'ends_before_mvt': 719, 'elapsed_sec': 1205.4, 'mvts_per_sec': 623.63, 'rss_gib': 2.1532974243164062}

{'buckets': '165/512', 'mvts': 756365, 'assigned_mvts': 754722, 'single': 715811, 'multiple': 38911, 'physical_flights': 796034, 'max_physical_flights': 8, 'selected': 747089, 'resampled': 747089, 'rows': 419013177, 'unresolved': 9276, 'contains_mvt': 483827, 'starts_after_mvt': 262540, 'ends_before_mvt': 722, 'elapsed_sec': 1206.9, 'mvts_per_sec': 626.72, 'rss_gib': 2.1532974243164062}

{'buckets': '166/512', 'mvts': 760940, 'assigned_mvts': 759292, 'single': 720150, 'multiple': 39142, 'physical_flights': 800845, 'max_physical_flights': 8, 'selected': 751615, 'resampled': 751615, 'rows': 421535290, 'unresolved': 9325, 'contains_mvt': 486781, 'starts_after_mvt': 264110, 'ends_before_mvt': 724, 'elapsed_sec': 1221.5, 'mvts_per_sec': 622.97, 'rss_gib': 2.1532974243164062}

{'buckets': '167/512', 'mvts': 765567, 'assigned_mvts': 763909, 'single': 724518, 'multiple': 39391, 'physical_flights': 805730, 'max_physical_flights': 8, 'selected': 756189, 'resampled': 756189, 'rows': 424060887, 'unresolved': 9378, 'contains_mvt': 489702, 'starts_after_mvt': 265756, 'ends_before_mvt': 731, 'elapsed_sec': 1223.0, 'mvts_per_sec': 626.0, 'rss_gib': 2.1532974243164062}

{'buckets': '168/512', 'mvts': 770229, 'assigned_mvts': 768563, 'single': 728931, 'multiple': 39632, 'physical_flights': 810633, 'max_physical_flights': 8, 'selected': 760804, 'resampled': 760804, 'rows': 426669390, 'unresolved': 9425, 'contains_mvt': 492735, 'starts_after_mvt': 267333, 'ends_before_mvt': 736, 'elapsed_sec': 1226.3, 'mvts_per_sec': 628.1, 'rss_gib': 2.1532974243164062}

{'buckets': '169/512', 'mvts': 774870, 'assigned_mvts': 773196, 'single': 733306, 'multiple': 39890, 'physical_flights': 815545, 'max_physical_flights': 8, 'selected': 765397, 'resampled': 765397, 'rows': 429262390, 'unresolved': 9473, 'contains_mvt': 495688, 'starts_after_mvt': 268971, 'ends_before_mvt': 738, 'elapsed_sec': 1229.2, 'mvts_per_sec': 630.37, 'rss_gib': 2.1532974243164062}

{'buckets': '170/512', 'mvts': 779537, 'assigned_mvts': 777857, 'single': 737718, 'multiple': 40139, 'physical_flights': 820467, 'max_physical_flights': 8, 'selected': 770003, 'resampled': 770003, 'rows': 431799943, 'unresolved': 9534, 'contains_mvt': 498682, 'starts_after_mvt': 270575, 'ends_before_mvt': 746, 'elapsed_sec': 1232.5, 'mvts_per_sec': 632.48, 'rss_gib': 2.1532974243164062}

{'buckets': '171/512', 'mvts': 784121, 'assigned_mvts': 782432, 'single': 742062, 'multiple': 40370, 'physical_flights': 825289, 'max_physical_flights': 8, 'selected': 774521, 'resampled': 774521, 'rows': 434370524, 'unresolved': 9600, 'contains_mvt': 501635, 'starts_after_mvt': 272134, 'ends_before_mvt': 752, 'elapsed_sec': 1233.5, 'mvts_per_sec': 635.71, 'rss_gib': 2.1532974243164062}

{'buckets': '172/512', 'mvts': 788709, 'assigned_mvts': 787010, 'single': 746399, 'multiple': 40611, 'physical_flights': 830118, 'max_physical_flights': 8, 'selected': 779058, 'resampled': 779058, 'rows': 436873949, 'unresolved': 9651, 'contains_mvt': 504522, 'starts_after_mvt': 273782, 'ends_before_mvt': 754, 'elapsed_sec': 1236.6, 'mvts_per_sec': 637.81, 'rss_gib': 2.1532974243164062}

{'buckets': '173/512', 'mvts': 793208, 'assigned_mvts': 791498, 'single': 750629, 'multiple': 40869, 'physical_flights': 834868, 'max_physical_flights': 8, 'selected': 783497, 'resampled': 783497, 'rows': 439301154, 'unresolved': 9711, 'contains_mvt': 507397, 'starts_after_mvt': 275341, 'ends_before_mvt': 759, 'elapsed_sec': 1247.0, 'mvts_per_sec': 636.1, 'rss_gib': 2.1532974243164062}

{'buckets': '174/512', 'mvts': 797862, 'assigned_mvts': 796145, 'single': 755053, 'multiple': 41092, 'physical_flights': 839754, 'max_physical_flights': 8, 'selected': 788109, 'resampled': 788109, 'rows': 441931690, 'unresolved': 9753, 'contains_mvt': 510391, 'starts_after_mvt': 276955, 'ends_before_mvt': 763, 'elapsed_sec': 1247.4, 'mvts_per_sec': 639.63, 'rss_gib': 2.1532974243164062}

{'buckets': '175/512', 'mvts': 802535, 'assigned_mvts': 800802, 'single': 759460, 'multiple': 41342, 'physical_flights': 844675, 'max_physical_flights': 8, 'selected': 792710, 'resampled': 792710, 'rows': 444423091, 'unresolved': 9825, 'contains_mvt': 513327, 'starts_after_mvt': 278616, 'ends_before_mvt': 767, 'elapsed_sec': 1251.3, 'mvts_per_sec': 641.38, 'rss_gib': 2.1532974243164062}

{'buckets': '176/512', 'mvts': 807070, 'assigned_mvts': 805327, 'single': 763752, 'multiple': 41575, 'physical_flights': 849447, 'max_physical_flights': 8, 'selected': 797181, 'resampled': 797181, 'rows': 446957255, 'unresolved': 9889, 'contains_mvt': 516220, 'starts_after_mvt': 280188, 'ends_before_mvt': 773, 'elapsed_sec': 1261.5, 'mvts_per_sec': 639.76, 'rss_gib': 2.1532974243164062}

{'buckets': '177/512', 'mvts': 811608, 'assigned_mvts': 809850, 'single': 768029, 'multiple': 41821, 'physical_flights': 854228, 'max_physical_flights': 8, 'selected': 801669, 'resampled': 801669, 'rows': 449482011, 'unresolved': 9939, 'contains_mvt': 519098, 'starts_after_mvt': 281792, 'ends_before_mvt': 779, 'elapsed_sec': 1262.5, 'mvts_per_sec': 642.86, 'rss_gib': 2.1532974243164062}

{'buckets': '178/512', 'mvts': 816094, 'assigned_mvts': 814330, 'single': 772272, 'multiple': 42058, 'physical_flights': 858960, 'max_physical_flights': 8, 'selected': 806097, 'resampled': 806097, 'rows': 452037287, 'unresolved': 9997, 'contains_mvt': 521968, 'starts_after_mvt': 283340, 'ends_before_mvt': 789, 'elapsed_sec': 1276.2, 'mvts_per_sec': 639.48, 'rss_gib': 2.1532974243164062}

{'buckets': '179/512', 'mvts': 820696, 'assigned_mvts': 818921, 'single': 776670, 'multiple': 42251, 'physical_flights': 863754, 'max_physical_flights': 8, 'selected': 810642, 'resampled': 810642, 'rows': 454573235, 'unresolved': 10054, 'contains_mvt': 524960, 'starts_after_mvt': 284888, 'ends_before_mvt': 794, 'elapsed_sec': 1285.9, 'mvts_per_sec': 638.23, 'rss_gib': 2.153301239013672}

{'buckets': '180/512', 'mvts': 825293, 'assigned_mvts': 823508, 'single': 781025, 'multiple': 42483, 'physical_flights': 868589, 'max_physical_flights': 8, 'selected': 815182, 'resampled': 815182, 'rows': 457103116, 'unresolved': 10111, 'contains_mvt': 527893, 'starts_after_mvt': 286491, 'ends_before_mvt': 798, 'elapsed_sec': 1286.7, 'mvts_per_sec': 641.4, 'rss_gib': 2.153301239013672}

{'buckets': '181/512', 'mvts': 829883, 'assigned_mvts': 828092, 'single': 785351, 'multiple': 42741, 'physical_flights': 873452, 'max_physical_flights': 8, 'selected': 819716, 'resampled': 819716, 'rows': 459638634, 'unresolved': 10167, 'contains_mvt': 530823, 'starts_after_mvt': 288084, 'ends_before_mvt': 809, 'elapsed_sec': 1307.4, 'mvts_per_sec': 634.78, 'rss_gib': 2.153301239013672}

{'buckets': '182/512', 'mvts': 834455, 'assigned_mvts': 832655, 'single': 789685, 'multiple': 42970, 'physical_flights': 878267, 'max_physical_flights': 8, 'selected': 824238, 'resampled': 824238, 'rows': 462175516, 'unresolved': 10217, 'contains_mvt': 533728, 'starts_after_mvt': 289696, 'ends_before_mvt': 814, 'elapsed_sec': 1312.1, 'mvts_per_sec': 635.96, 'rss_gib': 2.153301239013672}

{'buckets': '183/512', 'mvts': 839036, 'assigned_mvts': 837226, 'single': 794035, 'multiple': 43191, 'physical_flights': 883072, 'max_physical_flights': 8, 'selected': 828770, 'resampled': 828770, 'rows': 464748684, 'unresolved': 10266, 'contains_mvt': 536685, 'starts_after_mvt': 291266, 'ends_before_mvt': 819, 'elapsed_sec': 1339.4, 'mvts_per_sec': 626.41, 'rss_gib': 2.153301239013672}

{'buckets': '184/512', 'mvts': 843684, 'assigned_mvts': 841868, 'single': 798432, 'multiple': 43436, 'physical_flights': 887963, 'max_physical_flights': 8, 'selected': 833363, 'resampled': 833363, 'rows': 467302308, 'unresolved': 10321, 'contains_mvt': 539652, 'starts_after_mvt': 292888, 'ends_before_mvt': 823, 'elapsed_sec': 1348.6, 'mvts_per_sec': 625.59, 'rss_gib': 2.153301239013672}

{'buckets': '185/512', 'mvts': 848385, 'assigned_mvts': 846560, 'single': 802870, 'multiple': 43690, 'physical_flights': 892927, 'max_physical_flights': 8, 'selected': 838014, 'resampled': 838014, 'rows': 469916071, 'unresolved': 10371, 'contains_mvt': 542701, 'starts_after_mvt': 294487, 'ends_before_mvt': 826, 'elapsed_sec': 1354.7, 'mvts_per_sec': 626.27, 'rss_gib': 2.153301239013672}

{'buckets': '186/512', 'mvts': 852951, 'assigned_mvts': 851114, 'single': 807206, 'multiple': 43908, 'physical_flights': 897723, 'max_physical_flights': 8, 'selected': 842530, 'resampled': 842530, 'rows': 472461767, 'unresolved': 10421, 'contains_mvt': 545661, 'starts_after_mvt': 296037, 'ends_before_mvt': 832, 'elapsed_sec': 1355.2, 'mvts_per_sec': 629.37, 'rss_gib': 2.153301239013672}

{'buckets': '187/512', 'mvts': 857456, 'assigned_mvts': 855607, 'single': 811458, 'multiple': 44149, 'physical_flights': 902474, 'max_physical_flights': 8, 'selected': 846960, 'resampled': 846960, 'rows': 474889068, 'unresolved': 10496, 'contains_mvt': 548439, 'starts_after_mvt': 297686, 'ends_before_mvt': 835, 'elapsed_sec': 1361.2, 'mvts_per_sec': 629.93, 'rss_gib': 2.153301239013672}

{'buckets': '188/512', 'mvts': 861976, 'assigned_mvts': 860120, 'single': 815750, 'multiple': 44370, 'physical_flights': 907224, 'max_physical_flights': 8, 'selected': 851429, 'resampled': 851429, 'rows': 477377838, 'unresolved': 10547, 'contains_mvt': 551295, 'starts_after_mvt': 299293, 'ends_before_mvt': 841, 'elapsed_sec': 1365.9, 'mvts_per_sec': 631.06, 'rss_gib': 2.153301239013672}

{'buckets': '189/512', 'mvts': 866667, 'assigned_mvts': 864799, 'single': 820166, 'multiple': 44633, 'physical_flights': 912182, 'max_physical_flights': 8, 'selected': 856066, 'resampled': 856066, 'rows': 479989696, 'unresolved': 10601, 'contains_mvt': 554277, 'starts_after_mvt': 300942, 'ends_before_mvt': 847, 'elapsed_sec': 1380.7, 'mvts_per_sec': 627.7, 'rss_gib': 2.153301239013672}

{'buckets': '190/512', 'mvts': 871351, 'assigned_mvts': 869474, 'single': 824612, 'multiple': 44862, 'physical_flights': 917100, 'max_physical_flights': 8, 'selected': 860694, 'resampled': 860694, 'rows': 482570382, 'unresolved': 10657, 'contains_mvt': 557217, 'starts_after_mvt': 302625, 'ends_before_mvt': 852, 'elapsed_sec': 1383.5, 'mvts_per_sec': 629.82, 'rss_gib': 2.153301239013672}

{'buckets': '191/512', 'mvts': 876024, 'assigned_mvts': 874140, 'single': 829034, 'multiple': 45106, 'physical_flights': 922035, 'max_physical_flights': 8, 'selected': 865303, 'resampled': 865303, 'rows': 485150814, 'unresolved': 10721, 'contains_mvt': 560146, 'starts_after_mvt': 304301, 'ends_before_mvt': 856, 'elapsed_sec': 1386.2, 'mvts_per_sec': 631.97, 'rss_gib': 2.153301239013672}

{'buckets': '192/512', 'mvts': 880593, 'assigned_mvts': 878700, 'single': 833351, 'multiple': 45349, 'physical_flights': 926847, 'max_physical_flights': 8, 'selected': 869817, 'resampled': 869817, 'rows': 487684401, 'unresolved': 10776, 'contains_mvt': 563066, 'starts_after_mvt': 305887, 'ends_before_mvt': 864, 'elapsed_sec': 1390.3, 'mvts_per_sec': 633.39, 'rss_gib': 2.153301239013672}

{'buckets': '193/512', 'mvts': 885160, 'assigned_mvts': 883262, 'single': 837672, 'multiple': 45590, 'physical_flights': 931663, 'max_physical_flights': 8, 'selected': 874337, 'resampled': 874337, 'rows': 490217353, 'unresolved': 10823, 'contains_mvt': 565989, 'starts_after_mvt': 307479, 'ends_before_mvt': 869, 'elapsed_sec': 1396.3, 'mvts_per_sec': 633.93, 'rss_gib': 2.153301239013672}

{'buckets': '194/512', 'mvts': 889720, 'assigned_mvts': 887809, 'single': 841985, 'multiple': 45824, 'physical_flights': 936454, 'max_physical_flights': 8, 'selected': 878835, 'resampled': 878835, 'rows': 492715389, 'unresolved': 10885, 'contains_mvt': 568895, 'starts_after_mvt': 309069, 'ends_before_mvt': 871, 'elapsed_sec': 1405.5, 'mvts_per_sec': 633.04, 'rss_gib': 2.153301239013672}

{'buckets': '195/512', 'mvts': 894342, 'assigned_mvts': 892421, 'single': 846370, 'multiple': 46051, 'physical_flights': 941307, 'max_physical_flights': 8, 'selected': 883396, 'resampled': 883396, 'rows': 495248688, 'unresolved': 10946, 'contains_mvt': 571849, 'starts_after_mvt': 310674, 'ends_before_mvt': 873, 'elapsed_sec': 1412.8, 'mvts_per_sec': 633.03, 'rss_gib': 2.153301239013672}

{'buckets': '196/512', 'mvts': 898884, 'assigned_mvts': 896954, 'single': 850690, 'multiple': 46264, 'physical_flights': 946070, 'max_physical_flights': 8, 'selected': 887882, 'resampled': 887882, 'rows': 497818663, 'unresolved': 11002, 'contains_mvt': 574798, 'starts_after_mvt': 312207, 'ends_before_mvt': 877, 'elapsed_sec': 1414.5, 'mvts_per_sec': 635.5, 'rss_gib': 2.153301239013672}

{'buckets': '197/512', 'mvts': 903288, 'assigned_mvts': 901345, 'single': 854850, 'multiple': 46495, 'physical_flights': 950703, 'max_physical_flights': 8, 'selected': 892239, 'resampled': 892239, 'rows': 500221661, 'unresolved': 11049, 'contains_mvt': 577586, 'starts_after_mvt': 313773, 'ends_before_mvt': 880, 'elapsed_sec': 1417.8, 'mvts_per_sec': 637.11, 'rss_gib': 2.153301239013672}

{'buckets': '198/512', 'mvts': 907849, 'assigned_mvts': 905900, 'single': 859163, 'multiple': 46737, 'physical_flights': 955514, 'max_physical_flights': 8, 'selected': 896740, 'resampled': 896740, 'rows': 502727213, 'unresolved': 11109, 'contains_mvt': 580508, 'starts_after_mvt': 315349, 'ends_before_mvt': 883, 'elapsed_sec': 1418.0, 'mvts_per_sec': 640.22, 'rss_gib': 2.1533050537109375}

{'buckets': '199/512', 'mvts': 912514, 'assigned_mvts': 910553, 'single': 863572, 'multiple': 46981, 'physical_flights': 960419, 'max_physical_flights': 8, 'selected': 901350, 'resampled': 901350, 'rows': 505365044, 'unresolved': 11164, 'contains_mvt': 583513, 'starts_after_mvt': 316951, 'ends_before_mvt': 886, 'elapsed_sec': 1420.3, 'mvts_per_sec': 642.5, 'rss_gib': 2.1533050537109375}

{'buckets': '200/512', 'mvts': 917095, 'assigned_mvts': 915127, 'single': 867906, 'multiple': 47221, 'physical_flights': 965245, 'max_physical_flights': 8, 'selected': 905886, 'resampled': 905886, 'rows': 507872095, 'unresolved': 11209, 'contains_mvt': 586473, 'starts_after_mvt': 318524, 'ends_before_mvt': 889, 'elapsed_sec': 1430.3, 'mvts_per_sec': 641.21, 'rss_gib': 2.1533050537109375}

{'buckets': '201/512', 'mvts': 921733, 'assigned_mvts': 919758, 'single': 872300, 'multiple': 47458, 'physical_flights': 970128, 'max_physical_flights': 8, 'selected': 910468, 'resampled': 910468, 'rows': 510479653, 'unresolved': 11265, 'contains_mvt': 589436, 'starts_after_mvt': 320136, 'ends_before_mvt': 896, 'elapsed_sec': 1434.9, 'mvts_per_sec': 642.36, 'rss_gib': 2.1533050537109375}

{'buckets': '202/512', 'mvts': 926388, 'assigned_mvts': 924404, 'single': 876699, 'multiple': 47705, 'physical_flights': 975037, 'max_physical_flights': 8, 'selected': 915065, 'resampled': 915065, 'rows': 513039693, 'unresolved': 11323, 'contains_mvt': 592406, 'starts_after_mvt': 321759, 'ends_before_mvt': 900, 'elapsed_sec': 1438.3, 'mvts_per_sec': 644.09, 'rss_gib': 2.1533050537109375}

{'buckets': '203/512', 'mvts': 931079, 'assigned_mvts': 929087, 'single': 881155, 'multiple': 47932, 'physical_flights': 979966, 'max_physical_flights': 8, 'selected': 919698, 'resampled': 919698, 'rows': 515634199, 'unresolved': 11381, 'contains_mvt': 595377, 'starts_after_mvt': 323416, 'ends_before_mvt': 905, 'elapsed_sec': 1441.9, 'mvts_per_sec': 645.71, 'rss_gib': 2.1533050537109375}

{'buckets': '204/512', 'mvts': 935642, 'assigned_mvts': 933641, 'single': 885461, 'multiple': 48180, 'physical_flights': 984775, 'max_physical_flights': 8, 'selected': 924205, 'resampled': 924205, 'rows': 518188365, 'unresolved': 11437, 'contains_mvt': 598302, 'starts_after_mvt': 324992, 'ends_before_mvt': 911, 'elapsed_sec': 1446.0, 'mvts_per_sec': 647.06, 'rss_gib': 2.1533050537109375}

{'buckets': '205/512', 'mvts': 940292, 'assigned_mvts': 938276, 'single': 889866, 'multiple': 48410, 'physical_flights': 989654, 'max_physical_flights': 8, 'selected': 928793, 'resampled': 928793, 'rows': 520763054, 'unresolved': 11499, 'contains_mvt': 601290, 'starts_after_mvt': 326590, 'ends_before_mvt': 913, 'elapsed_sec': 1455.2, 'mvts_per_sec': 646.15, 'rss_gib': 2.1533050537109375}

{'buckets': '206/512', 'mvts': 944911, 'assigned_mvts': 942886, 'single': 894243, 'multiple': 48643, 'physical_flights': 994515, 'max_physical_flights': 8, 'selected': 933351, 'resampled': 933351, 'rows': 523353872, 'unresolved': 11560, 'contains_mvt': 604246, 'starts_after_mvt': 328188, 'ends_before_mvt': 917, 'elapsed_sec': 1458.6, 'mvts_per_sec': 647.83, 'rss_gib': 2.1533050537109375}

{'buckets': '207/512', 'mvts': 949612, 'assigned_mvts': 947573, 'single': 898695, 'multiple': 48878, 'physical_flights': 999446, 'max_physical_flights': 8, 'selected': 937983, 'resampled': 937983, 'rows': 525986184, 'unresolved': 11629, 'contains_mvt': 607277, 'starts_after_mvt': 329788, 'ends_before_mvt': 918, 'elapsed_sec': 1472.7, 'mvts_per_sec': 644.83, 'rss_gib': 2.1533050537109375}

{'buckets': '208/512', 'mvts': 954187, 'assigned_mvts': 952129, 'single': 903003, 'multiple': 49126, 'physical_flights': 1004270, 'max_physical_flights': 8, 'selected': 942496, 'resampled': 942496, 'rows': 528487654, 'unresolved': 11691, 'contains_mvt': 610172, 'starts_after_mvt': 331402, 'ends_before_mvt': 922, 'elapsed_sec': 1486.2, 'mvts_per_sec': 642.03, 'rss_gib': 2.1533050537109375}

{'buckets': '209/512', 'mvts': 958816, 'assigned_mvts': 956746, 'single': 907409, 'multiple': 49337, 'physical_flights': 1009109, 'max_physical_flights': 8, 'selected': 947076, 'resampled': 947076, 'rows': 531047140, 'unresolved': 11740, 'contains_mvt': 613166, 'starts_after_mvt': 332982, 'ends_before_mvt': 928, 'elapsed_sec': 1490.9, 'mvts_per_sec': 643.13, 'rss_gib': 2.1533050537109375}

{'buckets': '210/512', 'mvts': 963461, 'assigned_mvts': 961381, 'single': 911795, 'multiple': 49586, 'physical_flights': 1014009, 'max_physical_flights': 8, 'selected': 951659, 'resampled': 951659, 'rows': 533668858, 'unresolved': 11802, 'contains_mvt': 616176, 'starts_after_mvt': 334548, 'ends_before_mvt': 935, 'elapsed_sec': 1506.4, 'mvts_per_sec': 639.57, 'rss_gib': 2.1533050537109375}

{'buckets': '211/512', 'mvts': 967990, 'assigned_mvts': 965900, 'single': 916060, 'multiple': 49840, 'physical_flights': 1018795, 'max_physical_flights': 8, 'selected': 956132, 'resampled': 956132, 'rows': 536165883, 'unresolved': 11858, 'contains_mvt': 619092, 'starts_after_mvt': 336101, 'ends_before_mvt': 939, 'elapsed_sec': 1522.0, 'mvts_per_sec': 635.99, 'rss_gib': 2.1533050537109375}

{'buckets': '212/512', 'mvts': 972615, 'assigned_mvts': 970513, 'single': 920428, 'multiple': 50085, 'physical_flights': 1023671, 'max_physical_flights': 8, 'selected': 960704, 'resampled': 960704, 'rows': 538699378, 'unresolved': 11911, 'contains_mvt': 622063, 'starts_after_mvt': 337699, 'ends_before_mvt': 942, 'elapsed_sec': 1529.8, 'mvts_per_sec': 635.77, 'rss_gib': 2.1533050537109375}

{'buckets': '213/512', 'mvts': 977049, 'assigned_mvts': 974940, 'single': 924620, 'multiple': 50320, 'physical_flights': 1028354, 'max_physical_flights': 8, 'selected': 965088, 'resampled': 965088, 'rows': 541146970, 'unresolved': 11961, 'contains_mvt': 624939, 'starts_after_mvt': 339204, 'ends_before_mvt': 945, 'elapsed_sec': 1531.5, 'mvts_per_sec': 637.95, 'rss_gib': 2.1533050537109375}

{'buckets': '214/512', 'mvts': 981599, 'assigned_mvts': 979479, 'single': 928950, 'multiple': 50529, 'physical_flights': 1033107, 'max_physical_flights': 8, 'selected': 969582, 'resampled': 969582, 'rows': 543670328, 'unresolved': 12017, 'contains_mvt': 627832, 'starts_after_mvt': 340800, 'ends_before_mvt': 950, 'elapsed_sec': 1536.0, 'mvts_per_sec': 639.06, 'rss_gib': 2.1533050537109375}

{'buckets': '215/512', 'mvts': 986160, 'assigned_mvts': 984035, 'single': 933280, 'multiple': 50755, 'physical_flights': 1037908, 'max_physical_flights': 8, 'selected': 974100, 'resampled': 974100, 'rows': 546209931, 'unresolved': 12060, 'contains_mvt': 630761, 'starts_after_mvt': 342385, 'ends_before_mvt': 954, 'elapsed_sec': 1547.1, 'mvts_per_sec': 637.43, 'rss_gib': 2.1533050537109375}

{'buckets': '216/512', 'mvts': 990764, 'assigned_mvts': 988630, 'single': 937639, 'multiple': 50991, 'physical_flights': 1042750, 'max_physical_flights': 8, 'selected': 978652, 'resampled': 978652, 'rows': 548758351, 'unresolved': 12112, 'contains_mvt': 633682, 'starts_after_mvt': 344014, 'ends_before_mvt': 956, 'elapsed_sec': 1555.8, 'mvts_per_sec': 636.81, 'rss_gib': 2.1533050537109375}

{'buckets': '217/512', 'mvts': 995413, 'assigned_mvts': 993270, 'single': 942040, 'multiple': 51230, 'physical_flights': 1047642, 'max_physical_flights': 8, 'selected': 983236, 'resampled': 983236, 'rows': 551389236, 'unresolved': 12177, 'contains_mvt': 636655, 'starts_after_mvt': 345617, 'ends_before_mvt': 964, 'elapsed_sec': 1561.8, 'mvts_per_sec': 637.35, 'rss_gib': 2.1533050537109375}

{'buckets': '218/512', 'mvts': 999875, 'assigned_mvts': 997722, 'single': 946265, 'multiple': 51457, 'physical_flights': 1052338, 'max_physical_flights': 8, 'selected': 987643, 'resampled': 987643, 'rows': 553859700, 'unresolved': 12232, 'contains_mvt': 639496, 'starts_after_mvt': 347181, 'ends_before_mvt': 966, 'elapsed_sec': 1563.0, 'mvts_per_sec': 639.73, 'rss_gib': 2.1533050537109375}

{'buckets': '219/512', 'mvts': 1004463, 'assigned_mvts': 1002301, 'single': 950579, 'multiple': 51722, 'physical_flights': 1057201, 'max_physical_flights': 8, 'selected': 992177, 'resampled': 992177, 'rows': 556397970, 'unresolved': 12286, 'contains_mvt': 642402, 'starts_after_mvt': 348806, 'ends_before_mvt': 969, 'elapsed_sec': 1564.1, 'mvts_per_sec': 642.2, 'rss_gib': 2.1533050537109375}

{'buckets': '220/512', 'mvts': 1008985, 'assigned_mvts': 1006813, 'single': 954879, 'multiple': 51934, 'physical_flights': 1061946, 'max_physical_flights': 8, 'selected': 996650, 'resampled': 996650, 'rows': 558886209, 'unresolved': 12335, 'contains_mvt': 645315, 'starts_after_mvt': 350356, 'ends_before_mvt': 979, 'elapsed_sec': 1572.2, 'mvts_per_sec': 641.76, 'rss_gib': 2.1533050537109375}

{'buckets': '221/512', 'mvts': 1013463, 'assigned_mvts': 1011284, 'single': 959116, 'multiple': 52168, 'physical_flights': 1066673, 'max_physical_flights': 8, 'selected': 1001068, 'resampled': 1001068, 'rows': 561330449, 'unresolved': 12395, 'contains_mvt': 648190, 'starts_after_mvt': 351899, 'ends_before_mvt': 979, 'elapsed_sec': 1594.8, 'mvts_per_sec': 635.48, 'rss_gib': 2.1533050537109375}

{'buckets': '222/512', 'mvts': 1018068, 'assigned_mvts': 1015883, 'single': 963473, 'multiple': 52410, 'physical_flights': 1071523, 'max_physical_flights': 8, 'selected': 1005621, 'resampled': 1005621, 'rows': 563922728, 'unresolved': 12447, 'contains_mvt': 651171, 'starts_after_mvt': 353466, 'ends_before_mvt': 984, 'elapsed_sec': 1595.0, 'mvts_per_sec': 638.27, 'rss_gib': 2.1533050537109375}

{'buckets': '223/512', 'mvts': 1022639, 'assigned_mvts': 1020447, 'single': 967819, 'multiple': 52628, 'physical_flights': 1076321, 'max_physical_flights': 8, 'selected': 1010146, 'resampled': 1010146, 'rows': 566424929, 'unresolved': 12493, 'contains_mvt': 654081, 'starts_after_mvt': 355070, 'ends_before_mvt': 995, 'elapsed_sec': 1606.0, 'mvts_per_sec': 636.76, 'rss_gib': 2.1533050537109375}

{'buckets': '224/512', 'mvts': 1027228, 'assigned_mvts': 1025028, 'single': 972169, 'multiple': 52859, 'physical_flights': 1081145, 'max_physical_flights': 8, 'selected': 1014668, 'resampled': 1014668, 'rows': 569001101, 'unresolved': 12560, 'contains_mvt': 657088, 'starts_after_mvt': 356585, 'ends_before_mvt': 995, 'elapsed_sec': 1610.9, 'mvts_per_sec': 637.67, 'rss_gib': 2.1533050537109375}

{'buckets': '225/512', 'mvts': 1031593, 'assigned_mvts': 1029382, 'single': 976315, 'multiple': 53067, 'physical_flights': 1085714, 'max_physical_flights': 8, 'selected': 1018978, 'resampled': 1018978, 'rows': 571399342, 'unresolved': 12615, 'contains_mvt': 659890, 'starts_after_mvt': 358089, 'ends_before_mvt': 999, 'elapsed_sec': 1612.3, 'mvts_per_sec': 639.82, 'rss_gib': 2.1533050537109375}

{'buckets': '226/512', 'mvts': 1036295, 'assigned_mvts': 1034082, 'single': 980772, 'multiple': 53310, 'physical_flights': 1090676, 'max_physical_flights': 8, 'selected': 1023629, 'resampled': 1023629, 'rows': 574002019, 'unresolved': 12666, 'contains_mvt': 662906, 'starts_after_mvt': 359719, 'ends_before_mvt': 1004, 'elapsed_sec': 1613.4, 'mvts_per_sec': 642.31, 'rss_gib': 2.153308868408203}

{'buckets': '227/512', 'mvts': 1040834, 'assigned_mvts': 1038615, 'single': 985078, 'multiple': 53537, 'physical_flights': 1095450, 'max_physical_flights': 8, 'selected': 1028115, 'resampled': 1028115, 'rows': 576485196, 'unresolved': 12719, 'contains_mvt': 665762, 'starts_after_mvt': 361345, 'ends_before_mvt': 1008, 'elapsed_sec': 1624.8, 'mvts_per_sec': 640.6, 'rss_gib': 2.153308868408203}

{'buckets': '228/512', 'mvts': 1045401, 'assigned_mvts': 1043172, 'single': 989397, 'multiple': 53775, 'physical_flights': 1100260, 'max_physical_flights': 8, 'selected': 1032626, 'resampled': 1032626, 'rows': 578978326, 'unresolved': 12775, 'contains_mvt': 668663, 'starts_after_mvt': 362950, 'ends_before_mvt': 1013, 'elapsed_sec': 1628.0, 'mvts_per_sec': 642.15, 'rss_gib': 2.153308868408203}

{'buckets': '229/512', 'mvts': 1049887, 'assigned_mvts': 1047646, 'single': 993643, 'multiple': 54003, 'physical_flights': 1104975, 'max_physical_flights': 8, 'selected': 1037059, 'resampled': 1037059, 'rows': 581516791, 'unresolved': 12828, 'contains_mvt': 671591, 'starts_after_mvt': 364454, 'ends_before_mvt': 1014, 'elapsed_sec': 1630.9, 'mvts_per_sec': 643.74, 'rss_gib': 2.153308868408203}

{'buckets': '230/512', 'mvts': 1054553, 'assigned_mvts': 1052303, 'single': 998039, 'multiple': 54264, 'physical_flights': 1109906, 'max_physical_flights': 8, 'selected': 1041668, 'resampled': 1041668, 'rows': 584067396, 'unresolved': 12885, 'contains_mvt': 674593, 'starts_after_mvt': 366056, 'ends_before_mvt': 1019, 'elapsed_sec': 1634.0, 'mvts_per_sec': 645.38, 'rss_gib': 2.153308868408203}

{'buckets': '231/512', 'mvts': 1059000, 'assigned_mvts': 1056741, 'single': 1002236, 'multiple': 54505, 'physical_flights': 1114594, 'max_physical_flights': 8, 'selected': 1046067, 'resampled': 1046067, 'rows': 586558498, 'unresolved': 12933, 'contains_mvt': 677404, 'starts_after_mvt': 367640, 'ends_before_mvt': 1023, 'elapsed_sec': 1635.4, 'mvts_per_sec': 647.55, 'rss_gib': 2.153308868408203}

{'buckets': '232/512', 'mvts': 1063535, 'assigned_mvts': 1061268, 'single': 1006528, 'multiple': 54740, 'physical_flights': 1119365, 'max_physical_flights': 8, 'selected': 1050540, 'resampled': 1050540, 'rows': 589052897, 'unresolved': 12995, 'contains_mvt': 680304, 'starts_after_mvt': 369207, 'ends_before_mvt': 1029, 'elapsed_sec': 1639.6, 'mvts_per_sec': 648.65, 'rss_gib': 2.153308868408203}

{'buckets': '233/512', 'mvts': 1068205, 'assigned_mvts': 1065929, 'single': 1010910, 'multiple': 55019, 'physical_flights': 1124325, 'max_physical_flights': 8, 'selected': 1055146, 'resampled': 1055146, 'rows': 591565057, 'unresolved': 13059, 'contains_mvt': 683222, 'starts_after_mvt': 370889, 'ends_before_mvt': 1035, 'elapsed_sec': 1640.9, 'mvts_per_sec': 650.99, 'rss_gib': 2.153308868408203}

{'buckets': '234/512', 'mvts': 1072764, 'assigned_mvts': 1070479, 'single': 1015234, 'multiple': 55245, 'physical_flights': 1129112, 'max_physical_flights': 8, 'selected': 1059662, 'resampled': 1059662, 'rows': 594133615, 'unresolved': 13102, 'contains_mvt': 686218, 'starts_after_mvt': 372406, 'ends_before_mvt': 1038, 'elapsed_sec': 1650.6, 'mvts_per_sec': 649.91, 'rss_gib': 2.1533126831054688}

{'buckets': '235/512', 'mvts': 1077426, 'assigned_mvts': 1075135, 'single': 1019655, 'multiple': 55480, 'physical_flights': 1134011, 'max_physical_flights': 8, 'selected': 1064287, 'resampled': 1064287, 'rows': 596732417, 'unresolved': 13139, 'contains_mvt': 689251, 'starts_after_mvt': 373995, 'ends_before_mvt': 1041, 'elapsed_sec': 1653.1, 'mvts_per_sec': 651.75, 'rss_gib': 2.1533126831054688}

{'buckets': '236/512', 'mvts': 1082056, 'assigned_mvts': 1079754, 'single': 1024031, 'multiple': 55723, 'physical_flights': 1138889, 'max_physical_flights': 8, 'selected': 1068875, 'resampled': 1068875, 'rows': 599288616, 'unresolved': 13181, 'contains_mvt': 692229, 'starts_after_mvt': 375600, 'ends_before_mvt': 1046, 'elapsed_sec': 1668.6, 'mvts_per_sec': 648.48, 'rss_gib': 2.1533126831054688}

{'buckets': '237/512', 'mvts': 1086697, 'assigned_mvts': 1084385, 'single': 1028401, 'multiple': 55984, 'physical_flights': 1143794, 'max_physical_flights': 8, 'selected': 1073453, 'resampled': 1073453, 'rows': 601874956, 'unresolved': 13244, 'contains_mvt': 695197, 'starts_after_mvt': 377206, 'ends_before_mvt': 1050, 'elapsed_sec': 1674.7, 'mvts_per_sec': 648.88, 'rss_gib': 2.1533126831054688}

{'buckets': '238/512', 'mvts': 1091276, 'assigned_mvts': 1088955, 'single': 1032736, 'multiple': 56219, 'physical_flights': 1148616, 'max_physical_flights': 8, 'selected': 1077967, 'resampled': 1077967, 'rows': 604389230, 'unresolved': 13309, 'contains_mvt': 698088, 'starts_after_mvt': 378825, 'ends_before_mvt': 1054, 'elapsed_sec': 1683.9, 'mvts_per_sec': 648.07, 'rss_gib': 2.1533126831054688}

{'buckets': '239/512', 'mvts': 1095937, 'assigned_mvts': 1093604, 'single': 1037126, 'multiple': 56478, 'physical_flights': 1153538, 'max_physical_flights': 8, 'selected': 1082566, 'resampled': 1082566, 'rows': 606934064, 'unresolved': 13371, 'contains_mvt': 701009, 'starts_after_mvt': 380501, 'ends_before_mvt': 1056, 'elapsed_sec': 1701.1, 'mvts_per_sec': 644.26, 'rss_gib': 2.1533126831054688}

{'buckets': '240/512', 'mvts': 1100492, 'assigned_mvts': 1098152, 'single': 1041423, 'multiple': 56729, 'physical_flights': 1158352, 'max_physical_flights': 8, 'selected': 1087062, 'resampled': 1087062, 'rows': 609548504, 'unresolved': 13430, 'contains_mvt': 703918, 'starts_after_mvt': 382083, 'ends_before_mvt': 1061, 'elapsed_sec': 1724.9, 'mvts_per_sec': 638.01, 'rss_gib': 2.1533126831054688}

{'buckets': '241/512', 'mvts': 1105115, 'assigned_mvts': 1102766, 'single': 1045768, 'multiple': 56998, 'physical_flights': 1163249, 'max_physical_flights': 8, 'selected': 1091634, 'resampled': 1091634, 'rows': 612137798, 'unresolved': 13481, 'contains_mvt': 706890, 'starts_after_mvt': 383676, 'ends_before_mvt': 1068, 'elapsed_sec': 1730.3, 'mvts_per_sec': 638.68, 'rss_gib': 2.1533126831054688}

{'buckets': '242/512', 'mvts': 1109544, 'assigned_mvts': 1107187, 'single': 1049933, 'multiple': 57254, 'physical_flights': 1167936, 'max_physical_flights': 8, 'selected': 1096018, 'resampled': 1096018, 'rows': 614553809, 'unresolved': 13526, 'contains_mvt': 709708, 'starts_after_mvt': 385241, 'ends_before_mvt': 1069, 'elapsed_sec': 1730.8, 'mvts_per_sec': 641.05, 'rss_gib': 2.1533126831054688}

{'buckets': '243/512', 'mvts': 1114090, 'assigned_mvts': 1111725, 'single': 1054258, 'multiple': 57467, 'physical_flights': 1172703, 'max_physical_flights': 8, 'selected': 1100508, 'resampled': 1100508, 'rows': 617053775, 'unresolved': 13582, 'contains_mvt': 712623, 'starts_after_mvt': 386814, 'ends_before_mvt': 1071, 'elapsed_sec': 1731.5, 'mvts_per_sec': 643.41, 'rss_gib': 2.1533126831054688}

{'buckets': '244/512', 'mvts': 1118752, 'assigned_mvts': 1116375, 'single': 1058683, 'multiple': 57692, 'physical_flights': 1177589, 'max_physical_flights': 8, 'selected': 1105111, 'resampled': 1105111, 'rows': 619699346, 'unresolved': 13641, 'contains_mvt': 715625, 'starts_after_mvt': 388411, 'ends_before_mvt': 1075, 'elapsed_sec': 1737.1, 'mvts_per_sec': 644.05, 'rss_gib': 2.1533126831054688}

{'buckets': '245/512', 'mvts': 1123343, 'assigned_mvts': 1120950, 'single': 1063000, 'multiple': 57950, 'physical_flights': 1182441, 'max_physical_flights': 8, 'selected': 1109654, 'resampled': 1109654, 'rows': 622189186, 'unresolved': 13689, 'contains_mvt': 718525, 'starts_after_mvt': 390051, 'ends_before_mvt': 1078, 'elapsed_sec': 1748.1, 'mvts_per_sec': 642.62, 'rss_gib': 2.1533126831054688}

{'buckets': '246/512', 'mvts': 1127988, 'assigned_mvts': 1125587, 'single': 1067399, 'multiple': 58188, 'physical_flights': 1187329, 'max_physical_flights': 8, 'selected': 1114246, 'resampled': 1114246, 'rows': 624780995, 'unresolved': 13742, 'contains_mvt': 721483, 'starts_after_mvt': 391682, 'ends_before_mvt': 1081, 'elapsed_sec': 1759.5, 'mvts_per_sec': 641.1, 'rss_gib': 2.1533126831054688}

{'buckets': '247/512', 'mvts': 1132526, 'assigned_mvts': 1130117, 'single': 1071692, 'multiple': 58425, 'physical_flights': 1192106, 'max_physical_flights': 8, 'selected': 1118733, 'resampled': 1118733, 'rows': 627268488, 'unresolved': 13793, 'contains_mvt': 724417, 'starts_after_mvt': 393232, 'ends_before_mvt': 1084, 'elapsed_sec': 1760.9, 'mvts_per_sec': 643.14, 'rss_gib': 2.1533126831054688}

{'buckets': '248/512', 'mvts': 1137048, 'assigned_mvts': 1134627, 'single': 1075950, 'multiple': 58677, 'physical_flights': 1196883, 'max_physical_flights': 8, 'selected': 1123201, 'resampled': 1123201, 'rows': 629796119, 'unresolved': 13847, 'contains_mvt': 727279, 'starts_after_mvt': 394834, 'ends_before_mvt': 1088, 'elapsed_sec': 1761.1, 'mvts_per_sec': 645.64, 'rss_gib': 2.1533126831054688}

{'buckets': '249/512', 'mvts': 1141626, 'assigned_mvts': 1139191, 'single': 1080273, 'multiple': 58918, 'physical_flights': 1201698, 'max_physical_flights': 8, 'selected': 1127715, 'resampled': 1127715, 'rows': 632299638, 'unresolved': 13911, 'contains_mvt': 730167, 'starts_after_mvt': 396459, 'ends_before_mvt': 1089, 'elapsed_sec': 1767.2, 'mvts_per_sec': 646.03, 'rss_gib': 2.1533126831054688}

{'buckets': '250/512', 'mvts': 1146145, 'assigned_mvts': 1143701, 'single': 1084577, 'multiple': 59124, 'physical_flights': 1206422, 'max_physical_flights': 8, 'selected': 1132185, 'resampled': 1132185, 'rows': 634808697, 'unresolved': 13960, 'contains_mvt': 733085, 'starts_after_mvt': 398007, 'ends_before_mvt': 1093, 'elapsed_sec': 1777.9, 'mvts_per_sec': 644.65, 'rss_gib': 2.1533126831054688}

{'buckets': '251/512', 'mvts': 1150730, 'assigned_mvts': 1148272, 'single': 1088907, 'multiple': 59365, 'physical_flights': 1211248, 'max_physical_flights': 8, 'selected': 1136710, 'resampled': 1136710, 'rows': 637320428, 'unresolved': 14020, 'contains_mvt': 736012, 'starts_after_mvt': 399602, 'ends_before_mvt': 1096, 'elapsed_sec': 1780.5, 'mvts_per_sec': 646.29, 'rss_gib': 2.1533126831054688}

{'buckets': '252/512', 'mvts': 1155319, 'assigned_mvts': 1152856, 'single': 1093238, 'multiple': 59618, 'physical_flights': 1216101, 'max_physical_flights': 8, 'selected': 1141254, 'resampled': 1141254, 'rows': 639816428, 'unresolved': 14065, 'contains_mvt': 738917, 'starts_after_mvt': 401237, 'ends_before_mvt': 1100, 'elapsed_sec': 1781.5, 'mvts_per_sec': 648.51, 'rss_gib': 2.1533126831054688}

{'buckets': '253/512', 'mvts': 1159830, 'assigned_mvts': 1157352, 'single': 1097498, 'multiple': 59854, 'physical_flights': 1220847, 'max_physical_flights': 8, 'selected': 1145699, 'resampled': 1145699, 'rows': 642307249, 'unresolved': 14131, 'contains_mvt': 741809, 'starts_after_mvt': 402783, 'ends_before_mvt': 1107, 'elapsed_sec': 1792.2, 'mvts_per_sec': 647.15, 'rss_gib': 2.1533126831054688}

{'buckets': '254/512', 'mvts': 1164304, 'assigned_mvts': 1161817, 'single': 1101727, 'multiple': 60090, 'physical_flights': 1225572, 'max_physical_flights': 8, 'selected': 1150117, 'resampled': 1150117, 'rows': 644792198, 'unresolved': 14187, 'contains_mvt': 744667, 'starts_after_mvt': 404331, 'ends_before_mvt': 1119, 'elapsed_sec': 1803.9, 'mvts_per_sec': 645.43, 'rss_gib': 2.1533126831054688}

{'buckets': '255/512', 'mvts': 1168968, 'assigned_mvts': 1166474, 'single': 1106158, 'multiple': 60316, 'physical_flights': 1230463, 'max_physical_flights': 8, 'selected': 1154732, 'resampled': 1154732, 'rows': 647333786, 'unresolved': 14236, 'contains_mvt': 747601, 'starts_after_mvt': 406008, 'ends_before_mvt': 1123, 'elapsed_sec': 1804.8, 'mvts_per_sec': 647.72, 'rss_gib': 2.1533126831054688}

{'buckets': '256/512', 'mvts': 1173589, 'assigned_mvts': 1171084, 'single': 1110516, 'multiple': 60568, 'physical_flights': 1235339, 'max_physical_flights': 8, 'selected': 1159282, 'resampled': 1159282, 'rows': 649887994, 'unresolved': 14307, 'contains_mvt': 750587, 'starts_after_mvt': 407565, 'ends_before_mvt': 1130, 'elapsed_sec': 1804.8, 'mvts_per_sec': 650.27, 'rss_gib': 2.1533126831054688}

{'buckets': '257/512', 'mvts': 1178148, 'assigned_mvts': 1175634, 'single': 1114806, 'multiple': 60828, 'physical_flights': 1240154, 'max_physical_flights': 8, 'selected': 1163785, 'resampled': 1163785, 'rows': 652390811, 'unresolved': 14363, 'contains_mvt': 753473, 'starts_after_mvt': 409176, 'ends_before_mvt': 1136, 'elapsed_sec': 1813.3, 'mvts_per_sec': 649.73, 'rss_gib': 2.1533126831054688}

{'buckets': '258/512', 'mvts': 1182786, 'assigned_mvts': 1180262, 'single': 1119181, 'multiple': 61081, 'physical_flights': 1245054, 'max_physical_flights': 8, 'selected': 1168369, 'resampled': 1168369, 'rows': 654982836, 'unresolved': 14417, 'contains_mvt': 756497, 'starts_after_mvt': 410736, 'ends_before_mvt': 1136, 'elapsed_sec': 1814.6, 'mvts_per_sec': 651.81, 'rss_gib': 2.1533126831054688}

{'buckets': '259/512', 'mvts': 1187243, 'assigned_mvts': 1184709, 'single': 1123390, 'multiple': 61319, 'physical_flights': 1249754, 'max_physical_flights': 8, 'selected': 1172766, 'resampled': 1172766, 'rows': 657399109, 'unresolved': 14477, 'contains_mvt': 759315, 'starts_after_mvt': 412308, 'ends_before_mvt': 1143, 'elapsed_sec': 1816.5, 'mvts_per_sec': 653.59, 'rss_gib': 2.1533126831054688}

{'buckets': '260/512', 'mvts': 1191851, 'assigned_mvts': 1189304, 'single': 1127745, 'multiple': 61559, 'physical_flights': 1254601, 'max_physical_flights': 8, 'selected': 1177315, 'resampled': 1177315, 'rows': 659900566, 'unresolved': 14536, 'contains_mvt': 762242, 'starts_after_mvt': 413929, 'ends_before_mvt': 1144, 'elapsed_sec': 1821.2, 'mvts_per_sec': 654.44, 'rss_gib': 2.1533126831054688}

{'buckets': '261/512', 'mvts': 1196433, 'assigned_mvts': 1193879, 'single': 1132063, 'multiple': 61816, 'physical_flights': 1259445, 'max_physical_flights': 8, 'selected': 1181845, 'resampled': 1181845, 'rows': 662463132, 'unresolved': 14588, 'contains_mvt': 765196, 'starts_after_mvt': 415504, 'ends_before_mvt': 1145, 'elapsed_sec': 1827.9, 'mvts_per_sec': 654.53, 'rss_gib': 2.1533126831054688}

{'buckets': '262/512', 'mvts': 1201050, 'assigned_mvts': 1198480, 'single': 1136410, 'multiple': 62070, 'physical_flights': 1264316, 'max_physical_flights': 8, 'selected': 1186393, 'resampled': 1186393, 'rows': 665003854, 'unresolved': 14657, 'contains_mvt': 768154, 'starts_after_mvt': 417092, 'ends_before_mvt': 1147, 'elapsed_sec': 1838.0, 'mvts_per_sec': 653.47, 'rss_gib': 2.1533164978027344}

{'buckets': '263/512', 'mvts': 1205650, 'assigned_mvts': 1203067, 'single': 1140782, 'multiple': 62285, 'physical_flights': 1269127, 'max_physical_flights': 8, 'selected': 1190929, 'resampled': 1190929, 'rows': 667613512, 'unresolved': 14721, 'contains_mvt': 771089, 'starts_after_mvt': 418687, 'ends_before_mvt': 1153, 'elapsed_sec': 1838.7, 'mvts_per_sec': 655.69, 'rss_gib': 2.1533164978027344}

{'buckets': '264/512', 'mvts': 1210249, 'assigned_mvts': 1207659, 'single': 1145152, 'multiple': 62507, 'physical_flights': 1273954, 'max_physical_flights': 8, 'selected': 1195476, 'resampled': 1195476, 'rows': 670147118, 'unresolved': 14773, 'contains_mvt': 774020, 'starts_after_mvt': 420296, 'ends_before_mvt': 1160, 'elapsed_sec': 1856.1, 'mvts_per_sec': 652.03, 'rss_gib': 2.1533164978027344}

{'buckets': '265/512', 'mvts': 1214712, 'assigned_mvts': 1212113, 'single': 1149361, 'multiple': 62752, 'physical_flights': 1278662, 'max_physical_flights': 8, 'selected': 1199888, 'resampled': 1199888, 'rows': 672601084, 'unresolved': 14824, 'contains_mvt': 776891, 'starts_after_mvt': 421830, 'ends_before_mvt': 1167, 'elapsed_sec': 1866.0, 'mvts_per_sec': 650.97, 'rss_gib': 2.1533164978027344}

{'buckets': '266/512', 'mvts': 1219239, 'assigned_mvts': 1216629, 'single': 1153660, 'multiple': 62969, 'physical_flights': 1283410, 'max_physical_flights': 8, 'selected': 1204361, 'resampled': 1204361, 'rows': 675063705, 'unresolved': 14878, 'contains_mvt': 779766, 'starts_after_mvt': 423422, 'ends_before_mvt': 1173, 'elapsed_sec': 1876.7, 'mvts_per_sec': 649.65, 'rss_gib': 2.1533164978027344}

{'buckets': '267/512', 'mvts': 1223936, 'assigned_mvts': 1221313, 'single': 1158101, 'multiple': 63212, 'physical_flights': 1288348, 'max_physical_flights': 8, 'selected': 1209002, 'resampled': 1209002, 'rows': 677618205, 'unresolved': 14934, 'contains_mvt': 782768, 'starts_after_mvt': 425059, 'ends_before_mvt': 1175, 'elapsed_sec': 1885.9, 'mvts_per_sec': 649.01, 'rss_gib': 2.1533164978027344}

{'buckets': '268/512', 'mvts': 1228528, 'assigned_mvts': 1225899, 'single': 1162444, 'multiple': 63455, 'physical_flights': 1293189, 'max_physical_flights': 8, 'selected': 1213546, 'resampled': 1213546, 'rows': 680166166, 'unresolved': 14982, 'contains_mvt': 785725, 'starts_after_mvt': 426638, 'ends_before_mvt': 1183, 'elapsed_sec': 1886.8, 'mvts_per_sec': 651.12, 'rss_gib': 2.1533164978027344}

{'buckets': '269/512', 'mvts': 1233121, 'assigned_mvts': 1230482, 'single': 1166796, 'multiple': 63686, 'physical_flights': 1298021, 'max_physical_flights': 8, 'selected': 1218079, 'resampled': 1218079, 'rows': 682720885, 'unresolved': 15042, 'contains_mvt': 788682, 'starts_after_mvt': 428209, 'ends_before_mvt': 1188, 'elapsed_sec': 1900.4, 'mvts_per_sec': 648.88, 'rss_gib': 2.1533164978027344}

{'buckets': '270/512', 'mvts': 1237683, 'assigned_mvts': 1235031, 'single': 1171115, 'multiple': 63916, 'physical_flights': 1302821, 'max_physical_flights': 8, 'selected': 1222577, 'resampled': 1222577, 'rows': 685230698, 'unresolved': 15106, 'contains_mvt': 791599, 'starts_after_mvt': 429784, 'ends_before_mvt': 1194, 'elapsed_sec': 1906.7, 'mvts_per_sec': 649.12, 'rss_gib': 2.1533164978027344}

{'buckets': '271/512', 'mvts': 1242356, 'assigned_mvts': 1239694, 'single': 1175534, 'multiple': 64160, 'physical_flights': 1307746, 'max_physical_flights': 8, 'selected': 1227192, 'resampled': 1227192, 'rows': 687804288, 'unresolved': 15164, 'contains_mvt': 794613, 'starts_after_mvt': 431378, 'ends_before_mvt': 1201, 'elapsed_sec': 1920.5, 'mvts_per_sec': 646.9, 'rss_gib': 2.1533164978027344}

{'buckets': '272/512', 'mvts': 1247016, 'assigned_mvts': 1244346, 'single': 1179924, 'multiple': 64422, 'physical_flights': 1312681, 'max_physical_flights': 8, 'selected': 1231809, 'resampled': 1231809, 'rows': 690322413, 'unresolved': 15207, 'contains_mvt': 797558, 'starts_after_mvt': 433045, 'ends_before_mvt': 1206, 'elapsed_sec': 1928.9, 'mvts_per_sec': 646.5, 'rss_gib': 2.1533164978027344}

{'buckets': '273/512', 'mvts': 1251424, 'assigned_mvts': 1248744, 'single': 1184102, 'multiple': 64642, 'physical_flights': 1317320, 'max_physical_flights': 8, 'selected': 1236169, 'resampled': 1236169, 'rows': 692792649, 'unresolved': 15255, 'contains_mvt': 800397, 'starts_after_mvt': 434564, 'ends_before_mvt': 1208, 'elapsed_sec': 1933.1, 'mvts_per_sec': 647.38, 'rss_gib': 2.1533164978027344}

{'buckets': '274/512', 'mvts': 1255990, 'assigned_mvts': 1253299, 'single': 1188431, 'multiple': 64868, 'physical_flights': 1322114, 'max_physical_flights': 8, 'selected': 1240681, 'resampled': 1240681, 'rows': 695292900, 'unresolved': 15309, 'contains_mvt': 803361, 'starts_after_mvt': 436106, 'ends_before_mvt': 1214, 'elapsed_sec': 1938.9, 'mvts_per_sec': 647.78, 'rss_gib': 2.1533164978027344}

{'buckets': '275/512', 'mvts': 1260507, 'assigned_mvts': 1257798, 'single': 1192696, 'multiple': 65102, 'physical_flights': 1326868, 'max_physical_flights': 8, 'selected': 1245134, 'resampled': 1245134, 'rows': 697781679, 'unresolved': 15373, 'contains_mvt': 806233, 'starts_after_mvt': 437683, 'ends_before_mvt': 1218, 'elapsed_sec': 1939.1, 'mvts_per_sec': 650.05, 'rss_gib': 2.1533164978027344}

{'buckets': '276/512', 'mvts': 1265169, 'assigned_mvts': 1262450, 'single': 1197120, 'multiple': 65330, 'physical_flights': 1331767, 'max_physical_flights': 8, 'selected': 1249740, 'resampled': 1249740, 'rows': 700334608, 'unresolved': 15429, 'contains_mvt': 809206, 'starts_after_mvt': 439311, 'ends_before_mvt': 1223, 'elapsed_sec': 1962.5, 'mvts_per_sec': 644.66, 'rss_gib': 2.1533164978027344}

{'buckets': '277/512', 'mvts': 1269715, 'assigned_mvts': 1266990, 'single': 1201428, 'multiple': 65562, 'physical_flights': 1336550, 'max_physical_flights': 8, 'selected': 1254235, 'resampled': 1254235, 'rows': 702851411, 'unresolved': 15480, 'contains_mvt': 812111, 'starts_after_mvt': 440893, 'ends_before_mvt': 1231, 'elapsed_sec': 1964.6, 'mvts_per_sec': 646.3, 'rss_gib': 2.1533164978027344}

{'buckets': '278/512', 'mvts': 1274378, 'assigned_mvts': 1271646, 'single': 1205809, 'multiple': 65837, 'physical_flights': 1341497, 'max_physical_flights': 8, 'selected': 1258850, 'resampled': 1258850, 'rows': 705439070, 'unresolved': 15528, 'contains_mvt': 815073, 'starts_after_mvt': 442542, 'ends_before_mvt': 1235, 'elapsed_sec': 1965.8, 'mvts_per_sec': 648.28, 'rss_gib': 2.1533164978027344}

{'buckets': '279/512', 'mvts': 1278929, 'assigned_mvts': 1276181, 'single': 1210110, 'multiple': 66071, 'physical_flights': 1346278, 'max_physical_flights': 8, 'selected': 1263350, 'resampled': 1263350, 'rows': 707977176, 'unresolved': 15579, 'contains_mvt': 817972, 'starts_after_mvt': 444139, 'ends_before_mvt': 1239, 'elapsed_sec': 1988.4, 'mvts_per_sec': 643.19, 'rss_gib': 2.1533164978027344}

{'buckets': '280/512', 'mvts': 1283533, 'assigned_mvts': 1280777, 'single': 1214479, 'multiple': 66298, 'physical_flights': 1351120, 'max_physical_flights': 8, 'selected': 1267901, 'resampled': 1267901, 'rows': 710530096, 'unresolved': 15632, 'contains_mvt': 820919, 'starts_after_mvt': 445738, 'ends_before_mvt': 1244, 'elapsed_sec': 1988.8, 'mvts_per_sec': 645.37, 'rss_gib': 2.1533164978027344}

{'buckets': '281/512', 'mvts': 1288086, 'assigned_mvts': 1285320, 'single': 1218768, 'multiple': 66552, 'physical_flights': 1355924, 'max_physical_flights': 8, 'selected': 1272398, 'resampled': 1272398, 'rows': 713052296, 'unresolved': 15688, 'contains_mvt': 823858, 'starts_after_mvt': 447291, 'ends_before_mvt': 1249, 'elapsed_sec': 1990.0, 'mvts_per_sec': 647.27, 'rss_gib': 2.1533164978027344}

{'buckets': '282/512', 'mvts': 1292676, 'assigned_mvts': 1289901, 'single': 1223074, 'multiple': 66827, 'physical_flights': 1360794, 'max_physical_flights': 8, 'selected': 1276942, 'resampled': 1276942, 'rows': 715553904, 'unresolved': 15734, 'contains_mvt': 826795, 'starts_after_mvt': 448893, 'ends_before_mvt': 1254, 'elapsed_sec': 1991.8, 'mvts_per_sec': 648.99, 'rss_gib': 2.1533164978027344}

{'buckets': '283/512', 'mvts': 1297215, 'assigned_mvts': 1294424, 'single': 1227359, 'multiple': 67065, 'physical_flights': 1365571, 'max_physical_flights': 8, 'selected': 1281408, 'resampled': 1281408, 'rows': 718066189, 'unresolved': 15807, 'contains_mvt': 829714, 'starts_after_mvt': 450435, 'ends_before_mvt': 1259, 'elapsed_sec': 1996.3, 'mvts_per_sec': 649.82, 'rss_gib': 2.1533164978027344}

{'buckets': '284/512', 'mvts': 1301739, 'assigned_mvts': 1298937, 'single': 1231638, 'multiple': 67299, 'physical_flights': 1370340, 'max_physical_flights': 8, 'selected': 1285870, 'resampled': 1285870, 'rows': 720536896, 'unresolved': 15869, 'contains_mvt': 832606, 'starts_after_mvt': 452000, 'ends_before_mvt': 1264, 'elapsed_sec': 1999.4, 'mvts_per_sec': 651.05, 'rss_gib': 2.1533164978027344}

{'buckets': '285/512', 'mvts': 1306325, 'assigned_mvts': 1303514, 'single': 1235977, 'multiple': 67537, 'physical_flights': 1375171, 'max_physical_flights': 8, 'selected': 1290403, 'resampled': 1290403, 'rows': 723081669, 'unresolved': 15922, 'contains_mvt': 835571, 'starts_after_mvt': 453565, 'ends_before_mvt': 1267, 'elapsed_sec': 2011.5, 'mvts_per_sec': 649.44, 'rss_gib': 2.1533164978027344}

{'buckets': '286/512', 'mvts': 1310904, 'assigned_mvts': 1308077, 'single': 1240286, 'multiple': 67791, 'physical_flights': 1379994, 'max_physical_flights': 8, 'selected': 1294924, 'resampled': 1294924, 'rows': 725550764, 'unresolved': 15980, 'contains_mvt': 838435, 'starts_after_mvt': 455215, 'ends_before_mvt': 1274, 'elapsed_sec': 2013.7, 'mvts_per_sec': 651.01, 'rss_gib': 2.1533164978027344}

{'buckets': '287/512', 'mvts': 1315561, 'assigned_mvts': 1312728, 'single': 1244686, 'multiple': 68042, 'physical_flights': 1384908, 'max_physical_flights': 8, 'selected': 1299530, 'resampled': 1299530, 'rows': 728094056, 'unresolved': 16031, 'contains_mvt': 841369, 'starts_after_mvt': 456877, 'ends_before_mvt': 1284, 'elapsed_sec': 2019.3, 'mvts_per_sec': 651.5, 'rss_gib': 2.1533164978027344}

{'buckets': '288/512', 'mvts': 1320110, 'assigned_mvts': 1317266, 'single': 1248978, 'multiple': 68288, 'physical_flights': 1389705, 'max_physical_flights': 8, 'selected': 1304030, 'resampled': 1304030, 'rows': 730620049, 'unresolved': 16080, 'contains_mvt': 844250, 'starts_after_mvt': 458493, 'ends_before_mvt': 1287, 'elapsed_sec': 2021.1, 'mvts_per_sec': 653.15, 'rss_gib': 2.1533164978027344}

{'buckets': '289/512', 'mvts': 1324924, 'assigned_mvts': 1322066, 'single': 1253561, 'multiple': 68505, 'physical_flights': 1394732, 'max_physical_flights': 8, 'selected': 1308790, 'resampled': 1308790, 'rows': 733269627, 'unresolved': 16134, 'contains_mvt': 847320, 'starts_after_mvt': 460176, 'ends_before_mvt': 1294, 'elapsed_sec': 2023.9, 'mvts_per_sec': 654.65, 'rss_gib': 2.1533164978027344}

{'buckets': '290/512', 'mvts': 1329476, 'assigned_mvts': 1326606, 'single': 1257861, 'multiple': 68745, 'physical_flights': 1399528, 'max_physical_flights': 8, 'selected': 1313286, 'resampled': 1313286, 'rows': 735802079, 'unresolved': 16190, 'contains_mvt': 850243, 'starts_after_mvt': 461748, 'ends_before_mvt': 1295, 'elapsed_sec': 2024.2, 'mvts_per_sec': 656.8, 'rss_gib': 2.1533164978027344}

{'buckets': '291/512', 'mvts': 1334190, 'assigned_mvts': 1331305, 'single': 1262320, 'multiple': 68985, 'physical_flights': 1404476, 'max_physical_flights': 8, 'selected': 1317946, 'resampled': 1317946, 'rows': 738456776, 'unresolved': 16244, 'contains_mvt': 853275, 'starts_after_mvt': 463372, 'ends_before_mvt': 1299, 'elapsed_sec': 2029.4, 'mvts_per_sec': 657.42, 'rss_gib': 2.1533164978027344}

{'buckets': '292/512', 'mvts': 1338878, 'assigned_mvts': 1335988, 'single': 1266763, 'multiple': 69225, 'physical_flights': 1409415, 'max_physical_flights': 8, 'selected': 1322572, 'resampled': 1322572, 'rows': 741029762, 'unresolved': 16306, 'contains_mvt': 856258, 'starts_after_mvt': 465010, 'ends_before_mvt': 1304, 'elapsed_sec': 2038.6, 'mvts_per_sec': 656.76, 'rss_gib': 2.1533164978027344}

{'buckets': '293/512', 'mvts': 1343462, 'assigned_mvts': 1340561, 'single': 1271115, 'multiple': 69446, 'physical_flights': 1414224, 'max_physical_flights': 8, 'selected': 1327108, 'resampled': 1327108, 'rows': 743573771, 'unresolved': 16354, 'contains_mvt': 859207, 'starts_after_mvt': 466589, 'ends_before_mvt': 1312, 'elapsed_sec': 2053.2, 'mvts_per_sec': 654.33, 'rss_gib': 2.1533164978027344}

{'buckets': '294/512', 'mvts': 1348057, 'assigned_mvts': 1345142, 'single': 1275468, 'multiple': 69674, 'physical_flights': 1419048, 'max_physical_flights': 8, 'selected': 1331633, 'resampled': 1331633, 'rows': 746124933, 'unresolved': 16424, 'contains_mvt': 862150, 'starts_after_mvt': 468168, 'ends_before_mvt': 1315, 'elapsed_sec': 2057.5, 'mvts_per_sec': 655.19, 'rss_gib': 2.1533164978027344}

{'buckets': '295/512', 'mvts': 1352671, 'assigned_mvts': 1349750, 'single': 1279842, 'multiple': 69908, 'physical_flights': 1423901, 'max_physical_flights': 8, 'selected': 1336189, 'resampled': 1336189, 'rows': 748695890, 'unresolved': 16482, 'contains_mvt': 865087, 'starts_after_mvt': 469784, 'ends_before_mvt': 1318, 'elapsed_sec': 2066.8, 'mvts_per_sec': 654.47, 'rss_gib': 2.1533164978027344}

{'buckets': '296/512', 'mvts': 1357346, 'assigned_mvts': 1354414, 'single': 1284260, 'multiple': 70154, 'physical_flights': 1428829, 'max_physical_flights': 8, 'selected': 1340794, 'resampled': 1340794, 'rows': 751268371, 'unresolved': 16552, 'contains_mvt': 868024, 'starts_after_mvt': 471448, 'ends_before_mvt': 1322, 'elapsed_sec': 2073.5, 'mvts_per_sec': 654.61, 'rss_gib': 2.1533164978027344}

{'buckets': '297/512', 'mvts': 1361991, 'assigned_mvts': 1359050, 'single': 1288659, 'multiple': 70391, 'physical_flights': 1433718, 'max_physical_flights': 8, 'selected': 1345371, 'resampled': 1345371, 'rows': 753817785, 'unresolved': 16620, 'contains_mvt': 870960, 'starts_after_mvt': 473081, 'ends_before_mvt': 1330, 'elapsed_sec': 2082.0, 'mvts_per_sec': 654.16, 'rss_gib': 2.1533164978027344}

{'buckets': '298/512', 'mvts': 1366530, 'assigned_mvts': 1363578, 'single': 1292959, 'multiple': 70619, 'physical_flights': 1438486, 'max_physical_flights': 8, 'selected': 1349865, 'resampled': 1349865, 'rows': 756244778, 'unresolved': 16665, 'contains_mvt': 873814, 'starts_after_mvt': 474714, 'ends_before_mvt': 1337, 'elapsed_sec': 2088.5, 'mvts_per_sec': 654.31, 'rss_gib': 2.1533164978027344}

{'buckets': '299/512', 'mvts': 1371115, 'assigned_mvts': 1368153, 'single': 1297288, 'multiple': 70865, 'physical_flights': 1443326, 'max_physical_flights': 8, 'selected': 1354391, 'resampled': 1354391, 'rows': 758815185, 'unresolved': 16724, 'contains_mvt': 876749, 'starts_after_mvt': 476301, 'ends_before_mvt': 1341, 'elapsed_sec': 2108.4, 'mvts_per_sec': 650.31, 'rss_gib': 2.1533164978027344}

{'buckets': '300/512', 'mvts': 1375656, 'assigned_mvts': 1372685, 'single': 1301586, 'multiple': 71099, 'physical_flights': 1448105, 'max_physical_flights': 8, 'selected': 1358884, 'resampled': 1358884, 'rows': 761372794, 'unresolved': 16772, 'contains_mvt': 879665, 'starts_after_mvt': 477876, 'ends_before_mvt': 1343, 'elapsed_sec': 2110.6, 'mvts_per_sec': 651.8, 'rss_gib': 2.1533164978027344}

{'buckets': '301/512', 'mvts': 1380216, 'assigned_mvts': 1377240, 'single': 1305912, 'multiple': 71328, 'physical_flights': 1452903, 'max_physical_flights': 8, 'selected': 1363392, 'resampled': 1363392, 'rows': 763929744, 'unresolved': 16824, 'contains_mvt': 882581, 'starts_after_mvt': 479468, 'ends_before_mvt': 1343, 'elapsed_sec': 2117.9, 'mvts_per_sec': 651.69, 'rss_gib': 2.1533164978027344}

{'buckets': '302/512', 'mvts': 1384714, 'assigned_mvts': 1381729, 'single': 1310168, 'multiple': 71561, 'physical_flights': 1457633, 'max_physical_flights': 8, 'selected': 1367832, 'resampled': 1367832, 'rows': 766491852, 'unresolved': 16882, 'contains_mvt': 885470, 'starts_after_mvt': 481013, 'ends_before_mvt': 1349, 'elapsed_sec': 2119.9, 'mvts_per_sec': 653.21, 'rss_gib': 2.1533164978027344}

{'buckets': '303/512', 'mvts': 1389289, 'assigned_mvts': 1386295, 'single': 1314473, 'multiple': 71822, 'physical_flights': 1462478, 'max_physical_flights': 8, 'selected': 1372341, 'resampled': 1372341, 'rows': 769034410, 'unresolved': 16948, 'contains_mvt': 888363, 'starts_after_mvt': 482623, 'ends_before_mvt': 1355, 'elapsed_sec': 2120.2, 'mvts_per_sec': 655.26, 'rss_gib': 2.1533164978027344}

{'buckets': '304/512', 'mvts': 1393824, 'assigned_mvts': 1390820, 'single': 1318760, 'multiple': 72060, 'physical_flights': 1467257, 'max_physical_flights': 8, 'selected': 1376816, 'resampled': 1376816, 'rows': 771525256, 'unresolved': 17008, 'contains_mvt': 891267, 'starts_after_mvt': 484189, 'ends_before_mvt': 1360, 'elapsed_sec': 2128.8, 'mvts_per_sec': 654.74, 'rss_gib': 2.1533164978027344}

{'buckets': '305/512', 'mvts': 1398379, 'assigned_mvts': 1395365, 'single': 1323058, 'multiple': 72307, 'physical_flights': 1472065, 'max_physical_flights': 8, 'selected': 1381320, 'resampled': 1381320, 'rows': 774020741, 'unresolved': 17059, 'contains_mvt': 894170, 'starts_after_mvt': 485783, 'ends_before_mvt': 1367, 'elapsed_sec': 2140.7, 'mvts_per_sec': 653.25, 'rss_gib': 2.1533164978027344}

{'buckets': '306/512', 'mvts': 1402897, 'assigned_mvts': 1399879, 'single': 1327344, 'multiple': 72535, 'physical_flights': 1476816, 'max_physical_flights': 8, 'selected': 1385793, 'resampled': 1385793, 'rows': 776614926, 'unresolved': 17104, 'contains_mvt': 897078, 'starts_after_mvt': 487344, 'ends_before_mvt': 1371, 'elapsed_sec': 2149.9, 'mvts_per_sec': 652.54, 'rss_gib': 2.1533164978027344}

{'buckets': '307/512', 'mvts': 1407346, 'assigned_mvts': 1404318, 'single': 1331561, 'multiple': 72757, 'physical_flights': 1481498, 'max_physical_flights': 8, 'selected': 1390196, 'resampled': 1390196, 'rows': 779061049, 'unresolved': 17150, 'contains_mvt': 899918, 'starts_after_mvt': 488902, 'ends_before_mvt': 1376, 'elapsed_sec': 2161.3, 'mvts_per_sec': 651.15, 'rss_gib': 2.1533164978027344}

{'buckets': '308/512', 'mvts': 1411939, 'assigned_mvts': 1408904, 'single': 1335923, 'multiple': 72981, 'physical_flights': 1486321, 'max_physical_flights': 8, 'selected': 1394736, 'resampled': 1394736, 'rows': 781574421, 'unresolved': 17203, 'contains_mvt': 902895, 'starts_after_mvt': 490462, 'ends_before_mvt': 1379, 'elapsed_sec': 2162.5, 'mvts_per_sec': 652.91, 'rss_gib': 2.1533164978027344}

{'buckets': '309/512', 'mvts': 1416495, 'assigned_mvts': 1413446, 'single': 1340222, 'multiple': 73224, 'physical_flights': 1491116, 'max_physical_flights': 8, 'selected': 1399225, 'resampled': 1399225, 'rows': 784106393, 'unresolved': 17270, 'contains_mvt': 905773, 'starts_after_mvt': 492066, 'ends_before_mvt': 1386, 'elapsed_sec': 2163.5, 'mvts_per_sec': 654.71, 'rss_gib': 2.1533164978027344}

{'buckets': '310/512', 'mvts': 1421091, 'assigned_mvts': 1418036, 'single': 1344586, 'multiple': 73450, 'physical_flights': 1495943, 'max_physical_flights': 8, 'selected': 1403773, 'resampled': 1403773, 'rows': 786592050, 'unresolved': 17318, 'contains_mvt': 908697, 'starts_after_mvt': 493688, 'ends_before_mvt': 1388, 'elapsed_sec': 2164.3, 'mvts_per_sec': 656.61, 'rss_gib': 2.1533164978027344}

{'buckets': '310/512', 'mvts': 1421091, 'assigned_mvts': 1418036, 'single': 1344586, 'multiple': 73450, 'physical_flights': 1495943, 'max_physical_flights': 8, 'selected': 1403773, 'resampled': 1403773, 'rows': 786592050, 'unresolved': 17318, 'contains_mvt': 908697, 'starts_after_mvt': 493688, 'ends_before_mvt': 1388, 'elapsed_sec': 2194.3, 'mvts_per_sec': 647.63, 'rss_gib': 2.1533164978027344}

{'buckets': '311/512', 'mvts': 1425733, 'assigned_mvts': 1422670, 'single': 1348982, 'multiple': 73688, 'physical_flights': 1500830, 'max_physical_flights': 8, 'selected': 1408367, 'resampled': 1408367, 'rows': 789190622, 'unresolved': 17366, 'contains_mvt': 911737, 'starts_after_mvt': 495240, 'ends_before_mvt': 1390, 'elapsed_sec': 2200.5, 'mvts_per_sec': 647.92, 'rss_gib': 2.1533164978027344}

{'buckets': '312/512', 'mvts': 1430296, 'assigned_mvts': 1427223, 'single': 1353283, 'multiple': 73940, 'physical_flights': 1505652, 'max_physical_flights': 8, 'selected': 1412880, 'resampled': 1412880, 'rows': 791690929, 'unresolved': 17416, 'contains_mvt': 914602, 'starts_after_mvt': 496885, 'ends_before_mvt': 1393, 'elapsed_sec': 2203.4, 'mvts_per_sec': 649.13, 'rss_gib': 2.1533164978027344}

{'buckets': '313/512', 'mvts': 1434831, 'assigned_mvts': 1431753, 'single': 1357584, 'multiple': 74169, 'physical_flights': 1510427, 'max_physical_flights': 8, 'selected': 1417367, 'resampled': 1417367, 'rows': 794211582, 'unresolved': 17464, 'contains_mvt': 917442, 'starts_after_mvt': 498529, 'ends_before_mvt': 1396, 'elapsed_sec': 2203.7, 'mvts_per_sec': 651.09, 'rss_gib': 2.1533164978027344}

{'buckets': '314/512', 'mvts': 1439384, 'assigned_mvts': 1436294, 'single': 1361874, 'multiple': 74420, 'physical_flights': 1515232, 'max_physical_flights': 8, 'selected': 1421859, 'resampled': 1421859, 'rows': 796706013, 'unresolved': 17525, 'contains_mvt': 920358, 'starts_after_mvt': 500102, 'ends_before_mvt': 1399, 'elapsed_sec': 2207.9, 'mvts_per_sec': 651.93, 'rss_gib': 2.1533164978027344}

{'buckets': '315/512', 'mvts': 1443892, 'assigned_mvts': 1440798, 'single': 1366153, 'multiple': 74645, 'physical_flights': 1519979, 'max_physical_flights': 8, 'selected': 1426318, 'resampled': 1426318, 'rows': 799204505, 'unresolved': 17574, 'contains_mvt': 923282, 'starts_after_mvt': 501636, 'ends_before_mvt': 1400, 'elapsed_sec': 2209.2, 'mvts_per_sec': 653.58, 'rss_gib': 2.1533164978027344}

{'buckets': '316/512', 'mvts': 1448458, 'assigned_mvts': 1445356, 'single': 1370493, 'multiple': 74863, 'physical_flights': 1524766, 'max_physical_flights': 8, 'selected': 1430831, 'resampled': 1430831, 'rows': 801786785, 'unresolved': 17627, 'contains_mvt': 926248, 'starts_after_mvt': 503178, 'ends_before_mvt': 1405, 'elapsed_sec': 2214.8, 'mvts_per_sec': 653.98, 'rss_gib': 2.1533164978027344}

{'buckets': '317/512', 'mvts': 1452938, 'assigned_mvts': 1449825, 'single': 1374740, 'multiple': 75085, 'physical_flights': 1529468, 'max_physical_flights': 8, 'selected': 1435256, 'resampled': 1435256, 'rows': 804294300, 'unresolved': 17682, 'contains_mvt': 929128, 'starts_after_mvt': 504721, 'ends_before_mvt': 1407, 'elapsed_sec': 2220.0, 'mvts_per_sec': 654.48, 'rss_gib': 2.1533164978027344}

{'buckets': '318/512', 'mvts': 1457540, 'assigned_mvts': 1454420, 'single': 1379111, 'multiple': 75309, 'physical_flights': 1534296, 'max_physical_flights': 8, 'selected': 1439807, 'resampled': 1439807, 'rows': 806786232, 'unresolved': 17733, 'contains_mvt': 932068, 'starts_after_mvt': 506329, 'ends_before_mvt': 1410, 'elapsed_sec': 2222.5, 'mvts_per_sec': 655.82, 'rss_gib': 2.1533164978027344}

{'buckets': '319/512', 'mvts': 1462216, 'assigned_mvts': 1459086, 'single': 1383510, 'multiple': 75576, 'physical_flights': 1539246, 'max_physical_flights': 8, 'selected': 1444435, 'resampled': 1444435, 'rows': 809380767, 'unresolved': 17781, 'contains_mvt': 935085, 'starts_after_mvt': 507935, 'ends_before_mvt': 1415, 'elapsed_sec': 2234.0, 'mvts_per_sec': 654.54, 'rss_gib': 2.1533164978027344}

{'buckets': '320/512', 'mvts': 1466886, 'assigned_mvts': 1463746, 'single': 1387914, 'multiple': 75832, 'physical_flights': 1544178, 'max_physical_flights': 8, 'selected': 1449045, 'resampled': 1449045, 'rows': 811957958, 'unresolved': 17841, 'contains_mvt': 938011, 'starts_after_mvt': 509611, 'ends_before_mvt': 1423, 'elapsed_sec': 2234.5, 'mvts_per_sec': 656.48, 'rss_gib': 2.1533164978027344}

{'buckets': '321/512', 'mvts': 1471437, 'assigned_mvts': 1468292, 'single': 1392228, 'multiple': 76064, 'physical_flights': 1548967, 'max_physical_flights': 8, 'selected': 1453524, 'resampled': 1453524, 'rows': 814452799, 'unresolved': 17913, 'contains_mvt': 940916, 'starts_after_mvt': 511179, 'ends_before_mvt': 1429, 'elapsed_sec': 2235.0, 'mvts_per_sec': 658.38, 'rss_gib': 2.1533164978027344}

{'buckets': '322/512', 'mvts': 1475999, 'assigned_mvts': 1472843, 'single': 1396528, 'multiple': 76315, 'physical_flights': 1553785, 'max_physical_flights': 8, 'selected': 1458033, 'resampled': 1458033, 'rows': 816969166, 'unresolved': 17966, 'contains_mvt': 943832, 'starts_after_mvt': 512771, 'ends_before_mvt': 1430, 'elapsed_sec': 2249.0, 'mvts_per_sec': 656.3, 'rss_gib': 2.1533164978027344}

{'buckets': '323/512', 'mvts': 1480521, 'assigned_mvts': 1477358, 'single': 1400810, 'multiple': 76548, 'physical_flights': 1558543, 'max_physical_flights': 8, 'selected': 1462496, 'resampled': 1462496, 'rows': 819498109, 'unresolved': 18025, 'contains_mvt': 946722, 'starts_after_mvt': 514339, 'ends_before_mvt': 1435, 'elapsed_sec': 2257.4, 'mvts_per_sec': 655.85, 'rss_gib': 2.1533164978027344}

{'buckets': '324/512', 'mvts': 1485241, 'assigned_mvts': 1482071, 'single': 1405286, 'multiple': 76785, 'physical_flights': 1563515, 'max_physical_flights': 8, 'selected': 1467163, 'resampled': 1467163, 'rows': 822141085, 'unresolved': 18078, 'contains_mvt': 949725, 'starts_after_mvt': 515998, 'ends_before_mvt': 1440, 'elapsed_sec': 2262.3, 'mvts_per_sec': 656.5, 'rss_gib': 2.1533164978027344}

{'buckets': '325/512', 'mvts': 1489869, 'assigned_mvts': 1486688, 'single': 1409687, 'multiple': 77001, 'physical_flights': 1568380, 'max_physical_flights': 8, 'selected': 1471742, 'resampled': 1471742, 'rows': 824683812, 'unresolved': 18127, 'contains_mvt': 952701, 'starts_after_mvt': 517596, 'ends_before_mvt': 1445, 'elapsed_sec': 2282.6, 'mvts_per_sec': 652.72, 'rss_gib': 2.1533203125}

{'buckets': '326/512', 'mvts': 1494496, 'assigned_mvts': 1491307, 'single': 1414085, 'multiple': 77222, 'physical_flights': 1573233, 'max_physical_flights': 8, 'selected': 1476309, 'resampled': 1476309, 'rows': 827307041, 'unresolved': 18187, 'contains_mvt': 955679, 'starts_after_mvt': 519179, 'ends_before_mvt': 1451, 'elapsed_sec': 2283.9, 'mvts_per_sec': 654.35, 'rss_gib': 2.1533203125}

{'buckets': '327/512', 'mvts': 1499049, 'assigned_mvts': 1495846, 'single': 1418375, 'multiple': 77471, 'physical_flights': 1578048, 'max_physical_flights': 8, 'selected': 1480804, 'resampled': 1480804, 'rows': 829801990, 'unresolved': 18245, 'contains_mvt': 958554, 'starts_after_mvt': 520798, 'ends_before_mvt': 1452, 'elapsed_sec': 2291.6, 'mvts_per_sec': 654.14, 'rss_gib': 2.1533203125}

{'buckets': '328/512', 'mvts': 1503720, 'assigned_mvts': 1500504, 'single': 1422769, 'multiple': 77735, 'physical_flights': 1582985, 'max_physical_flights': 8, 'selected': 1485411, 'resampled': 1485411, 'rows': 832442481, 'unresolved': 18309, 'contains_mvt': 961556, 'starts_after_mvt': 522399, 'ends_before_mvt': 1456, 'elapsed_sec': 2298.3, 'mvts_per_sec': 654.28, 'rss_gib': 2.1533203125}

{'buckets': '329/512', 'mvts': 1508146, 'assigned_mvts': 1504919, 'single': 1426934, 'multiple': 77985, 'physical_flights': 1587669, 'max_physical_flights': 8, 'selected': 1489779, 'resampled': 1489779, 'rows': 834878046, 'unresolved': 18367, 'contains_mvt': 964325, 'starts_after_mvt': 523991, 'ends_before_mvt': 1463, 'elapsed_sec': 2298.5, 'mvts_per_sec': 656.14, 'rss_gib': 2.1533203125}

{'buckets': '330/512', 'mvts': 1512740, 'assigned_mvts': 1509504, 'single': 1431287, 'multiple': 78217, 'physical_flights': 1592505, 'max_physical_flights': 8, 'selected': 1494325, 'resampled': 1494325, 'rows': 837475602, 'unresolved': 18415, 'contains_mvt': 967299, 'starts_after_mvt': 525557, 'ends_before_mvt': 1469, 'elapsed_sec': 2309.0, 'mvts_per_sec': 655.15, 'rss_gib': 2.1533203125}

{'buckets': '331/512', 'mvts': 1517268, 'assigned_mvts': 1514024, 'single': 1435540, 'multiple': 78484, 'physical_flights': 1597304, 'max_physical_flights': 8, 'selected': 1498791, 'resampled': 1498791, 'rows': 839994820, 'unresolved': 18477, 'contains_mvt': 970211, 'starts_after_mvt': 527104, 'ends_before_mvt': 1476, 'elapsed_sec': 2313.0, 'mvts_per_sec': 655.98, 'rss_gib': 2.1533203125}

{'buckets': '332/512', 'mvts': 1521912, 'assigned_mvts': 1518659, 'single': 1439950, 'multiple': 78709, 'physical_flights': 1602170, 'max_physical_flights': 8, 'selected': 1503369, 'resampled': 1503369, 'rows': 842494983, 'unresolved': 18543, 'contains_mvt': 973127, 'starts_after_mvt': 528759, 'ends_before_mvt': 1483, 'elapsed_sec': 2318.3, 'mvts_per_sec': 656.47, 'rss_gib': 2.1533203125}

{'buckets': '333/512', 'mvts': 1526435, 'assigned_mvts': 1523171, 'single': 1444221, 'multiple': 78950, 'physical_flights': 1606935, 'max_physical_flights': 8, 'selected': 1507833, 'resampled': 1507833, 'rows': 845050027, 'unresolved': 18602, 'contains_mvt': 976062, 'starts_after_mvt': 530281, 'ends_before_mvt': 1490, 'elapsed_sec': 2319.5, 'mvts_per_sec': 658.08, 'rss_gib': 2.1533203125}

{'buckets': '334/512', 'mvts': 1530952, 'assigned_mvts': 1527679, 'single': 1448475, 'multiple': 79204, 'physical_flights': 1611718, 'max_physical_flights': 8, 'selected': 1512287, 'resampled': 1512287, 'rows': 847496797, 'unresolved': 18665, 'contains_mvt': 978901, 'starts_after_mvt': 531889, 'ends_before_mvt': 1497, 'elapsed_sec': 2320.5, 'mvts_per_sec': 659.75, 'rss_gib': 2.1533203125}

{'buckets': '335/512', 'mvts': 1535553, 'assigned_mvts': 1532267, 'single': 1452828, 'multiple': 79439, 'physical_flights': 1616554, 'max_physical_flights': 8, 'selected': 1516837, 'resampled': 1516837, 'rows': 850080474, 'unresolved': 18716, 'contains_mvt': 981857, 'starts_after_mvt': 533482, 'ends_before_mvt': 1498, 'elapsed_sec': 2320.6, 'mvts_per_sec': 661.7, 'rss_gib': 2.1533203125}

{'buckets': '336/512', 'mvts': 1540140, 'assigned_mvts': 1536841, 'single': 1457190, 'multiple': 79651, 'physical_flights': 1621350, 'max_physical_flights': 8, 'selected': 1521359, 'resampled': 1521359, 'rows': 852564943, 'unresolved': 18781, 'contains_mvt': 984764, 'starts_after_mvt': 535093, 'ends_before_mvt': 1502, 'elapsed_sec': 2322.9, 'mvts_per_sec': 663.02, 'rss_gib': 2.1533203125}

{'buckets': '336/512', 'mvts': 1540140, 'assigned_mvts': 1536841, 'single': 1457190, 'multiple': 79651, 'physical_flights': 1621350, 'max_physical_flights': 8, 'selected': 1521359, 'resampled': 1521359, 'rows': 852564943, 'unresolved': 18781, 'contains_mvt': 984764, 'starts_after_mvt': 535093, 'ends_before_mvt': 1502, 'elapsed_sec': 2352.9, 'mvts_per_sec': 654.56, 'rss_gib': 2.1533203125}

{'buckets': '337/512', 'mvts': 1544823, 'assigned_mvts': 1541511, 'single': 1461625, 'multiple': 79886, 'physical_flights': 1626267, 'max_physical_flights': 8, 'selected': 1525986, 'resampled': 1525986, 'rows': 855120770, 'unresolved': 18837, 'contains_mvt': 987712, 'starts_after_mvt': 536767, 'ends_before_mvt': 1507, 'elapsed_sec': 2353.4, 'mvts_per_sec': 656.42, 'rss_gib': 2.1533203125}

{'buckets': '338/512', 'mvts': 1549328, 'assigned_mvts': 1546009, 'single': 1465887, 'multiple': 80122, 'physical_flights': 1631015, 'max_physical_flights': 8, 'selected': 1530429, 'resampled': 1530429, 'rows': 857605396, 'unresolved': 18899, 'contains_mvt': 990593, 'starts_after_mvt': 538321, 'ends_before_mvt': 1515, 'elapsed_sec': 2366.7, 'mvts_per_sec': 654.63, 'rss_gib': 2.1533203125}

{'buckets': '339/512', 'mvts': 1553875, 'assigned_mvts': 1550552, 'single': 1470187, 'multiple': 80365, 'physical_flights': 1635811, 'max_physical_flights': 8, 'selected': 1534928, 'resampled': 1534928, 'rows': 860179177, 'unresolved': 18947, 'contains_mvt': 993524, 'starts_after_mvt': 539888, 'ends_before_mvt': 1516, 'elapsed_sec': 2371.2, 'mvts_per_sec': 655.32, 'rss_gib': 2.1533203125}

{'buckets': '340/512', 'mvts': 1558515, 'assigned_mvts': 1555177, 'single': 1474573, 'multiple': 80604, 'physical_flights': 1640688, 'max_physical_flights': 8, 'selected': 1539504, 'resampled': 1539504, 'rows': 862715162, 'unresolved': 19011, 'contains_mvt': 996472, 'starts_after_mvt': 541509, 'ends_before_mvt': 1523, 'elapsed_sec': 2375.8, 'mvts_per_sec': 656.01, 'rss_gib': 2.1533203125}

{'buckets': '341/512', 'mvts': 1563070, 'assigned_mvts': 1559721, 'single': 1478887, 'multiple': 80834, 'physical_flights': 1645479, 'max_physical_flights': 8, 'selected': 1544003, 'resampled': 1544003, 'rows': 865220808, 'unresolved': 19067, 'contains_mvt': 999376, 'starts_after_mvt': 543098, 'ends_before_mvt': 1529, 'elapsed_sec': 2401.5, 'mvts_per_sec': 650.88, 'rss_gib': 2.1533203125}

{'buckets': '342/512', 'mvts': 1567591, 'assigned_mvts': 1564234, 'single': 1483187, 'multiple': 81047, 'physical_flights': 1650220, 'max_physical_flights': 8, 'selected': 1548477, 'resampled': 1548477, 'rows': 867730507, 'unresolved': 19114, 'contains_mvt': 1002235, 'starts_after_mvt': 544707, 'ends_before_mvt': 1535, 'elapsed_sec': 2404.6, 'mvts_per_sec': 651.91, 'rss_gib': 2.1533203125}

{'buckets': '343/512', 'mvts': 1572103, 'assigned_mvts': 1568739, 'single': 1487460, 'multiple': 81279, 'physical_flights': 1654980, 'max_physical_flights': 8, 'selected': 1552940, 'resampled': 1552940, 'rows': 870191483, 'unresolved': 19163, 'contains_mvt': 1005097, 'starts_after_mvt': 546304, 'ends_before_mvt': 1539, 'elapsed_sec': 2409.0, 'mvts_per_sec': 652.59, 'rss_gib': 2.1533203125}

{'buckets': '344/512', 'mvts': 1576584, 'assigned_mvts': 1573211, 'single': 1491701, 'multiple': 81510, 'physical_flights': 1659703, 'max_physical_flights': 8, 'selected': 1557379, 'resampled': 1557379, 'rows': 872725835, 'unresolved': 19205, 'contains_mvt': 1007960, 'starts_after_mvt': 547875, 'ends_before_mvt': 1544, 'elapsed_sec': 2410.6, 'mvts_per_sec': 654.03, 'rss_gib': 2.1533203125}

{'buckets': '345/512', 'mvts': 1581119, 'assigned_mvts': 1577730, 'single': 1495963, 'multiple': 81767, 'physical_flights': 1664491, 'max_physical_flights': 8, 'selected': 1561846, 'resampled': 1561846, 'rows': 875237680, 'unresolved': 19273, 'contains_mvt': 1010888, 'starts_after_mvt': 549410, 'ends_before_mvt': 1548, 'elapsed_sec': 2412.7, 'mvts_per_sec': 655.34, 'rss_gib': 2.1533203125}

{'buckets': '346/512', 'mvts': 1585750, 'assigned_mvts': 1582350, 'single': 1500324, 'multiple': 82026, 'physical_flights': 1669385, 'max_physical_flights': 8, 'selected': 1566420, 'resampled': 1566420, 'rows': 877755367, 'unresolved': 19330, 'contains_mvt': 1013865, 'starts_after_mvt': 551005, 'ends_before_mvt': 1550, 'elapsed_sec': 2416.8, 'mvts_per_sec': 656.13, 'rss_gib': 2.1533203125}

{'buckets': '347/512', 'mvts': 1590338, 'assigned_mvts': 1586929, 'single': 1504657, 'multiple': 82272, 'physical_flights': 1674222, 'max_physical_flights': 8, 'selected': 1570947, 'resampled': 1570947, 'rows': 880293759, 'unresolved': 19391, 'contains_mvt': 1016780, 'starts_after_mvt': 552610, 'ends_before_mvt': 1557, 'elapsed_sec': 2420.9, 'mvts_per_sec': 656.91, 'rss_gib': 2.1533203125}

{'buckets': '348/512', 'mvts': 1594825, 'assigned_mvts': 1591407, 'single': 1508895, 'multiple': 82512, 'physical_flights': 1678953, 'max_physical_flights': 8, 'selected': 1575380, 'resampled': 1575380, 'rows': 882789427, 'unresolved': 19445, 'contains_mvt': 1019702, 'starts_after_mvt': 554119, 'ends_before_mvt': 1559, 'elapsed_sec': 2423.3, 'mvts_per_sec': 658.13, 'rss_gib': 2.1533203125}

{'buckets': '349/512', 'mvts': 1599387, 'assigned_mvts': 1595961, 'single': 1513215, 'multiple': 82746, 'physical_flights': 1683762, 'max_physical_flights': 8, 'selected': 1579891, 'resampled': 1579891, 'rows': 885341650, 'unresolved': 19496, 'contains_mvt': 1022610, 'starts_after_mvt': 555720, 'ends_before_mvt': 1561, 'elapsed_sec': 2440.2, 'mvts_per_sec': 655.43, 'rss_gib': 2.1533203125}

{'buckets': '350/512', 'mvts': 1603996, 'assigned_mvts': 1600558, 'single': 1517571, 'multiple': 82987, 'physical_flights': 1688615, 'max_physical_flights': 8, 'selected': 1584450, 'resampled': 1584450, 'rows': 887931799, 'unresolved': 19546, 'contains_mvt': 1025626, 'starts_after_mvt': 557257, 'ends_before_mvt': 1567, 'elapsed_sec': 2444.9, 'mvts_per_sec': 656.05, 'rss_gib': 2.1533203125}

{'buckets': '351/512', 'mvts': 1608562, 'assigned_mvts': 1605115, 'single': 1521908, 'multiple': 83207, 'physical_flights': 1693410, 'max_physical_flights': 8, 'selected': 1588955, 'resampled': 1588955, 'rows': 890453584, 'unresolved': 19607, 'contains_mvt': 1028570, 'starts_after_mvt': 558815, 'ends_before_mvt': 1570, 'elapsed_sec': 2448.2, 'mvts_per_sec': 657.04, 'rss_gib': 2.1533203125}

{'buckets': '352/512', 'mvts': 1613229, 'assigned_mvts': 1609776, 'single': 1526321, 'multiple': 83455, 'physical_flights': 1698330, 'max_physical_flights': 8, 'selected': 1593563, 'resampled': 1593563, 'rows': 893086979, 'unresolved': 19666, 'contains_mvt': 1031562, 'starts_after_mvt': 560431, 'ends_before_mvt': 1570, 'elapsed_sec': 2449.5, 'mvts_per_sec': 658.6, 'rss_gib': 2.1533203125}

{'buckets': '353/512', 'mvts': 1617857, 'assigned_mvts': 1614396, 'single': 1530703, 'multiple': 83693, 'physical_flights': 1703197, 'max_physical_flights': 8, 'selected': 1598129, 'resampled': 1598129, 'rows': 895641927, 'unresolved': 19728, 'contains_mvt': 1034570, 'starts_after_mvt': 561985, 'ends_before_mvt': 1574, 'elapsed_sec': 2452.8, 'mvts_per_sec': 659.6, 'rss_gib': 2.1533203125}

{'buckets': '354/512', 'mvts': 1622483, 'assigned_mvts': 1619014, 'single': 1535101, 'multiple': 83913, 'physical_flights': 1708049, 'max_physical_flights': 8, 'selected': 1602705, 'resampled': 1602705, 'rows': 898284119, 'unresolved': 19778, 'contains_mvt': 1037577, 'starts_after_mvt': 563551, 'ends_before_mvt': 1577, 'elapsed_sec': 2454.6, 'mvts_per_sec': 661.01, 'rss_gib': 2.1533203125}

{'buckets': '355/512', 'mvts': 1627073, 'assigned_mvts': 1623598, 'single': 1539454, 'multiple': 84144, 'physical_flights': 1712884, 'max_physical_flights': 8, 'selected': 1607241, 'resampled': 1607241, 'rows': 900766086, 'unresolved': 19832, 'contains_mvt': 1040432, 'starts_after_mvt': 565230, 'ends_before_mvt': 1579, 'elapsed_sec': 2469.4, 'mvts_per_sec': 658.9, 'rss_gib': 2.1533203125}

{'buckets': '356/512', 'mvts': 1631580, 'assigned_mvts': 1628098, 'single': 1543742, 'multiple': 84356, 'physical_flights': 1717612, 'max_physical_flights': 8, 'selected': 1611713, 'resampled': 1611713, 'rows': 903287969, 'unresolved': 19867, 'contains_mvt': 1043328, 'starts_after_mvt': 566801, 'ends_before_mvt': 1584, 'elapsed_sec': 2472.8, 'mvts_per_sec': 659.82, 'rss_gib': 2.1533203125}

{'buckets': '357/512', 'mvts': 1636109, 'assigned_mvts': 1632621, 'single': 1547994, 'multiple': 84627, 'physical_flights': 1722425, 'max_physical_flights': 8, 'selected': 1616193, 'resampled': 1616193, 'rows': 905784407, 'unresolved': 19916, 'contains_mvt': 1046229, 'starts_after_mvt': 568373, 'ends_before_mvt': 1591, 'elapsed_sec': 2495.2, 'mvts_per_sec': 655.7, 'rss_gib': 2.1533203125}

{'buckets': '358/512', 'mvts': 1640603, 'assigned_mvts': 1637108, 'single': 1552252, 'multiple': 84856, 'physical_flights': 1727156, 'max_physical_flights': 8, 'selected': 1620642, 'resampled': 1620642, 'rows': 908304259, 'unresolved': 19961, 'contains_mvt': 1049133, 'starts_after_mvt': 569912, 'ends_before_mvt': 1597, 'elapsed_sec': 2496.8, 'mvts_per_sec': 657.08, 'rss_gib': 2.1533203125}

{'buckets': '359/512', 'mvts': 1645264, 'assigned_mvts': 1641755, 'single': 1556663, 'multiple': 85092, 'physical_flights': 1732051, 'max_physical_flights': 8, 'selected': 1625246, 'resampled': 1625246, 'rows': 910886773, 'unresolved': 20018, 'contains_mvt': 1052133, 'starts_after_mvt': 571511, 'ends_before_mvt': 1602, 'elapsed_sec': 2503.0, 'mvts_per_sec': 657.32, 'rss_gib': 2.1533203125}

{'buckets': '360/512', 'mvts': 1649728, 'assigned_mvts': 1646210, 'single': 1560880, 'multiple': 85330, 'physical_flights': 1736758, 'max_physical_flights': 8, 'selected': 1629653, 'resampled': 1629653, 'rows': 913346648, 'unresolved': 20075, 'contains_mvt': 1055006, 'starts_after_mvt': 573037, 'ends_before_mvt': 1610, 'elapsed_sec': 2504.9, 'mvts_per_sec': 658.59, 'rss_gib': 2.1533203125}

{'buckets': '361/512', 'mvts': 1654302, 'assigned_mvts': 1650772, 'single': 1565167, 'multiple': 85605, 'physical_flights': 1741604, 'max_physical_flights': 8, 'selected': 1634177, 'resampled': 1634177, 'rows': 915852528, 'unresolved': 20125, 'contains_mvt': 1057909, 'starts_after_mvt': 574654, 'ends_before_mvt': 1614, 'elapsed_sec': 2505.7, 'mvts_per_sec': 660.22, 'rss_gib': 2.1533203125}

{'buckets': '362/512', 'mvts': 1658878, 'assigned_mvts': 1655338, 'single': 1569511, 'multiple': 85827, 'physical_flights': 1746401, 'max_physical_flights': 8, 'selected': 1638699, 'resampled': 1638699, 'rows': 918385710, 'unresolved': 20179, 'contains_mvt': 1060849, 'starts_after_mvt': 576231, 'ends_before_mvt': 1619, 'elapsed_sec': 2510.2, 'mvts_per_sec': 660.86, 'rss_gib': 2.1533203125}

{'buckets': '363/512', 'mvts': 1663543, 'assigned_mvts': 1659989, 'single': 1573916, 'multiple': 86073, 'physical_flights': 1751323, 'max_physical_flights': 8, 'selected': 1643302, 'resampled': 1643302, 'rows': 920957906, 'unresolved': 20241, 'contains_mvt': 1063824, 'starts_after_mvt': 577857, 'ends_before_mvt': 1621, 'elapsed_sec': 2519.5, 'mvts_per_sec': 660.27, 'rss_gib': 2.1533203125}

{'buckets': '364/512', 'mvts': 1668136, 'assigned_mvts': 1664571, 'single': 1578218, 'multiple': 86353, 'physical_flights': 1756197, 'max_physical_flights': 8, 'selected': 1647839, 'resampled': 1647839, 'rows': 923504947, 'unresolved': 20297, 'contains_mvt': 1066730, 'starts_after_mvt': 579487, 'ends_before_mvt': 1622, 'elapsed_sec': 2523.5, 'mvts_per_sec': 661.04, 'rss_gib': 2.1533203125}

{'buckets': '365/512', 'mvts': 1672693, 'assigned_mvts': 1669115, 'single': 1582514, 'multiple': 86601, 'physical_flights': 1761002, 'max_physical_flights': 8, 'selected': 1652337, 'resampled': 1652337, 'rows': 926031660, 'unresolved': 20356, 'contains_mvt': 1069673, 'starts_after_mvt': 581039, 'ends_before_mvt': 1625, 'elapsed_sec': 2523.8, 'mvts_per_sec': 662.76, 'rss_gib': 2.1533203125}

{'buckets': '366/512', 'mvts': 1677254, 'assigned_mvts': 1673665, 'single': 1586835, 'multiple': 86830, 'physical_flights': 1765793, 'max_physical_flights': 8, 'selected': 1656840, 'resampled': 1656840, 'rows': 928589007, 'unresolved': 20414, 'contains_mvt': 1072597, 'starts_after_mvt': 582613, 'ends_before_mvt': 1630, 'elapsed_sec': 2543.2, 'mvts_per_sec': 659.52, 'rss_gib': 2.1533203125}

{'buckets': '367/512', 'mvts': 1681796, 'assigned_mvts': 1678193, 'single': 1591110, 'multiple': 87083, 'physical_flights': 1770587, 'max_physical_flights': 8, 'selected': 1661315, 'resampled': 1661315, 'rows': 931070826, 'unresolved': 20481, 'contains_mvt': 1075482, 'starts_after_mvt': 584200, 'ends_before_mvt': 1633, 'elapsed_sec': 2566.7, 'mvts_per_sec': 655.25, 'rss_gib': 2.1533203125}

{'buckets': '368/512', 'mvts': 1686411, 'assigned_mvts': 1682797, 'single': 1595468, 'multiple': 87329, 'physical_flights': 1775449, 'max_physical_flights': 8, 'selected': 1665875, 'resampled': 1665875, 'rows': 933633650, 'unresolved': 20536, 'contains_mvt': 1078425, 'starts_after_mvt': 585812, 'ends_before_mvt': 1638, 'elapsed_sec': 2580.1, 'mvts_per_sec': 653.63, 'rss_gib': 2.1533203125}

{'buckets': '369/512', 'mvts': 1691030, 'assigned_mvts': 1687406, 'single': 1599834, 'multiple': 87572, 'physical_flights': 1780314, 'max_physical_flights': 8, 'selected': 1670429, 'resampled': 1670429, 'rows': 936183167, 'unresolved': 20601, 'contains_mvt': 1081379, 'starts_after_mvt': 587408, 'ends_before_mvt': 1642, 'elapsed_sec': 2582.3, 'mvts_per_sec': 654.86, 'rss_gib': 2.1533203125}

{'buckets': '370/512', 'mvts': 1695683, 'assigned_mvts': 1692051, 'single': 1604254, 'multiple': 87797, 'physical_flights': 1785196, 'max_physical_flights': 8, 'selected': 1675031, 'resampled': 1675031, 'rows': 938821513, 'unresolved': 20652, 'contains_mvt': 1084375, 'starts_after_mvt': 589010, 'ends_before_mvt': 1646, 'elapsed_sec': 2595.8, 'mvts_per_sec': 653.25, 'rss_gib': 2.1533203125}

{'buckets': '371/512', 'mvts': 1700181, 'assigned_mvts': 1696543, 'single': 1608521, 'multiple': 88022, 'physical_flights': 1789928, 'max_physical_flights': 8, 'selected': 1679484, 'resampled': 1679484, 'rows': 941278009, 'unresolved': 20697, 'contains_mvt': 1087212, 'starts_after_mvt': 590625, 'ends_before_mvt': 1647, 'elapsed_sec': 2596.8, 'mvts_per_sec': 654.72, 'rss_gib': 2.1533203125}

{'buckets': '372/512', 'mvts': 1704763, 'assigned_mvts': 1701116, 'single': 1612868, 'multiple': 88248, 'physical_flights': 1794749, 'max_physical_flights': 8, 'selected': 1684013, 'resampled': 1684013, 'rows': 943828131, 'unresolved': 20750, 'contains_mvt': 1090174, 'starts_after_mvt': 592187, 'ends_before_mvt': 1652, 'elapsed_sec': 2610.2, 'mvts_per_sec': 653.1, 'rss_gib': 2.1533203125}

{'buckets': '373/512', 'mvts': 1709364, 'assigned_mvts': 1705704, 'single': 1617210, 'multiple': 88494, 'physical_flights': 1799599, 'max_physical_flights': 8, 'selected': 1688566, 'resampled': 1688566, 'rows': 946428425, 'unresolved': 20798, 'contains_mvt': 1093195, 'starts_after_mvt': 593714, 'ends_before_mvt': 1657, 'elapsed_sec': 2610.5, 'mvts_per_sec': 654.8, 'rss_gib': 2.1533203125}

{'buckets': '374/512', 'mvts': 1713981, 'assigned_mvts': 1710316, 'single': 1621558, 'multiple': 88758, 'physical_flights': 1804487, 'max_physical_flights': 8, 'selected': 1693144, 'resampled': 1693144, 'rows': 948897974, 'unresolved': 20837, 'contains_mvt': 1096114, 'starts_after_mvt': 595369, 'ends_before_mvt': 1661, 'elapsed_sec': 2612.6, 'mvts_per_sec': 656.05, 'rss_gib': 2.1533203125}

{'buckets': '375/512', 'mvts': 1718575, 'assigned_mvts': 1714897, 'single': 1625902, 'multiple': 88995, 'physical_flights': 1809321, 'max_physical_flights': 8, 'selected': 1697679, 'resampled': 1697679, 'rows': 951515603, 'unresolved': 20896, 'contains_mvt': 1099098, 'starts_after_mvt': 596917, 'ends_before_mvt': 1664, 'elapsed_sec': 2615.6, 'mvts_per_sec': 657.04, 'rss_gib': 2.1533203125}

{'buckets': '376/512', 'mvts': 1723024, 'assigned_mvts': 1719334, 'single': 1630115, 'multiple': 89219, 'physical_flights': 1813991, 'max_physical_flights': 8, 'selected': 1702074, 'resampled': 1702074, 'rows': 953919062, 'unresolved': 20950, 'contains_mvt': 1101894, 'starts_after_mvt': 598511, 'ends_before_mvt': 1669, 'elapsed_sec': 2618.3, 'mvts_per_sec': 658.08, 'rss_gib': 2.1533203125}

{'buckets': '377/512', 'mvts': 1727749, 'assigned_mvts': 1724050, 'single': 1634616, 'multiple': 89434, 'physical_flights': 1818930, 'max_physical_flights': 8, 'selected': 1706730, 'resampled': 1706730, 'rows': 956512452, 'unresolved': 21019, 'contains_mvt': 1104922, 'starts_after_mvt': 600137, 'ends_before_mvt': 1671, 'elapsed_sec': 2618.3, 'mvts_per_sec': 659.87, 'rss_gib': 2.1533203125}

{'buckets': '378/512', 'mvts': 1732319, 'assigned_mvts': 1728606, 'single': 1638906, 'multiple': 89700, 'physical_flights': 1823762, 'max_physical_flights': 8, 'selected': 1711248, 'resampled': 1711248, 'rows': 959084374, 'unresolved': 21071, 'contains_mvt': 1107869, 'starts_after_mvt': 601700, 'ends_before_mvt': 1679, 'elapsed_sec': 2621.3, 'mvts_per_sec': 660.86, 'rss_gib': 2.1533203125}

{'buckets': '379/512', 'mvts': 1736973, 'assigned_mvts': 1733241, 'single': 1643311, 'multiple': 89930, 'physical_flights': 1828642, 'max_physical_flights': 8, 'selected': 1715823, 'resampled': 1715823, 'rows': 961678594, 'unresolved': 21150, 'contains_mvt': 1110885, 'starts_after_mvt': 603256, 'ends_before_mvt': 1682, 'elapsed_sec': 2627.2, 'mvts_per_sec': 661.16, 'rss_gib': 2.1533203125}

{'buckets': '380/512', 'mvts': 1741496, 'assigned_mvts': 1737757, 'single': 1647584, 'multiple': 90173, 'physical_flights': 1833420, 'max_physical_flights': 8, 'selected': 1720291, 'resampled': 1720291, 'rows': 964225492, 'unresolved': 21205, 'contains_mvt': 1113839, 'starts_after_mvt': 604766, 'ends_before_mvt': 1686, 'elapsed_sec': 2627.2, 'mvts_per_sec': 662.88, 'rss_gib': 2.1533203125}

{'buckets': '381/512', 'mvts': 1746071, 'assigned_mvts': 1742326, 'single': 1651946, 'multiple': 90380, 'physical_flights': 1838211, 'max_physical_flights': 8, 'selected': 1724816, 'resampled': 1724816, 'rows': 966697967, 'unresolved': 21255, 'contains_mvt': 1116751, 'starts_after_mvt': 606370, 'ends_before_mvt': 1695, 'elapsed_sec': 2634.3, 'mvts_per_sec': 662.82, 'rss_gib': 2.1533203125}

{'buckets': '382/512', 'mvts': 1750727, 'assigned_mvts': 1746971, 'single': 1656340, 'multiple': 90631, 'physical_flights': 1843118, 'max_physical_flights': 8, 'selected': 1729422, 'resampled': 1729422, 'rows': 969309476, 'unresolved': 21305, 'contains_mvt': 1119733, 'starts_after_mvt': 607989, 'ends_before_mvt': 1700, 'elapsed_sec': 2641.5, 'mvts_per_sec': 662.79, 'rss_gib': 2.1533203125}

{'buckets': '383/512', 'mvts': 1755257, 'assigned_mvts': 1751487, 'single': 1660643, 'multiple': 90844, 'physical_flights': 1847864, 'max_physical_flights': 8, 'selected': 1733895, 'resampled': 1733895, 'rows': 971769868, 'unresolved': 21362, 'contains_mvt': 1122579, 'starts_after_mvt': 609612, 'ends_before_mvt': 1704, 'elapsed_sec': 2654.4, 'mvts_per_sec': 661.27, 'rss_gib': 2.1533203125}

{'buckets': '384/512', 'mvts': 1759832, 'assigned_mvts': 1756052, 'single': 1664997, 'multiple': 91055, 'physical_flights': 1852650, 'max_physical_flights': 8, 'selected': 1738409, 'resampled': 1738409, 'rows': 974269358, 'unresolved': 21423, 'contains_mvt': 1125459, 'starts_after_mvt': 611243, 'ends_before_mvt': 1707, 'elapsed_sec': 2656.6, 'mvts_per_sec': 662.43, 'rss_gib': 2.1533203125}

{'buckets': '385/512', 'mvts': 1764465, 'assigned_mvts': 1760671, 'single': 1669387, 'multiple': 91284, 'physical_flights': 1857511, 'max_physical_flights': 8, 'selected': 1742983, 'resampled': 1742983, 'rows': 976836986, 'unresolved': 21482, 'contains_mvt': 1128467, 'starts_after_mvt': 612805, 'ends_before_mvt': 1711, 'elapsed_sec': 2666.0, 'mvts_per_sec': 661.83, 'rss_gib': 2.1533203125}

{'buckets': '386/512', 'mvts': 1768942, 'assigned_mvts': 1765141, 'single': 1673627, 'multiple': 91514, 'physical_flights': 1862232, 'max_physical_flights': 8, 'selected': 1747408, 'resampled': 1747408, 'rows': 979301868, 'unresolved': 21534, 'contains_mvt': 1131256, 'starts_after_mvt': 614436, 'ends_before_mvt': 1716, 'elapsed_sec': 2683.1, 'mvts_per_sec': 659.29, 'rss_gib': 2.1533203125}

{'buckets': '387/512', 'mvts': 1773473, 'assigned_mvts': 1769656, 'single': 1677898, 'multiple': 91758, 'physical_flights': 1867002, 'max_physical_flights': 8, 'selected': 1751875, 'resampled': 1751875, 'rows': 981826926, 'unresolved': 21598, 'contains_mvt': 1134159, 'starts_after_mvt': 615996, 'ends_before_mvt': 1720, 'elapsed_sec': 2684.0, 'mvts_per_sec': 660.75, 'rss_gib': 2.1533203125}

{'buckets': '388/512', 'mvts': 1778047, 'assigned_mvts': 1774218, 'single': 1682205, 'multiple': 92013, 'physical_flights': 1871834, 'max_physical_flights': 8, 'selected': 1756389, 'resampled': 1756389, 'rows': 984356867, 'unresolved': 21658, 'contains_mvt': 1137065, 'starts_after_mvt': 617598, 'ends_before_mvt': 1726, 'elapsed_sec': 2694.1, 'mvts_per_sec': 659.98, 'rss_gib': 2.1533203125}

{'buckets': '389/512', 'mvts': 1782617, 'assigned_mvts': 1778773, 'single': 1686526, 'multiple': 92247, 'physical_flights': 1876633, 'max_physical_flights': 8, 'selected': 1760907, 'resampled': 1760907, 'rows': 986916397, 'unresolved': 21710, 'contains_mvt': 1140027, 'starts_after_mvt': 619151, 'ends_before_mvt': 1729, 'elapsed_sec': 2697.3, 'mvts_per_sec': 660.9, 'rss_gib': 2.1533203125}

{'buckets': '390/512', 'mvts': 1787112, 'assigned_mvts': 1783263, 'single': 1690773, 'multiple': 92490, 'physical_flights': 1881381, 'max_physical_flights': 8, 'selected': 1765352, 'resampled': 1765352, 'rows': 989407315, 'unresolved': 21760, 'contains_mvt': 1142964, 'starts_after_mvt': 620656, 'ends_before_mvt': 1732, 'elapsed_sec': 2702.2, 'mvts_per_sec': 661.35, 'rss_gib': 2.1533203125}

{'buckets': '391/512', 'mvts': 1791720, 'assigned_mvts': 1787858, 'single': 1695117, 'multiple': 92741, 'physical_flights': 1886246, 'max_physical_flights': 8, 'selected': 1769887, 'resampled': 1769887, 'rows': 991975244, 'unresolved': 21833, 'contains_mvt': 1145867, 'starts_after_mvt': 622279, 'ends_before_mvt': 1741, 'elapsed_sec': 2703.6, 'mvts_per_sec': 662.72, 'rss_gib': 2.1533203125}

{'buckets': '392/512', 'mvts': 1796339, 'assigned_mvts': 1792467, 'single': 1699496, 'multiple': 92971, 'physical_flights': 1891106, 'max_physical_flights': 8, 'selected': 1774450, 'resampled': 1774450, 'rows': 994518681, 'unresolved': 21889, 'contains_mvt': 1148818, 'starts_after_mvt': 623889, 'ends_before_mvt': 1743, 'elapsed_sec': 2706.2, 'mvts_per_sec': 663.8, 'rss_gib': 2.1533203125}

{'buckets': '393/512', 'mvts': 1800882, 'assigned_mvts': 1796998, 'single': 1703808, 'multiple': 93190, 'physical_flights': 1895868, 'max_physical_flights': 8, 'selected': 1778940, 'resampled': 1778940, 'rows': 997006257, 'unresolved': 21942, 'contains_mvt': 1151729, 'starts_after_mvt': 625461, 'ends_before_mvt': 1750, 'elapsed_sec': 2709.6, 'mvts_per_sec': 664.63, 'rss_gib': 2.1533203125}

{'buckets': '394/512', 'mvts': 1805397, 'assigned_mvts': 1801507, 'single': 1708089, 'multiple': 93418, 'physical_flights': 1900613, 'max_physical_flights': 8, 'selected': 1783411, 'resampled': 1783411, 'rows': 999441169, 'unresolved': 21986, 'contains_mvt': 1154575, 'starts_after_mvt': 627079, 'ends_before_mvt': 1757, 'elapsed_sec': 2718.6, 'mvts_per_sec': 664.08, 'rss_gib': 2.1533203125}

{'buckets': '395/512', 'mvts': 1809990, 'assigned_mvts': 1806091, 'single': 1712436, 'multiple': 93655, 'physical_flights': 1905453, 'max_physical_flights': 8, 'selected': 1787954, 'resampled': 1787954, 'rows': 1001973731, 'unresolved': 22036, 'contains_mvt': 1157530, 'starts_after_mvt': 628664, 'ends_before_mvt': 1760, 'elapsed_sec': 2745.3, 'mvts_per_sec': 659.31, 'rss_gib': 2.1533203125}

{'buckets': '396/512', 'mvts': 1814502, 'assigned_mvts': 1810596, 'single': 1716702, 'multiple': 93894, 'physical_flights': 1910208, 'max_physical_flights': 8, 'selected': 1792422, 'resampled': 1792422, 'rows': 1004450557, 'unresolved': 22080, 'contains_mvt': 1160394, 'starts_after_mvt': 630267, 'ends_before_mvt': 1761, 'elapsed_sec': 2749.0, 'mvts_per_sec': 660.06, 'rss_gib': 2.1533203125}

{'buckets': '397/512', 'mvts': 1819284, 'assigned_mvts': 1815372, 'single': 1721203, 'multiple': 94169, 'physical_flights': 1915273, 'max_physical_flights': 8, 'selected': 1797146, 'resampled': 1797146, 'rows': 1007082062, 'unresolved': 22138, 'contains_mvt': 1163442, 'starts_after_mvt': 631938, 'ends_before_mvt': 1766, 'elapsed_sec': 2772.1, 'mvts_per_sec': 656.29, 'rss_gib': 2.1533203125}

{'buckets': '398/512', 'mvts': 1823926, 'assigned_mvts': 1820008, 'single': 1725608, 'multiple': 94400, 'physical_flights': 1920147, 'max_physical_flights': 8, 'selected': 1801724, 'resampled': 1801724, 'rows': 1009648492, 'unresolved': 22202, 'contains_mvt': 1166383, 'starts_after_mvt': 633566, 'ends_before_mvt': 1775, 'elapsed_sec': 2780.0, 'mvts_per_sec': 656.09, 'rss_gib': 2.1533203125}

{'buckets': '399/512', 'mvts': 1828470, 'assigned_mvts': 1824539, 'single': 1729876, 'multiple': 94663, 'physical_flights': 1924963, 'max_physical_flights': 8, 'selected': 1806209, 'resampled': 1806209, 'rows': 1012191852, 'unresolved': 22261, 'contains_mvt': 1169318, 'starts_after_mvt': 635113, 'ends_before_mvt': 1778, 'elapsed_sec': 2783.7, 'mvts_per_sec': 656.86, 'rss_gib': 2.1533203125}

{'buckets': '400/512', 'mvts': 1833041, 'assigned_mvts': 1829095, 'single': 1734190, 'multiple': 94905, 'physical_flights': 1929776, 'max_physical_flights': 8, 'selected': 1810718, 'resampled': 1810718, 'rows': 1014676079, 'unresolved': 22323, 'contains_mvt': 1172227, 'starts_after_mvt': 636706, 'ends_before_mvt': 1785, 'elapsed_sec': 2790.1, 'mvts_per_sec': 656.97, 'rss_gib': 2.1533203125}

{'buckets': '401/512', 'mvts': 1837777, 'assigned_mvts': 1833816, 'single': 1738667, 'multiple': 95149, 'physical_flights': 1934761, 'max_physical_flights': 8, 'selected': 1815387, 'resampled': 1815387, 'rows': 1017209843, 'unresolved': 22390, 'contains_mvt': 1175209, 'starts_after_mvt': 638387, 'ends_before_mvt': 1791, 'elapsed_sec': 2799.3, 'mvts_per_sec': 656.51, 'rss_gib': 2.1533203125}

{'buckets': '402/512', 'mvts': 1842317, 'assigned_mvts': 1838350, 'single': 1742963, 'multiple': 95387, 'physical_flights': 1939545, 'max_physical_flights': 8, 'selected': 1819879, 'resampled': 1819879, 'rows': 1019687766, 'unresolved': 22438, 'contains_mvt': 1178116, 'starts_after_mvt': 639966, 'ends_before_mvt': 1797, 'elapsed_sec': 2802.3, 'mvts_per_sec': 657.42, 'rss_gib': 2.1533203125}

{'buckets': '403/512', 'mvts': 1846897, 'assigned_mvts': 1842922, 'single': 1747296, 'multiple': 95626, 'physical_flights': 1944377, 'max_physical_flights': 8, 'selected': 1824411, 'resampled': 1824411, 'rows': 1022228830, 'unresolved': 22486, 'contains_mvt': 1181112, 'starts_after_mvt': 641499, 'ends_before_mvt': 1800, 'elapsed_sec': 2802.4, 'mvts_per_sec': 659.04, 'rss_gib': 2.1533203125}

{'buckets': '404/512', 'mvts': 1851413, 'assigned_mvts': 1847431, 'single': 1751542, 'multiple': 95889, 'physical_flights': 1949167, 'max_physical_flights': 8, 'selected': 1828888, 'resampled': 1828888, 'rows': 1024781995, 'unresolved': 22525, 'contains_mvt': 1184008, 'starts_after_mvt': 643077, 'ends_before_mvt': 1803, 'elapsed_sec': 2807.6, 'mvts_per_sec': 659.42, 'rss_gib': 2.1533203125}

{'buckets': '405/512', 'mvts': 1855947, 'assigned_mvts': 1851956, 'single': 1755814, 'multiple': 96142, 'physical_flights': 1953958, 'max_physical_flights': 8, 'selected': 1833374, 'resampled': 1833374, 'rows': 1027331462, 'unresolved': 22573, 'contains_mvt': 1186954, 'starts_after_mvt': 644611, 'ends_before_mvt': 1809, 'elapsed_sec': 2807.8, 'mvts_per_sec': 661.0, 'rss_gib': 2.1533203125}

{'buckets': '406/512', 'mvts': 1860448, 'assigned_mvts': 1856449, 'single': 1760070, 'multiple': 96379, 'physical_flights': 1958700, 'max_physical_flights': 8, 'selected': 1837824, 'resampled': 1837824, 'rows': 1029882269, 'unresolved': 22624, 'contains_mvt': 1189885, 'starts_after_mvt': 646126, 'ends_before_mvt': 1813, 'elapsed_sec': 2815.4, 'mvts_per_sec': 660.81, 'rss_gib': 2.1533203125}

{'buckets': '407/512', 'mvts': 1864980, 'assigned_mvts': 1860974, 'single': 1764393, 'multiple': 96581, 'physical_flights': 1963441, 'max_physical_flights': 8, 'selected': 1842305, 'resampled': 1842305, 'rows': 1032387295, 'unresolved': 22675, 'contains_mvt': 1192774, 'starts_after_mvt': 647715, 'ends_before_mvt': 1816, 'elapsed_sec': 2818.1, 'mvts_per_sec': 661.78, 'rss_gib': 2.1533203125}

{'buckets': '408/512', 'mvts': 1869576, 'assigned_mvts': 1865559, 'single': 1768741, 'multiple': 96818, 'physical_flights': 1968271, 'max_physical_flights': 8, 'selected': 1846856, 'resampled': 1846856, 'rows': 1034917302, 'unresolved': 22720, 'contains_mvt': 1195739, 'starts_after_mvt': 649299, 'ends_before_mvt': 1818, 'elapsed_sec': 2818.6, 'mvts_per_sec': 663.31, 'rss_gib': 2.1533203125}

{'buckets': '409/512', 'mvts': 1874137, 'assigned_mvts': 1870108, 'single': 1773060, 'multiple': 97048, 'physical_flights': 1973061, 'max_physical_flights': 8, 'selected': 1851361, 'resampled': 1851361, 'rows': 1037443467, 'unresolved': 22776, 'contains_mvt': 1198653, 'starts_after_mvt': 650888, 'ends_before_mvt': 1820, 'elapsed_sec': 2822.0, 'mvts_per_sec': 664.11, 'rss_gib': 2.1533203125}

{'buckets': '410/512', 'mvts': 1878806, 'assigned_mvts': 1874770, 'single': 1777497, 'multiple': 97273, 'physical_flights': 1977964, 'max_physical_flights': 8, 'selected': 1855972, 'resampled': 1855972, 'rows': 1040020460, 'unresolved': 22834, 'contains_mvt': 1201659, 'starts_after_mvt': 652489, 'ends_before_mvt': 1824, 'elapsed_sec': 2829.3, 'mvts_per_sec': 664.05, 'rss_gib': 2.1533203125}

{'buckets': '411/512', 'mvts': 1883392, 'assigned_mvts': 1879348, 'single': 1781850, 'multiple': 97498, 'physical_flights': 1982788, 'max_physical_flights': 8, 'selected': 1860502, 'resampled': 1860502, 'rows': 1042529875, 'unresolved': 22890, 'contains_mvt': 1204566, 'starts_after_mvt': 654110, 'ends_before_mvt': 1826, 'elapsed_sec': 2833.2, 'mvts_per_sec': 664.76, 'rss_gib': 2.1533203125}

{'buckets': '412/512', 'mvts': 1888009, 'assigned_mvts': 1883954, 'single': 1786248, 'multiple': 97706, 'physical_flights': 1987617, 'max_physical_flights': 8, 'selected': 1865062, 'resampled': 1865062, 'rows': 1045120138, 'unresolved': 22947, 'contains_mvt': 1207527, 'starts_after_mvt': 655703, 'ends_before_mvt': 1832, 'elapsed_sec': 2848.8, 'mvts_per_sec': 662.74, 'rss_gib': 2.1533203125}

{'buckets': '413/512', 'mvts': 1892546, 'assigned_mvts': 1888481, 'single': 1790525, 'multiple': 97956, 'physical_flights': 1992407, 'max_physical_flights': 8, 'selected': 1869539, 'resampled': 1869539, 'rows': 1047664620, 'unresolved': 23007, 'contains_mvt': 1210472, 'starts_after_mvt': 657232, 'ends_before_mvt': 1835, 'elapsed_sec': 2864.1, 'mvts_per_sec': 660.78, 'rss_gib': 2.1533203125}

{'buckets': '414/512', 'mvts': 1897215, 'assigned_mvts': 1893143, 'single': 1794927, 'multiple': 98216, 'physical_flights': 1997344, 'max_physical_flights': 8, 'selected': 1874155, 'resampled': 1874155, 'rows': 1050298237, 'unresolved': 23060, 'contains_mvt': 1213477, 'starts_after_mvt': 658841, 'ends_before_mvt': 1837, 'elapsed_sec': 2866.8, 'mvts_per_sec': 661.79, 'rss_gib': 2.1533203125}

{'buckets': '415/512', 'mvts': 1901673, 'assigned_mvts': 1897597, 'single': 1799153, 'multiple': 98444, 'physical_flights': 2002041, 'max_physical_flights': 8, 'selected': 1878552, 'resampled': 1878552, 'rows': 1052795583, 'unresolved': 23121, 'contains_mvt': 1216300, 'starts_after_mvt': 660410, 'ends_before_mvt': 1842, 'elapsed_sec': 2874.9, 'mvts_per_sec': 661.47, 'rss_gib': 2.1533203125}

{'buckets': '416/512', 'mvts': 1906182, 'assigned_mvts': 1902095, 'single': 1803394, 'multiple': 98701, 'physical_flights': 2006814, 'max_physical_flights': 8, 'selected': 1883009, 'resampled': 1883009, 'rows': 1055310594, 'unresolved': 23173, 'contains_mvt': 1219207, 'starts_after_mvt': 661954, 'ends_before_mvt': 1848, 'elapsed_sec': 2880.4, 'mvts_per_sec': 661.78, 'rss_gib': 2.1533203125}

{'buckets': '417/512', 'mvts': 1910819, 'assigned_mvts': 1906718, 'single': 1807759, 'multiple': 98959, 'physical_flights': 2011711, 'max_physical_flights': 8, 'selected': 1887590, 'resampled': 1887590, 'rows': 1057861733, 'unresolved': 23229, 'contains_mvt': 1222181, 'starts_after_mvt': 663557, 'ends_before_mvt': 1852, 'elapsed_sec': 2883.5, 'mvts_per_sec': 662.68, 'rss_gib': 2.1533203125}

{'buckets': '418/512', 'mvts': 1915374, 'assigned_mvts': 1911270, 'single': 1812078, 'multiple': 99192, 'physical_flights': 2016510, 'max_physical_flights': 8, 'selected': 1892086, 'resampled': 1892086, 'rows': 1060391985, 'unresolved': 23288, 'contains_mvt': 1225083, 'starts_after_mvt': 665144, 'ends_before_mvt': 1859, 'elapsed_sec': 2897.5, 'mvts_per_sec': 661.05, 'rss_gib': 2.1533203125}

{'buckets': '419/512', 'mvts': 1919997, 'assigned_mvts': 1915882, 'single': 1816464, 'multiple': 99418, 'physical_flights': 2021359, 'max_physical_flights': 8, 'selected': 1896657, 'resampled': 1896657, 'rows': 1062927100, 'unresolved': 23340, 'contains_mvt': 1228048, 'starts_after_mvt': 666743, 'ends_before_mvt': 1866, 'elapsed_sec': 2900.5, 'mvts_per_sec': 661.95, 'rss_gib': 2.1533203125}

{'buckets': '420/512', 'mvts': 1924658, 'assigned_mvts': 1920533, 'single': 1820876, 'multiple': 99657, 'physical_flights': 2026266, 'max_physical_flights': 8, 'selected': 1901255, 'resampled': 1901255, 'rows': 1065605566, 'unresolved': 23403, 'contains_mvt': 1231095, 'starts_after_mvt': 668292, 'ends_before_mvt': 1868, 'elapsed_sec': 2901.9, 'mvts_per_sec': 663.24, 'rss_gib': 2.1533203125}

{'buckets': '421/512', 'mvts': 1929287, 'assigned_mvts': 1925155, 'single': 1825253, 'multiple': 99902, 'physical_flights': 2031153, 'max_physical_flights': 8, 'selected': 1905839, 'resampled': 1905839, 'rows': 1068150578, 'unresolved': 23448, 'contains_mvt': 1234043, 'starts_after_mvt': 669924, 'ends_before_mvt': 1872, 'elapsed_sec': 2911.2, 'mvts_per_sec': 662.71, 'rss_gib': 2.1533203125}

{'buckets': '422/512', 'mvts': 1933890, 'assigned_mvts': 1929751, 'single': 1829619, 'multiple': 100132, 'physical_flights': 2035995, 'max_physical_flights': 8, 'selected': 1910377, 'resampled': 1910377, 'rows': 1070691169, 'unresolved': 23513, 'contains_mvt': 1236971, 'starts_after_mvt': 671529, 'ends_before_mvt': 1877, 'elapsed_sec': 2915.1, 'mvts_per_sec': 663.41, 'rss_gib': 2.1533203125}

{'buckets': '423/512', 'mvts': 1938497, 'assigned_mvts': 1934346, 'single': 1833951, 'multiple': 100395, 'physical_flights': 2040864, 'max_physical_flights': 8, 'selected': 1914911, 'resampled': 1914911, 'rows': 1073172504, 'unresolved': 23586, 'contains_mvt': 1239929, 'starts_after_mvt': 673101, 'ends_before_mvt': 1881, 'elapsed_sec': 2917.5, 'mvts_per_sec': 664.45, 'rss_gib': 2.1533203125}

{'buckets': '424/512', 'mvts': 1943002, 'assigned_mvts': 1938840, 'single': 1838206, 'multiple': 100634, 'physical_flights': 2045613, 'max_physical_flights': 8, 'selected': 1919354, 'resampled': 1919354, 'rows': 1075670204, 'unresolved': 23648, 'contains_mvt': 1242793, 'starts_after_mvt': 674675, 'ends_before_mvt': 1886, 'elapsed_sec': 2918.1, 'mvts_per_sec': 665.85, 'rss_gib': 2.1533203125}

{'buckets': '425/512', 'mvts': 1947569, 'assigned_mvts': 1943395, 'single': 1842537, 'multiple': 100858, 'physical_flights': 2050403, 'max_physical_flights': 8, 'selected': 1923872, 'resampled': 1923872, 'rows': 1078168855, 'unresolved': 23697, 'contains_mvt': 1245671, 'starts_after_mvt': 676310, 'ends_before_mvt': 1891, 'elapsed_sec': 2935.0, 'mvts_per_sec': 663.58, 'rss_gib': 2.1533203125}

{'buckets': '425/512', 'mvts': 1947569, 'assigned_mvts': 1943395, 'single': 1842537, 'multiple': 100858, 'physical_flights': 2050403, 'max_physical_flights': 8, 'selected': 1923872, 'resampled': 1923872, 'rows': 1078168855, 'unresolved': 23697, 'contains_mvt': 1245671, 'starts_after_mvt': 676310, 'ends_before_mvt': 1891, 'elapsed_sec': 2965.0, 'mvts_per_sec': 656.86, 'rss_gib': 2.1533203125}

{'buckets': '426/512', 'mvts': 1952168, 'assigned_mvts': 1947986, 'single': 1846891, 'multiple': 101095, 'physical_flights': 2055242, 'max_physical_flights': 8, 'selected': 1928422, 'resampled': 1928422, 'rows': 1080710049, 'unresolved': 23746, 'contains_mvt': 1248610, 'starts_after_mvt': 677919, 'ends_before_mvt': 1893, 'elapsed_sec': 2975.0, 'mvts_per_sec': 656.2, 'rss_gib': 2.1533203125}

{'buckets': '427/512', 'mvts': 1956698, 'assigned_mvts': 1952506, 'single': 1851197, 'multiple': 101309, 'physical_flights': 2059991, 'max_physical_flights': 8, 'selected': 1932891, 'resampled': 1932891, 'rows': 1083167929, 'unresolved': 23807, 'contains_mvt': 1251445, 'starts_after_mvt': 679547, 'ends_before_mvt': 1899, 'elapsed_sec': 2976.4, 'mvts_per_sec': 657.42, 'rss_gib': 2.1533203125}

{'buckets': '428/512', 'mvts': 1961308, 'assigned_mvts': 1957107, 'single': 1855561, 'multiple': 101546, 'physical_flights': 2064840, 'max_physical_flights': 8, 'selected': 1937441, 'resampled': 1937441, 'rows': 1085735676, 'unresolved': 23867, 'contains_mvt': 1254375, 'starts_after_mvt': 681164, 'ends_before_mvt': 1902, 'elapsed_sec': 2976.9, 'mvts_per_sec': 658.84, 'rss_gib': 2.1533203125}

{'buckets': '429/512', 'mvts': 1965822, 'assigned_mvts': 1961612, 'single': 1859809, 'multiple': 101803, 'physical_flights': 2069622, 'max_physical_flights': 8, 'selected': 1941889, 'resampled': 1941889, 'rows': 1088257421, 'unresolved': 23933, 'contains_mvt': 1257246, 'starts_after_mvt': 682733, 'ends_before_mvt': 1910, 'elapsed_sec': 2983.4, 'mvts_per_sec': 658.93, 'rss_gib': 2.1533203125}

{'buckets': '430/512', 'mvts': 1970510, 'assigned_mvts': 1966293, 'single': 1864250, 'multiple': 102043, 'physical_flights': 2074555, 'max_physical_flights': 8, 'selected': 1946527, 'resampled': 1946527, 'rows': 1090788463, 'unresolved': 23983, 'contains_mvt': 1260200, 'starts_after_mvt': 684412, 'ends_before_mvt': 1915, 'elapsed_sec': 2984.9, 'mvts_per_sec': 660.15, 'rss_gib': 2.1533203125}

{'buckets': '431/512', 'mvts': 1974983, 'assigned_mvts': 1970760, 'single': 1868467, 'multiple': 102293, 'physical_flights': 2079280, 'max_physical_flights': 8, 'selected': 1950951, 'resampled': 1950951, 'rows': 1093219851, 'unresolved': 24032, 'contains_mvt': 1263010, 'starts_after_mvt': 686023, 'ends_before_mvt': 1918, 'elapsed_sec': 2986.8, 'mvts_per_sec': 661.23, 'rss_gib': 2.1533203125}

{'buckets': '432/512', 'mvts': 1979565, 'assigned_mvts': 1975329, 'single': 1872794, 'multiple': 102535, 'physical_flights': 2084103, 'max_physical_flights': 8, 'selected': 1955477, 'resampled': 1955477, 'rows': 1095737914, 'unresolved': 24088, 'contains_mvt': 1265937, 'starts_after_mvt': 687612, 'ends_before_mvt': 1928, 'elapsed_sec': 2986.9, 'mvts_per_sec': 662.75, 'rss_gib': 2.1533203125}

{'buckets': '433/512', 'mvts': 1984140, 'assigned_mvts': 1979888, 'single': 1877113, 'multiple': 102775, 'physical_flights': 2088919, 'max_physical_flights': 8, 'selected': 1959991, 'resampled': 1959991, 'rows': 1098308979, 'unresolved': 24149, 'contains_mvt': 1268896, 'starts_after_mvt': 689164, 'ends_before_mvt': 1931, 'elapsed_sec': 2988.1, 'mvts_per_sec': 664.02, 'rss_gib': 2.1533203125}

{'buckets': '434/512', 'mvts': 1988757, 'assigned_mvts': 1984492, 'single': 1881465, 'multiple': 103027, 'physical_flights': 2093788, 'max_physical_flights': 8, 'selected': 1964552, 'resampled': 1964552, 'rows': 1100899760, 'unresolved': 24205, 'contains_mvt': 1271894, 'starts_after_mvt': 690722, 'ends_before_mvt': 1936, 'elapsed_sec': 2996.9, 'mvts_per_sec': 663.61, 'rss_gib': 2.1533203125}

{'buckets': '435/512', 'mvts': 1993313, 'assigned_mvts': 1989034, 'single': 1885769, 'multiple': 103265, 'physical_flights': 2098574, 'max_physical_flights': 8, 'selected': 1969039, 'resampled': 1969039, 'rows': 1103452202, 'unresolved': 24274, 'contains_mvt': 1274790, 'starts_after_mvt': 692306, 'ends_before_mvt': 1943, 'elapsed_sec': 3004.4, 'mvts_per_sec': 663.45, 'rss_gib': 2.1533203125}

{'buckets': '436/512', 'mvts': 1997861, 'assigned_mvts': 1993575, 'single': 1890091, 'multiple': 103484, 'physical_flights': 2103349, 'max_physical_flights': 8, 'selected': 1973523, 'resampled': 1973523, 'rows': 1105986210, 'unresolved': 24338, 'contains_mvt': 1277701, 'starts_after_mvt': 693873, 'ends_before_mvt': 1949, 'elapsed_sec': 3009.8, 'mvts_per_sec': 663.79, 'rss_gib': 2.1533203125}

{'buckets': '437/512', 'mvts': 2002452, 'assigned_mvts': 1998155, 'single': 1894439, 'multiple': 103716, 'physical_flights': 2108176, 'max_physical_flights': 8, 'selected': 1978056, 'resampled': 1978056, 'rows': 1108521661, 'unresolved': 24396, 'contains_mvt': 1280582, 'starts_after_mvt': 695518, 'ends_before_mvt': 1956, 'elapsed_sec': 3020.1, 'mvts_per_sec': 663.04, 'rss_gib': 2.1533203125}

{'buckets': '438/512', 'mvts': 2007073, 'assigned_mvts': 2002768, 'single': 1898803, 'multiple': 103965, 'physical_flights': 2113058, 'max_physical_flights': 8, 'selected': 1982608, 'resampled': 1982608, 'rows': 1111115902, 'unresolved': 24465, 'contains_mvt': 1283493, 'starts_after_mvt': 697151, 'ends_before_mvt': 1964, 'elapsed_sec': 3026.0, 'mvts_per_sec': 663.27, 'rss_gib': 2.1533203125}

{'buckets': '439/512', 'mvts': 2011687, 'assigned_mvts': 2007370, 'single': 1903178, 'multiple': 104192, 'physical_flights': 2117896, 'max_physical_flights': 8, 'selected': 1987158, 'resampled': 1987158, 'rows': 1113679729, 'unresolved': 24529, 'contains_mvt': 1286454, 'starts_after_mvt': 698735, 'ends_before_mvt': 1969, 'elapsed_sec': 3028.4, 'mvts_per_sec': 664.28, 'rss_gib': 2.1533203125}

{'buckets': '440/512', 'mvts': 2016232, 'assigned_mvts': 2011910, 'single': 1907453, 'multiple': 104457, 'physical_flights': 2122716, 'max_physical_flights': 8, 'selected': 1991639, 'resampled': 1991639, 'rows': 1116129149, 'unresolved': 24593, 'contains_mvt': 1289335, 'starts_after_mvt': 700332, 'ends_before_mvt': 1972, 'elapsed_sec': 3039.4, 'mvts_per_sec': 663.35, 'rss_gib': 2.1533203125}

{'buckets': '441/512', 'mvts': 2020772, 'assigned_mvts': 2016442, 'single': 1911768, 'multiple': 104674, 'physical_flights': 2127484, 'max_physical_flights': 8, 'selected': 1996123, 'resampled': 1996123, 'rows': 1118646858, 'unresolved': 24649, 'contains_mvt': 1292286, 'starts_after_mvt': 701862, 'ends_before_mvt': 1975, 'elapsed_sec': 3045.1, 'mvts_per_sec': 663.61, 'rss_gib': 2.1533203125}

{'buckets': '442/512', 'mvts': 2025295, 'assigned_mvts': 2020952, 'single': 1916026, 'multiple': 104926, 'physical_flights': 2132265, 'max_physical_flights': 8, 'selected': 2000592, 'resampled': 2000592, 'rows': 1121159851, 'unresolved': 24703, 'contains_mvt': 1295183, 'starts_after_mvt': 703427, 'ends_before_mvt': 1982, 'elapsed_sec': 3069.8, 'mvts_per_sec': 659.76, 'rss_gib': 2.1533203125}

{'buckets': '443/512', 'mvts': 2029901, 'assigned_mvts': 2025553, 'single': 1920392, 'multiple': 105161, 'physical_flights': 2137104, 'max_physical_flights': 8, 'selected': 2005148, 'resampled': 2005148, 'rows': 1123660329, 'unresolved': 24753, 'contains_mvt': 1298108, 'starts_after_mvt': 705050, 'ends_before_mvt': 1990, 'elapsed_sec': 3072.7, 'mvts_per_sec': 660.63, 'rss_gib': 2.1533203125}

{'buckets': '444/512', 'mvts': 2034597, 'assigned_mvts': 2030237, 'single': 1924840, 'multiple': 105397, 'physical_flights': 2142036, 'max_physical_flights': 8, 'selected': 2009795, 'resampled': 2009795, 'rows': 1126254881, 'unresolved': 24802, 'contains_mvt': 1301095, 'starts_after_mvt': 706706, 'ends_before_mvt': 1994, 'elapsed_sec': 3079.9, 'mvts_per_sec': 660.61, 'rss_gib': 2.1533203125}

{'buckets': '445/512', 'mvts': 2039239, 'assigned_mvts': 2034873, 'single': 1929255, 'multiple': 105618, 'physical_flights': 2146899, 'max_physical_flights': 8, 'selected': 2014386, 'resampled': 2014386, 'rows': 1128825181, 'unresolved': 24853, 'contains_mvt': 1304082, 'starts_after_mvt': 708308, 'ends_before_mvt': 1996, 'elapsed_sec': 3084.8, 'mvts_per_sec': 661.05, 'rss_gib': 2.1533203125}

{'buckets': '446/512', 'mvts': 2043833, 'assigned_mvts': 2039456, 'single': 1933607, 'multiple': 105849, 'physical_flights': 2151728, 'max_physical_flights': 8, 'selected': 2018932, 'resampled': 2018932, 'rows': 1131343992, 'unresolved': 24901, 'contains_mvt': 1307022, 'starts_after_mvt': 709908, 'ends_before_mvt': 2002, 'elapsed_sec': 3089.6, 'mvts_per_sec': 661.52, 'rss_gib': 2.1533203125}

{'buckets': '447/512', 'mvts': 2048441, 'assigned_mvts': 2044054, 'single': 1937940, 'multiple': 106114, 'physical_flights': 2156603, 'max_physical_flights': 8, 'selected': 2023481, 'resampled': 2023481, 'rows': 1133906772, 'unresolved': 24960, 'contains_mvt': 1309932, 'starts_after_mvt': 711538, 'ends_before_mvt': 2011, 'elapsed_sec': 3091.6, 'mvts_per_sec': 662.57, 'rss_gib': 2.1533203125}

{'buckets': '448/512', 'mvts': 2052899, 'assigned_mvts': 2048502, 'single': 1942163, 'multiple': 106339, 'physical_flights': 2161289, 'max_physical_flights': 8, 'selected': 2027889, 'resampled': 2027889, 'rows': 1136386490, 'unresolved': 25010, 'contains_mvt': 1312822, 'starts_after_mvt': 713051, 'ends_before_mvt': 2016, 'elapsed_sec': 3096.9, 'mvts_per_sec': 662.9, 'rss_gib': 2.1533203125}

{'buckets': '449/512', 'mvts': 2057481, 'assigned_mvts': 2053076, 'single': 1946482, 'multiple': 106594, 'physical_flights': 2166145, 'max_physical_flights': 8, 'selected': 2032413, 'resampled': 2032413, 'rows': 1138956284, 'unresolved': 25068, 'contains_mvt': 1315777, 'starts_after_mvt': 714618, 'ends_before_mvt': 2018, 'elapsed_sec': 3099.1, 'mvts_per_sec': 663.9, 'rss_gib': 2.1533203125}

{'buckets': '450/512', 'mvts': 2062067, 'assigned_mvts': 2057650, 'single': 1950835, 'multiple': 106815, 'physical_flights': 2170957, 'max_physical_flights': 8, 'selected': 2036937, 'resampled': 2036937, 'rows': 1141508977, 'unresolved': 25130, 'contains_mvt': 1318726, 'starts_after_mvt': 716188, 'ends_before_mvt': 2023, 'elapsed_sec': 3105.5, 'mvts_per_sec': 664.01, 'rss_gib': 2.1533203125}

{'buckets': '451/512', 'mvts': 2066628, 'assigned_mvts': 2062200, 'single': 1955166, 'multiple': 107034, 'physical_flights': 2175743, 'max_physical_flights': 8, 'selected': 2041433, 'resampled': 2041433, 'rows': 1144040189, 'unresolved': 25195, 'contains_mvt': 1321673, 'starts_after_mvt': 717728, 'ends_before_mvt': 2032, 'elapsed_sec': 3108.5, 'mvts_per_sec': 664.84, 'rss_gib': 2.1533203125}

{'buckets': '452/512', 'mvts': 2071239, 'assigned_mvts': 2066795, 'single': 1959536, 'multiple': 107259, 'physical_flights': 2180578, 'max_physical_flights': 8, 'selected': 2045987, 'resampled': 2045987, 'rows': 1146626677, 'unresolved': 25252, 'contains_mvt': 1324622, 'starts_after_mvt': 719326, 'ends_before_mvt': 2039, 'elapsed_sec': 3108.8, 'mvts_per_sec': 666.25, 'rss_gib': 2.1533203125}

{'buckets': '453/512', 'mvts': 2075837, 'assigned_mvts': 2071387, 'single': 1963890, 'multiple': 107497, 'physical_flights': 2185421, 'max_physical_flights': 8, 'selected': 2050534, 'resampled': 2050534, 'rows': 1149120886, 'unresolved': 25303, 'contains_mvt': 1327574, 'starts_after_mvt': 720917, 'ends_before_mvt': 2043, 'elapsed_sec': 3111.1, 'mvts_per_sec': 667.25, 'rss_gib': 2.1533203125}

{'buckets': '454/512', 'mvts': 2080567, 'assigned_mvts': 2076102, 'single': 1968348, 'multiple': 107754, 'physical_flights': 2190402, 'max_physical_flights': 8, 'selected': 2055198, 'resampled': 2055198, 'rows': 1151769106, 'unresolved': 25369, 'contains_mvt': 1330587, 'starts_after_mvt': 722566, 'ends_before_mvt': 2045, 'elapsed_sec': 3131.8, 'mvts_per_sec': 664.34, 'rss_gib': 2.1533203125}

{'buckets': '455/512', 'mvts': 2085195, 'assigned_mvts': 2080723, 'single': 1972735, 'multiple': 107988, 'physical_flights': 2195269, 'max_physical_flights': 8, 'selected': 2059758, 'resampled': 2059758, 'rows': 1154313463, 'unresolved': 25437, 'contains_mvt': 1333533, 'starts_after_mvt': 724174, 'ends_before_mvt': 2051, 'elapsed_sec': 3131.8, 'mvts_per_sec': 665.81, 'rss_gib': 2.1533203125}

{'buckets': '456/512', 'mvts': 2089798, 'assigned_mvts': 2085316, 'single': 1977096, 'multiple': 108220, 'physical_flights': 2200103, 'max_physical_flights': 8, 'selected': 2064308, 'resampled': 2064308, 'rows': 1156900275, 'unresolved': 25490, 'contains_mvt': 1336485, 'starts_after_mvt': 725768, 'ends_before_mvt': 2055, 'elapsed_sec': 3142.3, 'mvts_per_sec': 665.06, 'rss_gib': 2.1533203125}

{'buckets': '457/512', 'mvts': 2094352, 'assigned_mvts': 2089861, 'single': 1981408, 'multiple': 108453, 'physical_flights': 2204889, 'max_physical_flights': 8, 'selected': 2068809, 'resampled': 2068809, 'rows': 1159380854, 'unresolved': 25543, 'contains_mvt': 1339410, 'starts_after_mvt': 727339, 'ends_before_mvt': 2060, 'elapsed_sec': 3162.9, 'mvts_per_sec': 662.17, 'rss_gib': 2.1533203125}

{'buckets': '458/512', 'mvts': 2098880, 'assigned_mvts': 2094383, 'single': 1985692, 'multiple': 108691, 'physical_flights': 2209658, 'max_physical_flights': 8, 'selected': 2073271, 'resampled': 2073271, 'rows': 1161870597, 'unresolved': 25609, 'contains_mvt': 1342337, 'starts_after_mvt': 728872, 'ends_before_mvt': 2062, 'elapsed_sec': 3164.0, 'mvts_per_sec': 663.36, 'rss_gib': 2.1533203125}

{'buckets': '459/512', 'mvts': 2103515, 'assigned_mvts': 2099007, 'single': 1990103, 'multiple': 108904, 'physical_flights': 2214511, 'max_physical_flights': 8, 'selected': 2077848, 'resampled': 2077848, 'rows': 1164446456, 'unresolved': 25667, 'contains_mvt': 1345286, 'starts_after_mvt': 730493, 'ends_before_mvt': 2069, 'elapsed_sec': 3176.7, 'mvts_per_sec': 662.17, 'rss_gib': 2.1533203125}

{'buckets': '460/512', 'mvts': 2108037, 'assigned_mvts': 2103516, 'single': 1994388, 'multiple': 109128, 'physical_flights': 2219258, 'max_physical_flights': 8, 'selected': 2082318, 'resampled': 2082318, 'rows': 1166898085, 'unresolved': 25719, 'contains_mvt': 1348153, 'starts_after_mvt': 732093, 'ends_before_mvt': 2072, 'elapsed_sec': 3182.5, 'mvts_per_sec': 662.39, 'rss_gib': 2.1533203125}

{'buckets': '461/512', 'mvts': 2112594, 'assigned_mvts': 2108067, 'single': 1998713, 'multiple': 109354, 'physical_flights': 2224048, 'max_physical_flights': 8, 'selected': 2086832, 'resampled': 2086832, 'rows': 1169502552, 'unresolved': 25762, 'contains_mvt': 1351096, 'starts_after_mvt': 733661, 'ends_before_mvt': 2075, 'elapsed_sec': 3187.8, 'mvts_per_sec': 662.72, 'rss_gib': 2.1533203125}

{'buckets': '462/512', 'mvts': 2117103, 'assigned_mvts': 2112556, 'single': 2002973, 'multiple': 109583, 'physical_flights': 2228778, 'max_physical_flights': 8, 'selected': 2091277, 'resampled': 2091277, 'rows': 1171977117, 'unresolved': 25826, 'contains_mvt': 1353987, 'starts_after_mvt': 735209, 'ends_before_mvt': 2081, 'elapsed_sec': 3188.6, 'mvts_per_sec': 663.96, 'rss_gib': 2.1533203125}

{'buckets': '463/512', 'mvts': 2121654, 'assigned_mvts': 2117092, 'single': 2007278, 'multiple': 109814, 'physical_flights': 2233567, 'max_physical_flights': 8, 'selected': 2095772, 'resampled': 2095772, 'rows': 1174507905, 'unresolved': 25882, 'contains_mvt': 1356901, 'starts_after_mvt': 736788, 'ends_before_mvt': 2083, 'elapsed_sec': 3189.0, 'mvts_per_sec': 665.3, 'rss_gib': 2.1533203125}

{'buckets': '464/512', 'mvts': 2126197, 'assigned_mvts': 2121627, 'single': 2011591, 'multiple': 110036, 'physical_flights': 2238345, 'max_physical_flights': 8, 'selected': 2100256, 'resampled': 2100256, 'rows': 1177061202, 'unresolved': 25941, 'contains_mvt': 1359797, 'starts_after_mvt': 738373, 'ends_before_mvt': 2086, 'elapsed_sec': 3194.7, 'mvts_per_sec': 665.53, 'rss_gib': 2.1533203125}

{'buckets': '465/512', 'mvts': 2130908, 'assigned_mvts': 2126332, 'single': 2016057, 'multiple': 110275, 'physical_flights': 2243300, 'max_physical_flights': 8, 'selected': 2104912, 'resampled': 2104912, 'rows': 1179723053, 'unresolved': 25996, 'contains_mvt': 1362827, 'starts_after_mvt': 739992, 'ends_before_mvt': 2093, 'elapsed_sec': 3204.6, 'mvts_per_sec': 664.95, 'rss_gib': 2.1533203125}

{'buckets': '466/512', 'mvts': 2135591, 'assigned_mvts': 2130999, 'single': 2020515, 'multiple': 110484, 'physical_flights': 2248191, 'max_physical_flights': 8, 'selected': 2109522, 'resampled': 2109522, 'rows': 1182272215, 'unresolved': 26069, 'contains_mvt': 1365802, 'starts_after_mvt': 741623, 'ends_before_mvt': 2097, 'elapsed_sec': 3211.3, 'mvts_per_sec': 665.02, 'rss_gib': 2.1533203125}

{'buckets': '467/512', 'mvts': 2140133, 'assigned_mvts': 2135534, 'single': 2024815, 'multiple': 110719, 'physical_flights': 2252974, 'max_physical_flights': 8, 'selected': 2114008, 'resampled': 2114008, 'rows': 1184672359, 'unresolved': 26125, 'contains_mvt': 1368607, 'starts_after_mvt': 743301, 'ends_before_mvt': 2100, 'elapsed_sec': 3221.5, 'mvts_per_sec': 664.33, 'rss_gib': 2.1533203125}

{'buckets': '468/512', 'mvts': 2144663, 'assigned_mvts': 2140054, 'single': 2029093, 'multiple': 110961, 'physical_flights': 2257745, 'max_physical_flights': 8, 'selected': 2118486, 'resampled': 2118486, 'rows': 1187152760, 'unresolved': 26177, 'contains_mvt': 1371522, 'starts_after_mvt': 744857, 'ends_before_mvt': 2107, 'elapsed_sec': 3222.1, 'mvts_per_sec': 665.61, 'rss_gib': 2.1533203125}

{'buckets': '469/512', 'mvts': 2149158, 'assigned_mvts': 2144541, 'single': 2033331, 'multiple': 111210, 'physical_flights': 2262498, 'max_physical_flights': 8, 'selected': 2122916, 'resampled': 2122916, 'rows': 1189638473, 'unresolved': 26242, 'contains_mvt': 1374400, 'starts_after_mvt': 746406, 'ends_before_mvt': 2110, 'elapsed_sec': 3234.1, 'mvts_per_sec': 664.53, 'rss_gib': 2.1533203125}

{'buckets': '470/512', 'mvts': 2153752, 'assigned_mvts': 2149126, 'single': 2037660, 'multiple': 111466, 'physical_flights': 2267350, 'max_physical_flights': 8, 'selected': 2127450, 'resampled': 2127450, 'rows': 1192193429, 'unresolved': 26302, 'contains_mvt': 1377349, 'starts_after_mvt': 747988, 'ends_before_mvt': 2113, 'elapsed_sec': 3247.4, 'mvts_per_sec': 663.23, 'rss_gib': 2.1533203125}

{'buckets': '471/512', 'mvts': 2158339, 'assigned_mvts': 2153703, 'single': 2041978, 'multiple': 111725, 'physical_flights': 2272200, 'max_physical_flights': 8, 'selected': 2131991, 'resampled': 2131991, 'rows': 1194821207, 'unresolved': 26348, 'contains_mvt': 1380318, 'starts_after_mvt': 749555, 'ends_before_mvt': 2118, 'elapsed_sec': 3261.0, 'mvts_per_sec': 661.86, 'rss_gib': 2.1533203125}

{'buckets': '472/512', 'mvts': 2162851, 'assigned_mvts': 2158202, 'single': 2046234, 'multiple': 111968, 'physical_flights': 2276964, 'max_physical_flights': 8, 'selected': 2136452, 'resampled': 2136452, 'rows': 1197355026, 'unresolved': 26399, 'contains_mvt': 1383201, 'starts_after_mvt': 751130, 'ends_before_mvt': 2121, 'elapsed_sec': 3267.6, 'mvts_per_sec': 661.91, 'rss_gib': 2.1533203125}

{'buckets': '473/512', 'mvts': 2167532, 'assigned_mvts': 2162873, 'single': 2050686, 'multiple': 112187, 'physical_flights': 2281868, 'max_physical_flights': 8, 'selected': 2141073, 'resampled': 2141073, 'rows': 1199997235, 'unresolved': 26459, 'contains_mvt': 1386212, 'starts_after_mvt': 752738, 'ends_before_mvt': 2123, 'elapsed_sec': 3272.4, 'mvts_per_sec': 662.37, 'rss_gib': 2.1533203125}

{'buckets': '474/512', 'mvts': 2172230, 'assigned_mvts': 2167565, 'single': 2055130, 'multiple': 112435, 'physical_flights': 2286818, 'max_physical_flights': 8, 'selected': 2145707, 'resampled': 2145707, 'rows': 1202580049, 'unresolved': 26523, 'contains_mvt': 1389231, 'starts_after_mvt': 754349, 'ends_before_mvt': 2127, 'elapsed_sec': 3277.8, 'mvts_per_sec': 662.72, 'rss_gib': 2.1533203125}

{'buckets': '475/512', 'mvts': 2176804, 'assigned_mvts': 2172130, 'single': 2059479, 'multiple': 112651, 'physical_flights': 2291617, 'max_physical_flights': 8, 'selected': 2150224, 'resampled': 2150224, 'rows': 1205110464, 'unresolved': 26580, 'contains_mvt': 1392153, 'starts_after_mvt': 755941, 'ends_before_mvt': 2130, 'elapsed_sec': 3281.8, 'mvts_per_sec': 663.29, 'rss_gib': 2.1533203125}

{'buckets': '476/512', 'mvts': 2181348, 'assigned_mvts': 2176667, 'single': 2063784, 'multiple': 112883, 'physical_flights': 2296409, 'max_physical_flights': 8, 'selected': 2154721, 'resampled': 2154721, 'rows': 1207614769, 'unresolved': 26627, 'contains_mvt': 1395067, 'starts_after_mvt': 757523, 'ends_before_mvt': 2131, 'elapsed_sec': 3291.0, 'mvts_per_sec': 662.83, 'rss_gib': 2.1533203125}

{'buckets': '477/512', 'mvts': 2185925, 'assigned_mvts': 2181238, 'single': 2068123, 'multiple': 113115, 'physical_flights': 2301226, 'max_physical_flights': 8, 'selected': 2159248, 'resampled': 2159248, 'rows': 1210103867, 'unresolved': 26677, 'contains_mvt': 1397982, 'starts_after_mvt': 759132, 'ends_before_mvt': 2134, 'elapsed_sec': 3291.8, 'mvts_per_sec': 664.06, 'rss_gib': 2.1533203125}

{'buckets': '478/512', 'mvts': 2190527, 'assigned_mvts': 2185826, 'single': 2072483, 'multiple': 113343, 'physical_flights': 2306054, 'max_physical_flights': 8, 'selected': 2163794, 'resampled': 2163794, 'rows': 1212684496, 'unresolved': 26733, 'contains_mvt': 1400934, 'starts_after_mvt': 760720, 'ends_before_mvt': 2140, 'elapsed_sec': 3292.0, 'mvts_per_sec': 665.41, 'rss_gib': 2.1533203125}

{'buckets': '479/512', 'mvts': 2194965, 'assigned_mvts': 2190258, 'single': 2076679, 'multiple': 113579, 'physical_flights': 2310733, 'max_physical_flights': 8, 'selected': 2168181, 'resampled': 2168181, 'rows': 1215126659, 'unresolved': 26784, 'contains_mvt': 1403746, 'starts_after_mvt': 762294, 'ends_before_mvt': 2141, 'elapsed_sec': 3308.4, 'mvts_per_sec': 663.46, 'rss_gib': 2.1533203125}

{'buckets': '480/512', 'mvts': 2199709, 'assigned_mvts': 2194990, 'single': 2081175, 'multiple': 113815, 'physical_flights': 2315717, 'max_physical_flights': 8, 'selected': 2172865, 'resampled': 2172865, 'rows': 1217735254, 'unresolved': 26844, 'contains_mvt': 1406798, 'starts_after_mvt': 763924, 'ends_before_mvt': 2143, 'elapsed_sec': 3313.4, 'mvts_per_sec': 663.88, 'rss_gib': 2.1533203125}

{'buckets': '481/512', 'mvts': 2204256, 'assigned_mvts': 2199527, 'single': 2085464, 'multiple': 114063, 'physical_flights': 2320528, 'max_physical_flights': 8, 'selected': 2177357, 'resampled': 2177357, 'rows': 1220251117, 'unresolved': 26899, 'contains_mvt': 1409743, 'starts_after_mvt': 765469, 'ends_before_mvt': 2145, 'elapsed_sec': 3315.2, 'mvts_per_sec': 664.89, 'rss_gib': 2.1533203125}

{'buckets': '482/512', 'mvts': 2208837, 'assigned_mvts': 2204088, 'single': 2089770, 'multiple': 114318, 'physical_flights': 2325357, 'max_physical_flights': 8, 'selected': 2181870, 'resampled': 2181870, 'rows': 1222828996, 'unresolved': 26967, 'contains_mvt': 1412706, 'starts_after_mvt': 767012, 'ends_before_mvt': 2152, 'elapsed_sec': 3321.0, 'mvts_per_sec': 665.1, 'rss_gib': 2.1533203125}

{'buckets': '483/512', 'mvts': 2213529, 'assigned_mvts': 2208771, 'single': 2094229, 'multiple': 114542, 'physical_flights': 2330277, 'max_physical_flights': 8, 'selected': 2186506, 'resampled': 2186506, 'rows': 1225410495, 'unresolved': 27023, 'contains_mvt': 1415683, 'starts_after_mvt': 768665, 'ends_before_mvt': 2158, 'elapsed_sec': 3321.7, 'mvts_per_sec': 666.39, 'rss_gib': 2.1533203125}

{'buckets': '484/512', 'mvts': 2218075, 'assigned_mvts': 2213304, 'single': 2098527, 'multiple': 114777, 'physical_flights': 2335056, 'max_physical_flights': 8, 'selected': 2190991, 'resampled': 2190991, 'rows': 1227897451, 'unresolved': 27084, 'contains_mvt': 1418601, 'starts_after_mvt': 770231, 'ends_before_mvt': 2159, 'elapsed_sec': 3332.0, 'mvts_per_sec': 665.69, 'rss_gib': 2.1533203125}

{'buckets': '485/512', 'mvts': 2222661, 'assigned_mvts': 2217879, 'single': 2102870, 'multiple': 115009, 'physical_flights': 2339876, 'max_physical_flights': 8, 'selected': 2195512, 'resampled': 2195512, 'rows': 1230379261, 'unresolved': 27149, 'contains_mvt': 1421509, 'starts_after_mvt': 771844, 'ends_before_mvt': 2159, 'elapsed_sec': 3334.3, 'mvts_per_sec': 666.61, 'rss_gib': 2.1533203125}

{'buckets': '486/512', 'mvts': 2227312, 'assigned_mvts': 2222515, 'single': 2107296, 'multiple': 115219, 'physical_flights': 2344734, 'max_physical_flights': 8, 'selected': 2200099, 'resampled': 2200099, 'rows': 1233022534, 'unresolved': 27213, 'contains_mvt': 1424521, 'starts_after_mvt': 773416, 'ends_before_mvt': 2162, 'elapsed_sec': 3352.9, 'mvts_per_sec': 664.3, 'rss_gib': 2.1533203125}

{'buckets': '487/512', 'mvts': 2231991, 'assigned_mvts': 2227183, 'single': 2111717, 'multiple': 115466, 'physical_flights': 2349664, 'max_physical_flights': 8, 'selected': 2204715, 'resampled': 2204715, 'rows': 1235604064, 'unresolved': 27276, 'contains_mvt': 1427542, 'starts_after_mvt': 775004, 'ends_before_mvt': 2169, 'elapsed_sec': 3357.7, 'mvts_per_sec': 664.74, 'rss_gib': 2.1533203125}

{'buckets': '488/512', 'mvts': 2236406, 'assigned_mvts': 2231587, 'single': 2115901, 'multiple': 115686, 'physical_flights': 2354292, 'max_physical_flights': 8, 'selected': 2209080, 'resampled': 2209080, 'rows': 1238085766, 'unresolved': 27326, 'contains_mvt': 1430365, 'starts_after_mvt': 776542, 'ends_before_mvt': 2173, 'elapsed_sec': 3364.7, 'mvts_per_sec': 664.67, 'rss_gib': 2.1533203125}

{'buckets': '489/512', 'mvts': 2241081, 'assigned_mvts': 2236248, 'single': 2120318, 'multiple': 115930, 'physical_flights': 2359220, 'max_physical_flights': 8, 'selected': 2213688, 'resampled': 2213688, 'rows': 1240627592, 'unresolved': 27393, 'contains_mvt': 1433319, 'starts_after_mvt': 778192, 'ends_before_mvt': 2177, 'elapsed_sec': 3365.1, 'mvts_per_sec': 665.98, 'rss_gib': 2.1533203125}

{'buckets': '490/512', 'mvts': 2245656, 'assigned_mvts': 2240813, 'single': 2124643, 'multiple': 116170, 'physical_flights': 2364041, 'max_physical_flights': 8, 'selected': 2218204, 'resampled': 2218204, 'rows': 1243159301, 'unresolved': 27452, 'contains_mvt': 1436273, 'starts_after_mvt': 779752, 'ends_before_mvt': 2179, 'elapsed_sec': 3371.4, 'mvts_per_sec': 666.09, 'rss_gib': 2.1533203125}

{'buckets': '491/512', 'mvts': 2250288, 'assigned_mvts': 2245436, 'single': 2129035, 'multiple': 116401, 'physical_flights': 2368907, 'max_physical_flights': 8, 'selected': 2222778, 'resampled': 2222778, 'rows': 1245713259, 'unresolved': 27510, 'contains_mvt': 1439256, 'starts_after_mvt': 781338, 'ends_before_mvt': 2184, 'elapsed_sec': 3385.4, 'mvts_per_sec': 664.7, 'rss_gib': 2.1533203125}

{'buckets': '492/512', 'mvts': 2254931, 'assigned_mvts': 2250068, 'single': 2133431, 'multiple': 116637, 'physical_flights': 2373794, 'max_physical_flights': 8, 'selected': 2227356, 'resampled': 2227356, 'rows': 1248325196, 'unresolved': 27575, 'contains_mvt': 1442241, 'starts_after_mvt': 782927, 'ends_before_mvt': 2188, 'elapsed_sec': 3390.6, 'mvts_per_sec': 665.05, 'rss_gib': 2.1533203125}

{'buckets': '493/512', 'mvts': 2259423, 'assigned_mvts': 2254552, 'single': 2137695, 'multiple': 116857, 'physical_flights': 2378518, 'max_physical_flights': 8, 'selected': 2231800, 'resampled': 2231800, 'rows': 1250778419, 'unresolved': 27623, 'contains_mvt': 1445135, 'starts_after_mvt': 784470, 'ends_before_mvt': 2195, 'elapsed_sec': 3392.1, 'mvts_per_sec': 666.08, 'rss_gib': 2.1533203125}

{'buckets': '494/512', 'mvts': 2264035, 'assigned_mvts': 2259156, 'single': 2142078, 'multiple': 117078, 'physical_flights': 2383364, 'max_physical_flights': 8, 'selected': 2236356, 'resampled': 2236356, 'rows': 1253334341, 'unresolved': 27679, 'contains_mvt': 1448072, 'starts_after_mvt': 786080, 'ends_before_mvt': 2204, 'elapsed_sec': 3396.0, 'mvts_per_sec': 666.68, 'rss_gib': 2.1533203125}

{'buckets': '495/512', 'mvts': 2268543, 'assigned_mvts': 2263653, 'single': 2146355, 'multiple': 117298, 'physical_flights': 2388088, 'max_physical_flights': 8, 'selected': 2240810, 'resampled': 2240810, 'rows': 1255832327, 'unresolved': 27733, 'contains_mvt': 1450982, 'starts_after_mvt': 787619, 'ends_before_mvt': 2209, 'elapsed_sec': 3399.6, 'mvts_per_sec': 667.3, 'rss_gib': 2.1533203125}

{'buckets': '496/512', 'mvts': 2273178, 'assigned_mvts': 2268275, 'single': 2150720, 'multiple': 117555, 'physical_flights': 2392979, 'max_physical_flights': 8, 'selected': 2245394, 'resampled': 2245394, 'rows': 1258416329, 'unresolved': 27784, 'contains_mvt': 1453980, 'starts_after_mvt': 789200, 'ends_before_mvt': 2214, 'elapsed_sec': 3399.6, 'mvts_per_sec': 668.67, 'rss_gib': 2.1533203125}

{'buckets': '497/512', 'mvts': 2277734, 'assigned_mvts': 2272818, 'single': 2155051, 'multiple': 117767, 'physical_flights': 2397749, 'max_physical_flights': 8, 'selected': 2249890, 'resampled': 2249890, 'rows': 1260909674, 'unresolved': 27844, 'contains_mvt': 1456884, 'starts_after_mvt': 790791, 'ends_before_mvt': 2215, 'elapsed_sec': 3409.5, 'mvts_per_sec': 668.06, 'rss_gib': 2.1533203125}

{'buckets': '498/512', 'mvts': 2282507, 'assigned_mvts': 2277580, 'single': 2159583, 'multiple': 117997, 'physical_flights': 2402753, 'max_physical_flights': 8, 'selected': 2254615, 'resampled': 2254615, 'rows': 1263556324, 'unresolved': 27892, 'contains_mvt': 1459950, 'starts_after_mvt': 792445, 'ends_before_mvt': 2220, 'elapsed_sec': 3416.1, 'mvts_per_sec': 668.17, 'rss_gib': 2.1533203125}

{'buckets': '499/512', 'mvts': 2286979, 'assigned_mvts': 2282043, 'single': 2163807, 'multiple': 118236, 'physical_flights': 2407477, 'max_physical_flights': 8, 'selected': 2259035, 'resampled': 2259035, 'rows': 1266072447, 'unresolved': 27944, 'contains_mvt': 1462828, 'starts_after_mvt': 793984, 'ends_before_mvt': 2223, 'elapsed_sec': 3419.4, 'mvts_per_sec': 668.82, 'rss_gib': 2.1533203125}

{'buckets': '500/512', 'mvts': 2291473, 'assigned_mvts': 2286525, 'single': 2168073, 'multiple': 118452, 'physical_flights': 2412190, 'max_physical_flights': 8, 'selected': 2263475, 'resampled': 2263475, 'rows': 1268518963, 'unresolved': 27998, 'contains_mvt': 1465634, 'starts_after_mvt': 795616, 'ends_before_mvt': 2225, 'elapsed_sec': 3422.8, 'mvts_per_sec': 669.48, 'rss_gib': 2.1533203125}

{'buckets': '501/512', 'mvts': 2295950, 'assigned_mvts': 2290990, 'single': 2172297, 'multiple': 118693, 'physical_flights': 2416906, 'max_physical_flights': 8, 'selected': 2267890, 'resampled': 2267890, 'rows': 1270936544, 'unresolved': 28060, 'contains_mvt': 1468427, 'starts_after_mvt': 797232, 'ends_before_mvt': 2231, 'elapsed_sec': 3425.6, 'mvts_per_sec': 670.23, 'rss_gib': 2.1533203125}

{'buckets': '502/512', 'mvts': 2300529, 'assigned_mvts': 2295561, 'single': 2176631, 'multiple': 118930, 'physical_flights': 2421732, 'max_physical_flights': 8, 'selected': 2272410, 'resampled': 2272410, 'rows': 1273461069, 'unresolved': 28119, 'contains_mvt': 1471306, 'starts_after_mvt': 798864, 'ends_before_mvt': 2240, 'elapsed_sec': 3427.9, 'mvts_per_sec': 671.12, 'rss_gib': 2.1533203125}

{'buckets': '503/512', 'mvts': 2305099, 'assigned_mvts': 2300124, 'single': 2180934, 'multiple': 119190, 'physical_flights': 2426568, 'max_physical_flights': 8, 'selected': 2276925, 'resampled': 2276925, 'rows': 1276029009, 'unresolved': 28174, 'contains_mvt': 1474232, 'starts_after_mvt': 800447, 'ends_before_mvt': 2246, 'elapsed_sec': 3431.1, 'mvts_per_sec': 671.82, 'rss_gib': 2.1533203125}

{'buckets': '504/512', 'mvts': 2309695, 'assigned_mvts': 2304717, 'single': 2185314, 'multiple': 119403, 'physical_flights': 2431381, 'max_physical_flights': 8, 'selected': 2281478, 'resampled': 2281478, 'rows': 1278561741, 'unresolved': 28217, 'contains_mvt': 1477141, 'starts_after_mvt': 802087, 'ends_before_mvt': 2250, 'elapsed_sec': 3435.2, 'mvts_per_sec': 672.37, 'rss_gib': 2.1533203125}

{'buckets': '505/512', 'mvts': 2314192, 'assigned_mvts': 2309209, 'single': 2189575, 'multiple': 119634, 'physical_flights': 2436119, 'max_physical_flights': 8, 'selected': 2285924, 'resampled': 2285924, 'rows': 1281046761, 'unresolved': 28268, 'contains_mvt': 1480055, 'starts_after_mvt': 803616, 'ends_before_mvt': 2253, 'elapsed_sec': 3438.5, 'mvts_per_sec': 673.01, 'rss_gib': 2.1533203125}

{'buckets': '506/512', 'mvts': 2318731, 'assigned_mvts': 2313737, 'single': 2193847, 'multiple': 119890, 'physical_flights': 2440923, 'max_physical_flights': 8, 'selected': 2290406, 'resampled': 2290406, 'rows': 1283571596, 'unresolved': 28325, 'contains_mvt': 1482965, 'starts_after_mvt': 805183, 'ends_before_mvt': 2258, 'elapsed_sec': 3440.1, 'mvts_per_sec': 674.04, 'rss_gib': 2.1533203125}

{'buckets': '507/512', 'mvts': 2323315, 'assigned_mvts': 2318310, 'single': 2198213, 'multiple': 120097, 'physical_flights': 2445715, 'max_physical_flights': 8, 'selected': 2294933, 'resampled': 2294933, 'rows': 1286134947, 'unresolved': 28382, 'contains_mvt': 1485908, 'starts_after_mvt': 806763, 'ends_before_mvt': 2262, 'elapsed_sec': 3440.9, 'mvts_per_sec': 675.2, 'rss_gib': 2.1533203125}

{'buckets': '508/512', 'mvts': 2327798, 'assigned_mvts': 2322782, 'single': 2202505, 'multiple': 120277, 'physical_flights': 2450383, 'max_physical_flights': 8, 'selected': 2299355, 'resampled': 2299355, 'rows': 1288638131, 'unresolved': 28443, 'contains_mvt': 1488753, 'starts_after_mvt': 808335, 'ends_before_mvt': 2267, 'elapsed_sec': 3458.0, 'mvts_per_sec': 673.16, 'rss_gib': 2.1533203125}

{'buckets': '509/512', 'mvts': 2332332, 'assigned_mvts': 2327304, 'single': 2206769, 'multiple': 120535, 'physical_flights': 2455174, 'max_physical_flights': 8, 'selected': 2303831, 'resampled': 2303831, 'rows': 1291118242, 'unresolved': 28501, 'contains_mvt': 1491696, 'starts_after_mvt': 809867, 'ends_before_mvt': 2268, 'elapsed_sec': 3461.4, 'mvts_per_sec': 673.81, 'rss_gib': 2.1533203125}

{'buckets': '510/512', 'mvts': 2336952, 'assigned_mvts': 2331920, 'single': 2211162, 'multiple': 120758, 'physical_flights': 2460027, 'max_physical_flights': 8, 'selected': 2308409, 'resampled': 2308409, 'rows': 1293641653, 'unresolved': 28543, 'contains_mvt': 1494622, 'starts_after_mvt': 811514, 'ends_before_mvt': 2273, 'elapsed_sec': 3468.1, 'mvts_per_sec': 673.84, 'rss_gib': 2.1533203125}

{'buckets': '511/512', 'mvts': 2341486, 'assigned_mvts': 2336444, 'single': 2215452, 'multiple': 120992, 'physical_flights': 2464801, 'max_physical_flights': 8, 'selected': 2312876, 'resampled': 2312876, 'rows': 1296163238, 'unresolved': 28610, 'contains_mvt': 1497512, 'starts_after_mvt': 813080, 'ends_before_mvt': 2284, 'elapsed_sec': 3470.6, 'mvts_per_sec': 674.67, 'rss_gib': 2.1533203125}

{'buckets': '512/512', 'mvts': 2346159, 'assigned_mvts': 2341105, 'single': 2219857, 'multiple': 121248, 'physical_flights': 2469729, 'max_physical_flights': 8, 'selected': 2317493, 'resampled': 2317493, 'rows': 1298697638, 'unresolved': 28666, 'contains_mvt': 1500419, 'starts_after_mvt': 814787, 'ends_before_mvt': 2287, 'elapsed_sec': 3475.9, 'mvts_per_sec': 674.97, 'rss_gib': 2.1533203125}

Stage A committed: movement_1s_v5; Parquet size 44.467 GiB

mvts                       2346159
assigned_mvts              2341105
single                     2219857
multiple                    121248
physical_flights           2469729
max_physical_flights             8
selected                   2317493
resampled                  2317493
rows                    1298697638
unresolved                   28666
contains_mvt               1500419
starts_after_mvt            814787
ends_before_mvt               2287
dtype: int64

## Stage B: first movement and distances

`Flight.movement()` (speed above 2 kn for at least 30 s) gives the start of the first sustained movement. The table
keeps absolute times, so `05_features` can express them relative to any dataset's take-off time.

In [5]:
stage_b = workflow.stage_b(PROCESSED, FEATURES, config, partition_function=extra.feature_partition,
                           partition_args=(str(context),), feature_schema=extra.SCHEMA, extra_validator=extra.validate_extra)
workflow.json_write(FEATURES.with_suffix(".json"), {**stage_b, "geometry_context": str(context)})
pd.Series(stage_b)

{'stage': 'B', 'buckets': '0/512', 'mvts': 0, 'detections': 0, 'elapsed_sec': 30.1, 'mvts_per_sec': 0.0, 'rss_gib': 2.160411834716797}

{'stage': 'B', 'buckets': '0/512', 'mvts': 0, 'detections': 0, 'elapsed_sec': 60.1, 'mvts_per_sec': 0.0, 'rss_gib': 2.1604156494140625}

{'stage': 'B', 'buckets': '0/512', 'mvts': 0, 'detections': 0, 'elapsed_sec': 90.1, 'mvts_per_sec': 0.0, 'rss_gib': 2.1604156494140625}

{'stage': 'B', 'buckets': '0/512', 'mvts': 0, 'detections': 0, 'elapsed_sec': 120.1, 'mvts_per_sec': 0.0, 'rss_gib': 2.1604156494140625}

{'stage': 'B', 'buckets': '0/512', 'mvts': 0, 'detections': 0, 'elapsed_sec': 150.1, 'mvts_per_sec': 0.0, 'rss_gib': 2.1604156494140625}

{'stage': 'B', 'buckets': '0/512', 'mvts': 0, 'detections': 0, 'elapsed_sec': 180.1, 'mvts_per_sec': 0.0, 'rss_gib': 2.1604156494140625}

{'stage': 'B', 'buckets': '1/512', 'mvts': 4488, 'detections': 4346, 'elapsed_sec': 203.3, 'mvts_per_sec': 22.08, 'rss_gib': 2.169933319091797}

{'stage': 'B', 'buckets': '2/512', 'mvts': 9084, 'detections': 8843, 'elapsed_sec': 209.6, 'mvts_per_sec': 43.34, 'rss_gib': 2.181011199951172}

{'stage': 'B', 'buckets': '3/512', 'mvts': 13689, 'detections': 13342, 'elapsed_sec': 210.7, 'mvts_per_sec': 64.95, 'rss_gib': 2.1851806640625}

{'stage': 'B', 'buckets': '4/512', 'mvts': 18144, 'detections': 17691, 'elapsed_sec': 210.8, 'mvts_per_sec': 86.06, 'rss_gib': 2.1851882934570312}

{'stage': 'B', 'buckets': '5/512', 'mvts': 22629, 'detections': 22078, 'elapsed_sec': 212.0, 'mvts_per_sec': 106.74, 'rss_gib': 2.1851882934570312}

{'stage': 'B', 'buckets': '6/512', 'mvts': 27287, 'detections': 26613, 'elapsed_sec': 212.5, 'mvts_per_sec': 128.42, 'rss_gib': 2.1852874755859375}

{'stage': 'B', 'buckets': '7/512', 'mvts': 31828, 'detections': 31047, 'elapsed_sec': 213.2, 'mvts_per_sec': 149.28, 'rss_gib': 2.185169219970703}

{'stage': 'B', 'buckets': '8/512', 'mvts': 36387, 'detections': 35490, 'elapsed_sec': 214.7, 'mvts_per_sec': 169.51, 'rss_gib': 2.1852264404296875}

{'stage': 'B', 'buckets': '9/512', 'mvts': 40975, 'detections': 39953, 'elapsed_sec': 215.1, 'mvts_per_sec': 190.46, 'rss_gib': 2.1852378845214844}

{'stage': 'B', 'buckets': '10/512', 'mvts': 45470, 'detections': 44318, 'elapsed_sec': 215.7, 'mvts_per_sec': 210.78, 'rss_gib': 2.185321807861328}

{'stage': 'B', 'buckets': '11/512', 'mvts': 50063, 'detections': 48780, 'elapsed_sec': 216.5, 'mvts_per_sec': 231.21, 'rss_gib': 2.1853179931640625}

{'stage': 'B', 'buckets': '12/512', 'mvts': 54652, 'detections': 53262, 'elapsed_sec': 217.6, 'mvts_per_sec': 251.14, 'rss_gib': 2.1853179931640625}

{'stage': 'B', 'buckets': '13/512', 'mvts': 59258, 'detections': 57758, 'elapsed_sec': 217.7, 'mvts_per_sec': 272.21, 'rss_gib': 2.185321807861328}

{'stage': 'B', 'buckets': '14/512', 'mvts': 63800, 'detections': 62174, 'elapsed_sec': 218.5, 'mvts_per_sec': 292.02, 'rss_gib': 2.185321807861328}

{'stage': 'B', 'buckets': '15/512', 'mvts': 68426, 'detections': 66677, 'elapsed_sec': 218.9, 'mvts_per_sec': 312.62, 'rss_gib': 2.185321807861328}

{'stage': 'B', 'buckets': '16/512', 'mvts': 73057, 'detections': 71193, 'elapsed_sec': 219.3, 'mvts_per_sec': 333.13, 'rss_gib': 2.185321807861328}

{'stage': 'B', 'buckets': '17/512', 'mvts': 77690, 'detections': 75710, 'elapsed_sec': 219.9, 'mvts_per_sec': 353.37, 'rss_gib': 2.185321807861328}

{'stage': 'B', 'buckets': '18/512', 'mvts': 82299, 'detections': 80187, 'elapsed_sec': 220.1, 'mvts_per_sec': 373.99, 'rss_gib': 2.185321807861328}

{'stage': 'B', 'buckets': '19/512', 'mvts': 86911, 'detections': 84693, 'elapsed_sec': 222.5, 'mvts_per_sec': 390.67, 'rss_gib': 2.185321807861328}

{'stage': 'B', 'buckets': '20/512', 'mvts': 91532, 'detections': 89200, 'elapsed_sec': 222.8, 'mvts_per_sec': 410.76, 'rss_gib': 2.185321807861328}

{'stage': 'B', 'buckets': '21/512', 'mvts': 96048, 'detections': 93602, 'elapsed_sec': 224.1, 'mvts_per_sec': 428.67, 'rss_gib': 2.185321807861328}

{'stage': 'B', 'buckets': '22/512', 'mvts': 100589, 'detections': 98027, 'elapsed_sec': 225.8, 'mvts_per_sec': 445.43, 'rss_gib': 2.185321807861328}

{'stage': 'B', 'buckets': '23/512', 'mvts': 105251, 'detections': 102593, 'elapsed_sec': 225.9, 'mvts_per_sec': 465.9, 'rss_gib': 2.185321807861328}

{'stage': 'B', 'buckets': '24/512', 'mvts': 109818, 'detections': 107023, 'elapsed_sec': 226.3, 'mvts_per_sec': 485.35, 'rss_gib': 2.185394287109375}

{'stage': 'B', 'buckets': '25/512', 'mvts': 114374, 'detections': 111473, 'elapsed_sec': 227.1, 'mvts_per_sec': 503.58, 'rss_gib': 2.185394287109375}

{'stage': 'B', 'buckets': '26/512', 'mvts': 118942, 'detections': 115921, 'elapsed_sec': 227.2, 'mvts_per_sec': 523.5, 'rss_gib': 2.1854248046875}

{'stage': 'B', 'buckets': '27/512', 'mvts': 123564, 'detections': 120425, 'elapsed_sec': 231.5, 'mvts_per_sec': 533.77, 'rss_gib': 2.1854248046875}

{'stage': 'B', 'buckets': '28/512', 'mvts': 128232, 'detections': 124971, 'elapsed_sec': 231.8, 'mvts_per_sec': 553.25, 'rss_gib': 2.1854248046875}

{'stage': 'B', 'buckets': '29/512', 'mvts': 132894, 'detections': 129505, 'elapsed_sec': 233.9, 'mvts_per_sec': 568.18, 'rss_gib': 2.1854248046875}

{'stage': 'B', 'buckets': '29/512', 'mvts': 132894, 'detections': 129505, 'elapsed_sec': 263.9, 'mvts_per_sec': 503.58, 'rss_gib': 2.1854248046875}

{'stage': 'B', 'buckets': '29/512', 'mvts': 132894, 'detections': 129505, 'elapsed_sec': 293.9, 'mvts_per_sec': 452.17, 'rss_gib': 2.1854248046875}

{'stage': 'B', 'buckets': '29/512', 'mvts': 132894, 'detections': 129505, 'elapsed_sec': 323.9, 'mvts_per_sec': 410.29, 'rss_gib': 2.1854248046875}

{'stage': 'B', 'buckets': '29/512', 'mvts': 132894, 'detections': 129505, 'elapsed_sec': 353.9, 'mvts_per_sec': 375.51, 'rss_gib': 2.1854248046875}

{'stage': 'B', 'buckets': '29/512', 'mvts': 132894, 'detections': 129505, 'elapsed_sec': 383.9, 'mvts_per_sec': 346.16, 'rss_gib': 2.1854248046875}

{'stage': 'B', 'buckets': '30/512', 'mvts': 137478, 'detections': 133976, 'elapsed_sec': 412.7, 'mvts_per_sec': 333.08, 'rss_gib': 2.1854248046875}

{'stage': 'B', 'buckets': '31/512', 'mvts': 141989, 'detections': 138368, 'elapsed_sec': 414.0, 'mvts_per_sec': 342.94, 'rss_gib': 2.1854248046875}

{'stage': 'B', 'buckets': '32/512', 'mvts': 146486, 'detections': 142761, 'elapsed_sec': 416.3, 'mvts_per_sec': 351.85, 'rss_gib': 2.1854248046875}

{'stage': 'B', 'buckets': '33/512', 'mvts': 151024, 'detections': 147196, 'elapsed_sec': 420.0, 'mvts_per_sec': 359.57, 'rss_gib': 2.1854248046875}

{'stage': 'B', 'buckets': '34/512', 'mvts': 155680, 'detections': 151734, 'elapsed_sec': 420.7, 'mvts_per_sec': 370.04, 'rss_gib': 2.1854248046875}

{'stage': 'B', 'buckets': '35/512', 'mvts': 160238, 'detections': 156165, 'elapsed_sec': 420.9, 'mvts_per_sec': 380.74, 'rss_gib': 2.1854248046875}

{'stage': 'B', 'buckets': '36/512', 'mvts': 164866, 'detections': 160667, 'elapsed_sec': 420.9, 'mvts_per_sec': 391.66, 'rss_gib': 2.1854248046875}

{'stage': 'B', 'buckets': '37/512', 'mvts': 169415, 'detections': 165108, 'elapsed_sec': 422.8, 'mvts_per_sec': 400.73, 'rss_gib': 2.1854248046875}

{'stage': 'B', 'buckets': '38/512', 'mvts': 174003, 'detections': 169601, 'elapsed_sec': 423.7, 'mvts_per_sec': 410.71, 'rss_gib': 2.1854286193847656}

{'stage': 'B', 'buckets': '39/512', 'mvts': 178619, 'detections': 174112, 'elapsed_sec': 425.5, 'mvts_per_sec': 419.78, 'rss_gib': 2.1854286193847656}

{'stage': 'B', 'buckets': '40/512', 'mvts': 183331, 'detections': 178694, 'elapsed_sec': 426.1, 'mvts_per_sec': 430.24, 'rss_gib': 2.1854286193847656}

{'stage': 'B', 'buckets': '41/512', 'mvts': 187863, 'detections': 183097, 'elapsed_sec': 427.9, 'mvts_per_sec': 439.06, 'rss_gib': 2.1854324340820312}

{'stage': 'B', 'buckets': '42/512', 'mvts': 192412, 'detections': 187520, 'elapsed_sec': 428.5, 'mvts_per_sec': 449.01, 'rss_gib': 2.185546875}

{'stage': 'B', 'buckets': '43/512', 'mvts': 197079, 'detections': 192085, 'elapsed_sec': 429.5, 'mvts_per_sec': 458.82, 'rss_gib': 2.1856918334960938}

{'stage': 'B', 'buckets': '44/512', 'mvts': 201577, 'detections': 196487, 'elapsed_sec': 430.0, 'mvts_per_sec': 468.75, 'rss_gib': 2.1856956481933594}

{'stage': 'B', 'buckets': '45/512', 'mvts': 206106, 'detections': 200915, 'elapsed_sec': 433.0, 'mvts_per_sec': 475.97, 'rss_gib': 2.185993194580078}

{'stage': 'B', 'buckets': '46/512', 'mvts': 210774, 'detections': 205457, 'elapsed_sec': 433.2, 'mvts_per_sec': 486.59, 'rss_gib': 2.1860618591308594}

{'stage': 'B', 'buckets': '47/512', 'mvts': 215445, 'detections': 210002, 'elapsed_sec': 433.2, 'mvts_per_sec': 497.28, 'rss_gib': 2.1860618591308594}

{'stage': 'B', 'buckets': '48/512', 'mvts': 220073, 'detections': 214508, 'elapsed_sec': 435.2, 'mvts_per_sec': 505.66, 'rss_gib': 2.1860923767089844}

{'stage': 'B', 'buckets': '49/512', 'mvts': 224689, 'detections': 219012, 'elapsed_sec': 438.0, 'mvts_per_sec': 512.96, 'rss_gib': 2.1862030029296875}

{'stage': 'B', 'buckets': '50/512', 'mvts': 229425, 'detections': 223606, 'elapsed_sec': 438.7, 'mvts_per_sec': 522.98, 'rss_gib': 2.1863670349121094}

{'stage': 'B', 'buckets': '51/512', 'mvts': 233916, 'detections': 227982, 'elapsed_sec': 439.3, 'mvts_per_sec': 532.44, 'rss_gib': 2.1863670349121094}

{'stage': 'B', 'buckets': '52/512', 'mvts': 238520, 'detections': 232461, 'elapsed_sec': 441.3, 'mvts_per_sec': 540.45, 'rss_gib': 2.1863670349121094}

{'stage': 'B', 'buckets': '53/512', 'mvts': 243024, 'detections': 236854, 'elapsed_sec': 441.4, 'mvts_per_sec': 550.55, 'rss_gib': 2.1863670349121094}

{'stage': 'B', 'buckets': '54/512', 'mvts': 247566, 'detections': 241281, 'elapsed_sec': 443.9, 'mvts_per_sec': 557.72, 'rss_gib': 2.1863670349121094}

{'stage': 'B', 'buckets': '55/512', 'mvts': 252238, 'detections': 245844, 'elapsed_sec': 444.7, 'mvts_per_sec': 567.16, 'rss_gib': 2.1863670349121094}

{'stage': 'B', 'buckets': '56/512', 'mvts': 256794, 'detections': 250289, 'elapsed_sec': 445.9, 'mvts_per_sec': 575.94, 'rss_gib': 2.1863670349121094}

{'stage': 'B', 'buckets': '57/512', 'mvts': 261478, 'detections': 254867, 'elapsed_sec': 447.1, 'mvts_per_sec': 584.8, 'rss_gib': 2.1863670349121094}

{'stage': 'B', 'buckets': '58/512', 'mvts': 266032, 'detections': 259305, 'elapsed_sec': 447.6, 'mvts_per_sec': 594.31, 'rss_gib': 2.1863670349121094}

{'stage': 'B', 'buckets': '58/512', 'mvts': 266032, 'detections': 259305, 'elapsed_sec': 477.6, 'mvts_per_sec': 556.98, 'rss_gib': 2.1863670349121094}

{'stage': 'B', 'buckets': '58/512', 'mvts': 266032, 'detections': 259305, 'elapsed_sec': 507.6, 'mvts_per_sec': 524.06, 'rss_gib': 2.1863670349121094}

{'stage': 'B', 'buckets': '58/512', 'mvts': 266032, 'detections': 259305, 'elapsed_sec': 537.6, 'mvts_per_sec': 494.82, 'rss_gib': 2.1863670349121094}

{'stage': 'B', 'buckets': '58/512', 'mvts': 266032, 'detections': 259305, 'elapsed_sec': 567.6, 'mvts_per_sec': 468.67, 'rss_gib': 2.1863670349121094}

{'stage': 'B', 'buckets': '58/512', 'mvts': 266032, 'detections': 259305, 'elapsed_sec': 597.6, 'mvts_per_sec': 445.14, 'rss_gib': 2.1863670349121094}

{'stage': 'B', 'buckets': '59/512', 'mvts': 270588, 'detections': 263756, 'elapsed_sec': 618.2, 'mvts_per_sec': 437.69, 'rss_gib': 2.1863670349121094}

{'stage': 'B', 'buckets': '60/512', 'mvts': 275177, 'detections': 268234, 'elapsed_sec': 625.3, 'mvts_per_sec': 440.08, 'rss_gib': 2.1863670349121094}

{'stage': 'B', 'buckets': '61/512', 'mvts': 279779, 'detections': 272729, 'elapsed_sec': 625.9, 'mvts_per_sec': 447.02, 'rss_gib': 2.1863555908203125}

{'stage': 'B', 'buckets': '62/512', 'mvts': 284395, 'detections': 277252, 'elapsed_sec': 627.9, 'mvts_per_sec': 452.94, 'rss_gib': 2.1863555908203125}

{'stage': 'B', 'buckets': '63/512', 'mvts': 289086, 'detections': 281823, 'elapsed_sec': 631.0, 'mvts_per_sec': 458.15, 'rss_gib': 2.1863555908203125}

{'stage': 'B', 'buckets': '64/512', 'mvts': 293637, 'detections': 286271, 'elapsed_sec': 631.9, 'mvts_per_sec': 464.7, 'rss_gib': 2.1863555908203125}

{'stage': 'B', 'buckets': '65/512', 'mvts': 298223, 'detections': 290721, 'elapsed_sec': 632.2, 'mvts_per_sec': 471.73, 'rss_gib': 2.1863555908203125}

{'stage': 'B', 'buckets': '66/512', 'mvts': 302823, 'detections': 295222, 'elapsed_sec': 635.9, 'mvts_per_sec': 476.2, 'rss_gib': 2.1863555908203125}

{'stage': 'B', 'buckets': '67/512', 'mvts': 307421, 'detections': 299712, 'elapsed_sec': 636.0, 'mvts_per_sec': 483.36, 'rss_gib': 2.1863555908203125}

{'stage': 'B', 'buckets': '68/512', 'mvts': 312050, 'detections': 304221, 'elapsed_sec': 638.1, 'mvts_per_sec': 489.04, 'rss_gib': 2.1863555908203125}

{'stage': 'B', 'buckets': '69/512', 'mvts': 316629, 'detections': 308673, 'elapsed_sec': 638.2, 'mvts_per_sec': 496.15, 'rss_gib': 2.1863555908203125}

{'stage': 'B', 'buckets': '70/512', 'mvts': 321243, 'detections': 313174, 'elapsed_sec': 638.9, 'mvts_per_sec': 502.79, 'rss_gib': 2.1863555908203125}

{'stage': 'B', 'buckets': '71/512', 'mvts': 326015, 'detections': 317832, 'elapsed_sec': 640.6, 'mvts_per_sec': 508.94, 'rss_gib': 2.1865196228027344}

{'stage': 'B', 'buckets': '72/512', 'mvts': 330592, 'detections': 322290, 'elapsed_sec': 641.5, 'mvts_per_sec': 515.32, 'rss_gib': 2.1865463256835938}

{'stage': 'B', 'buckets': '73/512', 'mvts': 335028, 'detections': 326632, 'elapsed_sec': 643.6, 'mvts_per_sec': 520.58, 'rss_gib': 2.1865463256835938}

{'stage': 'B', 'buckets': '74/512', 'mvts': 339603, 'detections': 331103, 'elapsed_sec': 644.0, 'mvts_per_sec': 527.32, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '75/512', 'mvts': 344273, 'detections': 335648, 'elapsed_sec': 646.1, 'mvts_per_sec': 532.84, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '76/512', 'mvts': 348862, 'detections': 340118, 'elapsed_sec': 648.8, 'mvts_per_sec': 537.74, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '77/512', 'mvts': 353568, 'detections': 344710, 'elapsed_sec': 649.2, 'mvts_per_sec': 544.64, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '78/512', 'mvts': 358160, 'detections': 349173, 'elapsed_sec': 649.3, 'mvts_per_sec': 551.64, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '79/512', 'mvts': 362700, 'detections': 353597, 'elapsed_sec': 650.6, 'mvts_per_sec': 557.48, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '80/512', 'mvts': 367168, 'detections': 357947, 'elapsed_sec': 653.7, 'mvts_per_sec': 561.67, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '81/512', 'mvts': 371828, 'detections': 362493, 'elapsed_sec': 654.1, 'mvts_per_sec': 568.49, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '82/512', 'mvts': 376520, 'detections': 367087, 'elapsed_sec': 657.2, 'mvts_per_sec': 572.94, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '83/512', 'mvts': 381169, 'detections': 371622, 'elapsed_sec': 661.2, 'mvts_per_sec': 576.48, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '84/512', 'mvts': 385789, 'detections': 376136, 'elapsed_sec': 663.9, 'mvts_per_sec': 581.06, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '85/512', 'mvts': 390370, 'detections': 380602, 'elapsed_sec': 664.0, 'mvts_per_sec': 587.88, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '86/512', 'mvts': 395022, 'detections': 385136, 'elapsed_sec': 665.5, 'mvts_per_sec': 593.58, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '87/512', 'mvts': 399605, 'detections': 389625, 'elapsed_sec': 670.7, 'mvts_per_sec': 595.78, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '87/512', 'mvts': 399605, 'detections': 389625, 'elapsed_sec': 700.7, 'mvts_per_sec': 570.27, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '87/512', 'mvts': 399605, 'detections': 389625, 'elapsed_sec': 730.7, 'mvts_per_sec': 546.85, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '87/512', 'mvts': 399605, 'detections': 389625, 'elapsed_sec': 760.7, 'mvts_per_sec': 525.29, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '87/512', 'mvts': 399605, 'detections': 389625, 'elapsed_sec': 790.7, 'mvts_per_sec': 505.36, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '87/512', 'mvts': 399605, 'detections': 389625, 'elapsed_sec': 820.7, 'mvts_per_sec': 486.88, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '88/512', 'mvts': 404259, 'detections': 394166, 'elapsed_sec': 822.4, 'mvts_per_sec': 491.55, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '89/512', 'mvts': 408821, 'detections': 398616, 'elapsed_sec': 833.5, 'mvts_per_sec': 490.5, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '90/512', 'mvts': 413487, 'detections': 403160, 'elapsed_sec': 837.4, 'mvts_per_sec': 493.77, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '91/512', 'mvts': 418015, 'detections': 407561, 'elapsed_sec': 838.2, 'mvts_per_sec': 498.72, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '92/512', 'mvts': 422731, 'detections': 412162, 'elapsed_sec': 841.1, 'mvts_per_sec': 502.6, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '93/512', 'mvts': 427320, 'detections': 416644, 'elapsed_sec': 841.2, 'mvts_per_sec': 508.01, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '94/512', 'mvts': 431831, 'detections': 421041, 'elapsed_sec': 844.9, 'mvts_per_sec': 511.1, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '95/512', 'mvts': 436375, 'detections': 425475, 'elapsed_sec': 845.6, 'mvts_per_sec': 516.07, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '96/512', 'mvts': 440917, 'detections': 429898, 'elapsed_sec': 846.0, 'mvts_per_sec': 521.21, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '97/512', 'mvts': 445535, 'detections': 434404, 'elapsed_sec': 848.7, 'mvts_per_sec': 524.96, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '98/512', 'mvts': 450205, 'detections': 438950, 'elapsed_sec': 849.1, 'mvts_per_sec': 530.19, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '99/512', 'mvts': 454744, 'detections': 443369, 'elapsed_sec': 850.5, 'mvts_per_sec': 534.7, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '100/512', 'mvts': 459370, 'detections': 447879, 'elapsed_sec': 852.1, 'mvts_per_sec': 539.09, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '101/512', 'mvts': 463997, 'detections': 452394, 'elapsed_sec': 857.5, 'mvts_per_sec': 541.1, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '102/512', 'mvts': 468449, 'detections': 456750, 'elapsed_sec': 858.1, 'mvts_per_sec': 545.92, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '103/512', 'mvts': 473093, 'detections': 461284, 'elapsed_sec': 859.6, 'mvts_per_sec': 550.36, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '104/512', 'mvts': 477763, 'detections': 465837, 'elapsed_sec': 860.2, 'mvts_per_sec': 555.38, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '105/512', 'mvts': 482265, 'detections': 470229, 'elapsed_sec': 861.5, 'mvts_per_sec': 559.8, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '106/512', 'mvts': 486784, 'detections': 474632, 'elapsed_sec': 863.2, 'mvts_per_sec': 563.92, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '107/512', 'mvts': 491404, 'detections': 479145, 'elapsed_sec': 863.3, 'mvts_per_sec': 569.23, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '108/512', 'mvts': 495977, 'detections': 483601, 'elapsed_sec': 865.5, 'mvts_per_sec': 573.08, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '109/512', 'mvts': 500641, 'detections': 488152, 'elapsed_sec': 866.5, 'mvts_per_sec': 577.77, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '110/512', 'mvts': 505140, 'detections': 492533, 'elapsed_sec': 867.5, 'mvts_per_sec': 582.31, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '111/512', 'mvts': 509765, 'detections': 497026, 'elapsed_sec': 868.5, 'mvts_per_sec': 586.93, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '112/512', 'mvts': 514340, 'detections': 501471, 'elapsed_sec': 871.1, 'mvts_per_sec': 590.45, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '113/512', 'mvts': 518792, 'detections': 505824, 'elapsed_sec': 874.3, 'mvts_per_sec': 593.36, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '114/512', 'mvts': 523431, 'detections': 510350, 'elapsed_sec': 877.6, 'mvts_per_sec': 596.4, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '115/512', 'mvts': 528036, 'detections': 514838, 'elapsed_sec': 880.9, 'mvts_per_sec': 599.41, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '116/512', 'mvts': 532687, 'detections': 519373, 'elapsed_sec': 888.6, 'mvts_per_sec': 599.48, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '116/512', 'mvts': 532687, 'detections': 519373, 'elapsed_sec': 918.6, 'mvts_per_sec': 579.9, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '116/512', 'mvts': 532687, 'detections': 519373, 'elapsed_sec': 948.6, 'mvts_per_sec': 561.56, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '116/512', 'mvts': 532687, 'detections': 519373, 'elapsed_sec': 978.6, 'mvts_per_sec': 544.34, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '116/512', 'mvts': 532687, 'detections': 519373, 'elapsed_sec': 1008.6, 'mvts_per_sec': 528.15, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '117/512', 'mvts': 537182, 'detections': 523755, 'elapsed_sec': 1021.7, 'mvts_per_sec': 525.78, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '118/512', 'mvts': 541748, 'detections': 528213, 'elapsed_sec': 1043.3, 'mvts_per_sec': 519.26, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '119/512', 'mvts': 546296, 'detections': 532641, 'elapsed_sec': 1044.9, 'mvts_per_sec': 522.83, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '120/512', 'mvts': 550897, 'detections': 537149, 'elapsed_sec': 1045.9, 'mvts_per_sec': 526.73, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '121/512', 'mvts': 555425, 'detections': 541581, 'elapsed_sec': 1050.1, 'mvts_per_sec': 528.9, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '122/512', 'mvts': 559861, 'detections': 545910, 'elapsed_sec': 1051.5, 'mvts_per_sec': 532.42, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '123/512', 'mvts': 564515, 'detections': 550445, 'elapsed_sec': 1053.3, 'mvts_per_sec': 535.93, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '124/512', 'mvts': 569102, 'detections': 554917, 'elapsed_sec': 1054.2, 'mvts_per_sec': 539.86, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '125/512', 'mvts': 573685, 'detections': 559389, 'elapsed_sec': 1055.4, 'mvts_per_sec': 543.59, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '126/512', 'mvts': 578270, 'detections': 563867, 'elapsed_sec': 1055.9, 'mvts_per_sec': 547.63, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '127/512', 'mvts': 582806, 'detections': 568306, 'elapsed_sec': 1056.4, 'mvts_per_sec': 551.71, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '128/512', 'mvts': 587323, 'detections': 572721, 'elapsed_sec': 1057.7, 'mvts_per_sec': 555.3, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '129/512', 'mvts': 591786, 'detections': 577074, 'elapsed_sec': 1059.2, 'mvts_per_sec': 558.72, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '130/512', 'mvts': 596199, 'detections': 581367, 'elapsed_sec': 1062.0, 'mvts_per_sec': 561.41, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '131/512', 'mvts': 600613, 'detections': 585680, 'elapsed_sec': 1065.3, 'mvts_per_sec': 563.77, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '132/512', 'mvts': 605097, 'detections': 590051, 'elapsed_sec': 1068.9, 'mvts_per_sec': 566.09, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '133/512', 'mvts': 609652, 'detections': 594503, 'elapsed_sec': 1069.9, 'mvts_per_sec': 569.84, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '134/512', 'mvts': 614178, 'detections': 598910, 'elapsed_sec': 1070.4, 'mvts_per_sec': 573.77, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '135/512', 'mvts': 618801, 'detections': 603416, 'elapsed_sec': 1074.3, 'mvts_per_sec': 576.03, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '136/512', 'mvts': 623318, 'detections': 607820, 'elapsed_sec': 1074.5, 'mvts_per_sec': 580.09, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '137/512', 'mvts': 627973, 'detections': 612354, 'elapsed_sec': 1079.6, 'mvts_per_sec': 581.68, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '138/512', 'mvts': 632516, 'detections': 616782, 'elapsed_sec': 1082.8, 'mvts_per_sec': 584.13, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '139/512', 'mvts': 637224, 'detections': 621381, 'elapsed_sec': 1082.9, 'mvts_per_sec': 588.43, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '140/512', 'mvts': 641863, 'detections': 625892, 'elapsed_sec': 1084.1, 'mvts_per_sec': 592.09, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '141/512', 'mvts': 646514, 'detections': 630452, 'elapsed_sec': 1085.3, 'mvts_per_sec': 595.72, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '142/512', 'mvts': 651022, 'detections': 634854, 'elapsed_sec': 1087.6, 'mvts_per_sec': 598.6, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '143/512', 'mvts': 655535, 'detections': 639265, 'elapsed_sec': 1093.2, 'mvts_per_sec': 599.62, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '144/512', 'mvts': 660104, 'detections': 643729, 'elapsed_sec': 1096.4, 'mvts_per_sec': 602.04, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '145/512', 'mvts': 664663, 'detections': 648195, 'elapsed_sec': 1097.8, 'mvts_per_sec': 605.48, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '145/512', 'mvts': 664663, 'detections': 648195, 'elapsed_sec': 1127.8, 'mvts_per_sec': 589.37, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '145/512', 'mvts': 664663, 'detections': 648195, 'elapsed_sec': 1157.8, 'mvts_per_sec': 574.09, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '145/512', 'mvts': 664663, 'detections': 648195, 'elapsed_sec': 1187.8, 'mvts_per_sec': 559.59, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '145/512', 'mvts': 664663, 'detections': 648195, 'elapsed_sec': 1217.8, 'mvts_per_sec': 545.8, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '146/512', 'mvts': 669332, 'detections': 652773, 'elapsed_sec': 1242.3, 'mvts_per_sec': 538.76, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '147/512', 'mvts': 673857, 'detections': 657184, 'elapsed_sec': 1247.7, 'mvts_per_sec': 540.09, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '148/512', 'mvts': 678416, 'detections': 661622, 'elapsed_sec': 1253.0, 'mvts_per_sec': 541.43, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '149/512', 'mvts': 682982, 'detections': 666074, 'elapsed_sec': 1255.9, 'mvts_per_sec': 543.81, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '150/512', 'mvts': 687538, 'detections': 670526, 'elapsed_sec': 1257.3, 'mvts_per_sec': 546.82, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '151/512', 'mvts': 692028, 'detections': 674895, 'elapsed_sec': 1258.2, 'mvts_per_sec': 550.03, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '152/512', 'mvts': 696721, 'detections': 679458, 'elapsed_sec': 1261.0, 'mvts_per_sec': 552.52, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '153/512', 'mvts': 701244, 'detections': 683851, 'elapsed_sec': 1261.8, 'mvts_per_sec': 555.76, 'rss_gib': 2.1865768432617188}

{'stage': 'B', 'buckets': '154/512', 'mvts': 705829, 'detections': 688335, 'elapsed_sec': 1263.1, 'mvts_per_sec': 558.82, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '155/512', 'mvts': 710473, 'detections': 692859, 'elapsed_sec': 1265.8, 'mvts_per_sec': 561.29, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '156/512', 'mvts': 715026, 'detections': 697298, 'elapsed_sec': 1267.4, 'mvts_per_sec': 564.17, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '157/512', 'mvts': 719555, 'detections': 701730, 'elapsed_sec': 1271.3, 'mvts_per_sec': 566.0, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '158/512', 'mvts': 724093, 'detections': 706152, 'elapsed_sec': 1273.2, 'mvts_per_sec': 568.74, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '159/512', 'mvts': 728834, 'detections': 710771, 'elapsed_sec': 1273.5, 'mvts_per_sec': 572.3, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '160/512', 'mvts': 733414, 'detections': 715220, 'elapsed_sec': 1273.6, 'mvts_per_sec': 575.85, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '161/512', 'mvts': 738076, 'detections': 719746, 'elapsed_sec': 1273.8, 'mvts_per_sec': 579.42, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '162/512', 'mvts': 742580, 'detections': 724140, 'elapsed_sec': 1278.8, 'mvts_per_sec': 580.67, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '163/512', 'mvts': 747141, 'detections': 728594, 'elapsed_sec': 1280.4, 'mvts_per_sec': 583.51, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '164/512', 'mvts': 751716, 'detections': 733059, 'elapsed_sec': 1287.5, 'mvts_per_sec': 583.84, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '165/512', 'mvts': 756378, 'detections': 737622, 'elapsed_sec': 1291.0, 'mvts_per_sec': 585.86, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '166/512', 'mvts': 761045, 'detections': 742169, 'elapsed_sec': 1298.4, 'mvts_per_sec': 586.16, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '167/512', 'mvts': 765672, 'detections': 746679, 'elapsed_sec': 1298.8, 'mvts_per_sec': 589.51, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '168/512', 'mvts': 770313, 'detections': 751221, 'elapsed_sec': 1300.9, 'mvts_per_sec': 592.14, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '169/512', 'mvts': 775012, 'detections': 755798, 'elapsed_sec': 1302.3, 'mvts_per_sec': 595.12, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '170/512', 'mvts': 779537, 'detections': 760201, 'elapsed_sec': 1304.1, 'mvts_per_sec': 597.74, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '171/512', 'mvts': 784121, 'detections': 764660, 'elapsed_sec': 1309.2, 'mvts_per_sec': 598.92, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '172/512', 'mvts': 788709, 'detections': 769140, 'elapsed_sec': 1310.2, 'mvts_per_sec': 601.98, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '173/512', 'mvts': 793363, 'detections': 773693, 'elapsed_sec': 1315.4, 'mvts_per_sec': 603.15, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '174/512', 'mvts': 798036, 'detections': 778233, 'elapsed_sec': 1317.9, 'mvts_per_sec': 605.55, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '174/512', 'mvts': 798036, 'detections': 778233, 'elapsed_sec': 1347.9, 'mvts_per_sec': 592.07, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '174/512', 'mvts': 798036, 'detections': 778233, 'elapsed_sec': 1377.9, 'mvts_per_sec': 579.18, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '174/512', 'mvts': 798036, 'detections': 778233, 'elapsed_sec': 1407.9, 'mvts_per_sec': 566.83, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '174/512', 'mvts': 798036, 'detections': 778233, 'elapsed_sec': 1437.9, 'mvts_per_sec': 555.01, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '175/512', 'mvts': 802571, 'detections': 782656, 'elapsed_sec': 1446.3, 'mvts_per_sec': 554.9, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '176/512', 'mvts': 807070, 'detections': 787035, 'elapsed_sec': 1448.2, 'mvts_per_sec': 557.3, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '177/512', 'mvts': 811667, 'detections': 791518, 'elapsed_sec': 1461.1, 'mvts_per_sec': 555.52, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '178/512', 'mvts': 816239, 'detections': 795984, 'elapsed_sec': 1465.0, 'mvts_per_sec': 557.16, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '179/512', 'mvts': 820777, 'detections': 800411, 'elapsed_sec': 1465.9, 'mvts_per_sec': 559.92, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '180/512', 'mvts': 825367, 'detections': 804886, 'elapsed_sec': 1468.6, 'mvts_per_sec': 561.99, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '181/512', 'mvts': 829969, 'detections': 809369, 'elapsed_sec': 1470.0, 'mvts_per_sec': 564.59, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '182/512', 'mvts': 834550, 'detections': 813849, 'elapsed_sec': 1470.7, 'mvts_per_sec': 567.44, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '183/512', 'mvts': 839036, 'detections': 818211, 'elapsed_sec': 1470.9, 'mvts_per_sec': 570.42, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '184/512', 'mvts': 843541, 'detections': 822577, 'elapsed_sec': 1471.0, 'mvts_per_sec': 573.45, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '185/512', 'mvts': 848107, 'detections': 827031, 'elapsed_sec': 1473.9, 'mvts_per_sec': 575.43, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '186/512', 'mvts': 852808, 'detections': 831636, 'elapsed_sec': 1477.9, 'mvts_per_sec': 577.05, 'rss_gib': 2.1865806579589844}

{'stage': 'B', 'buckets': '187/512', 'mvts': 857499, 'detections': 836223, 'elapsed_sec': 1482.6, 'mvts_per_sec': 578.39, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '188/512', 'mvts': 862183, 'detections': 840797, 'elapsed_sec': 1485.0, 'mvts_per_sec': 580.6, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '189/512', 'mvts': 866752, 'detections': 845248, 'elapsed_sec': 1485.7, 'mvts_per_sec': 583.39, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '190/512', 'mvts': 871272, 'detections': 849678, 'elapsed_sec': 1493.7, 'mvts_per_sec': 583.31, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '191/512', 'mvts': 875839, 'detections': 854131, 'elapsed_sec': 1495.6, 'mvts_per_sec': 585.61, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '192/512', 'mvts': 880487, 'detections': 858676, 'elapsed_sec': 1495.7, 'mvts_per_sec': 588.68, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '193/512', 'mvts': 885047, 'detections': 863120, 'elapsed_sec': 1496.9, 'mvts_per_sec': 591.24, 'rss_gib': 2.1865882873535156}

{'stage': 'B', 'buckets': '194/512', 'mvts': 889669, 'detections': 867620, 'elapsed_sec': 1503.3, 'mvts_per_sec': 591.82, 'rss_gib': 2.1865882873535156}

{'stage': 'B', 'buckets': '195/512', 'mvts': 894073, 'detections': 871922, 'elapsed_sec': 1510.6, 'mvts_per_sec': 591.87, 'rss_gib': 2.186595916748047}

{'stage': 'B', 'buckets': '196/512', 'mvts': 898764, 'detections': 876494, 'elapsed_sec': 1514.1, 'mvts_per_sec': 593.58, 'rss_gib': 2.186595916748047}

{'stage': 'B', 'buckets': '197/512', 'mvts': 903345, 'detections': 880981, 'elapsed_sec': 1515.1, 'mvts_per_sec': 596.24, 'rss_gib': 2.186595916748047}

{'stage': 'B', 'buckets': '198/512', 'mvts': 907983, 'detections': 885492, 'elapsed_sec': 1517.9, 'mvts_per_sec': 598.19, 'rss_gib': 2.186595916748047}

{'stage': 'B', 'buckets': '199/512', 'mvts': 912525, 'detections': 889919, 'elapsed_sec': 1520.0, 'mvts_per_sec': 600.35, 'rss_gib': 2.186595916748047}

{'stage': 'B', 'buckets': '200/512', 'mvts': 917144, 'detections': 894418, 'elapsed_sec': 1529.5, 'mvts_per_sec': 599.64, 'rss_gib': 2.186595916748047}

{'stage': 'B', 'buckets': '201/512', 'mvts': 921817, 'detections': 898980, 'elapsed_sec': 1529.6, 'mvts_per_sec': 602.67, 'rss_gib': 2.186595916748047}

{'stage': 'B', 'buckets': '202/512', 'mvts': 926472, 'detections': 903500, 'elapsed_sec': 1531.1, 'mvts_per_sec': 605.11, 'rss_gib': 2.186595916748047}

{'stage': 'B', 'buckets': '203/512', 'mvts': 931137, 'detections': 908042, 'elapsed_sec': 1536.0, 'mvts_per_sec': 606.21, 'rss_gib': 2.186595916748047}

{'stage': 'B', 'buckets': '203/512', 'mvts': 931137, 'detections': 908042, 'elapsed_sec': 1566.0, 'mvts_per_sec': 594.6, 'rss_gib': 2.186595916748047}

{'stage': 'B', 'buckets': '203/512', 'mvts': 931137, 'detections': 908042, 'elapsed_sec': 1596.0, 'mvts_per_sec': 583.42, 'rss_gib': 2.186595916748047}

{'stage': 'B', 'buckets': '203/512', 'mvts': 931137, 'detections': 908042, 'elapsed_sec': 1626.0, 'mvts_per_sec': 572.66, 'rss_gib': 2.186595916748047}

{'stage': 'B', 'buckets': '204/512', 'mvts': 935787, 'detections': 912555, 'elapsed_sec': 1655.7, 'mvts_per_sec': 565.19, 'rss_gib': 2.186595916748047}

{'stage': 'B', 'buckets': '205/512', 'mvts': 940350, 'detections': 917002, 'elapsed_sec': 1666.2, 'mvts_per_sec': 564.38, 'rss_gib': 2.186595916748047}

{'stage': 'B', 'buckets': '206/512', 'mvts': 944784, 'detections': 921325, 'elapsed_sec': 1671.7, 'mvts_per_sec': 565.15, 'rss_gib': 2.186595916748047}

{'stage': 'B', 'buckets': '207/512', 'mvts': 949413, 'detections': 925840, 'elapsed_sec': 1675.0, 'mvts_per_sec': 566.82, 'rss_gib': 2.186595916748047}

{'stage': 'B', 'buckets': '208/512', 'mvts': 953974, 'detections': 930275, 'elapsed_sec': 1677.0, 'mvts_per_sec': 568.86, 'rss_gib': 2.186595916748047}

{'stage': 'B', 'buckets': '209/512', 'mvts': 958535, 'detections': 934739, 'elapsed_sec': 1678.0, 'mvts_per_sec': 571.25, 'rss_gib': 2.186595916748047}

{'stage': 'B', 'buckets': '210/512', 'mvts': 963160, 'detections': 939257, 'elapsed_sec': 1679.6, 'mvts_per_sec': 573.44, 'rss_gib': 2.186595916748047}

{'stage': 'B', 'buckets': '211/512', 'mvts': 967861, 'detections': 943825, 'elapsed_sec': 1684.1, 'mvts_per_sec': 574.72, 'rss_gib': 2.186595916748047}

{'stage': 'B', 'buckets': '212/512', 'mvts': 972411, 'detections': 948260, 'elapsed_sec': 1685.4, 'mvts_per_sec': 576.97, 'rss_gib': 2.186595916748047}

{'stage': 'B', 'buckets': '213/512', 'mvts': 977056, 'detections': 952778, 'elapsed_sec': 1686.1, 'mvts_per_sec': 579.49, 'rss_gib': 2.186595916748047}

{'stage': 'B', 'buckets': '214/512', 'mvts': 981631, 'detections': 957227, 'elapsed_sec': 1686.2, 'mvts_per_sec': 582.17, 'rss_gib': 2.186595916748047}

{'stage': 'B', 'buckets': '215/512', 'mvts': 986093, 'detections': 961586, 'elapsed_sec': 1686.5, 'mvts_per_sec': 584.69, 'rss_gib': 2.186595916748047}

{'stage': 'B', 'buckets': '216/512', 'mvts': 990622, 'detections': 965992, 'elapsed_sec': 1692.2, 'mvts_per_sec': 585.39, 'rss_gib': 2.186595916748047}

{'stage': 'B', 'buckets': '217/512', 'mvts': 995271, 'detections': 970521, 'elapsed_sec': 1700.2, 'mvts_per_sec': 585.38, 'rss_gib': 2.186595916748047}

{'stage': 'B', 'buckets': '218/512', 'mvts': 999859, 'detections': 974992, 'elapsed_sec': 1700.7, 'mvts_per_sec': 587.9, 'rss_gib': 2.186595916748047}

{'stage': 'B', 'buckets': '219/512', 'mvts': 1004463, 'detections': 979497, 'elapsed_sec': 1701.6, 'mvts_per_sec': 590.29, 'rss_gib': 2.186595916748047}

{'stage': 'B', 'buckets': '220/512', 'mvts': 1009068, 'detections': 983986, 'elapsed_sec': 1704.6, 'mvts_per_sec': 591.96, 'rss_gib': 2.186595916748047}

{'stage': 'B', 'buckets': '221/512', 'mvts': 1013546, 'detections': 988343, 'elapsed_sec': 1705.8, 'mvts_per_sec': 594.18, 'rss_gib': 2.186595916748047}

{'stage': 'B', 'buckets': '222/512', 'mvts': 1018248, 'detections': 992923, 'elapsed_sec': 1709.1, 'mvts_per_sec': 595.79, 'rss_gib': 2.186595916748047}

{'stage': 'B', 'buckets': '223/512', 'mvts': 1022770, 'detections': 997343, 'elapsed_sec': 1713.0, 'mvts_per_sec': 597.05, 'rss_gib': 2.186595916748047}

{'stage': 'B', 'buckets': '224/512', 'mvts': 1027135, 'detections': 1001593, 'elapsed_sec': 1718.8, 'mvts_per_sec': 597.6, 'rss_gib': 2.1865997314453125}

{'stage': 'B', 'buckets': '225/512', 'mvts': 1031706, 'detections': 1006054, 'elapsed_sec': 1719.1, 'mvts_per_sec': 600.15, 'rss_gib': 2.1865997314453125}

{'stage': 'B', 'buckets': '226/512', 'mvts': 1036192, 'detections': 1010423, 'elapsed_sec': 1721.9, 'mvts_per_sec': 601.76, 'rss_gib': 2.1865997314453125}

{'stage': 'B', 'buckets': '227/512', 'mvts': 1040858, 'detections': 1014975, 'elapsed_sec': 1726.9, 'mvts_per_sec': 602.73, 'rss_gib': 2.1865997314453125}

{'stage': 'B', 'buckets': '228/512', 'mvts': 1045447, 'detections': 1019448, 'elapsed_sec': 1730.8, 'mvts_per_sec': 604.02, 'rss_gib': 2.1865997314453125}

{'stage': 'B', 'buckets': '229/512', 'mvts': 1049986, 'detections': 1023868, 'elapsed_sec': 1733.6, 'mvts_per_sec': 605.66, 'rss_gib': 2.1865997314453125}

{'stage': 'B', 'buckets': '230/512', 'mvts': 1054521, 'detections': 1028270, 'elapsed_sec': 1734.0, 'mvts_per_sec': 608.14, 'rss_gib': 2.1865997314453125}

{'stage': 'B', 'buckets': '231/512', 'mvts': 1059191, 'detections': 1032806, 'elapsed_sec': 1755.4, 'mvts_per_sec': 603.39, 'rss_gib': 2.1865997314453125}

{'stage': 'B', 'buckets': '232/512', 'mvts': 1063758, 'detections': 1037253, 'elapsed_sec': 1757.0, 'mvts_per_sec': 605.45, 'rss_gib': 2.1865997314453125}

{'stage': 'B', 'buckets': '232/512', 'mvts': 1063758, 'detections': 1037253, 'elapsed_sec': 1787.0, 'mvts_per_sec': 595.28, 'rss_gib': 2.1865997314453125}

{'stage': 'B', 'buckets': '232/512', 'mvts': 1063758, 'detections': 1037253, 'elapsed_sec': 1817.0, 'mvts_per_sec': 585.45, 'rss_gib': 2.1865997314453125}

{'stage': 'B', 'buckets': '232/512', 'mvts': 1063758, 'detections': 1037253, 'elapsed_sec': 1847.0, 'mvts_per_sec': 575.94, 'rss_gib': 2.1865997314453125}

{'stage': 'B', 'buckets': '233/512', 'mvts': 1068420, 'detections': 1041833, 'elapsed_sec': 1866.2, 'mvts_per_sec': 572.51, 'rss_gib': 2.1865997314453125}

{'stage': 'B', 'buckets': '234/512', 'mvts': 1073050, 'detections': 1046353, 'elapsed_sec': 1876.5, 'mvts_per_sec': 571.82, 'rss_gib': 2.1865997314453125}

{'stage': 'B', 'buckets': '235/512', 'mvts': 1077497, 'detections': 1050686, 'elapsed_sec': 1880.2, 'mvts_per_sec': 573.09, 'rss_gib': 2.1865997314453125}

{'stage': 'B', 'buckets': '236/512', 'mvts': 1082076, 'detections': 1055135, 'elapsed_sec': 1881.9, 'mvts_per_sec': 574.99, 'rss_gib': 2.1865997314453125}

{'stage': 'B', 'buckets': '237/512', 'mvts': 1086737, 'detections': 1059670, 'elapsed_sec': 1889.3, 'mvts_per_sec': 575.2, 'rss_gib': 2.1865997314453125}

{'stage': 'B', 'buckets': '238/512', 'mvts': 1091292, 'detections': 1064113, 'elapsed_sec': 1889.4, 'mvts_per_sec': 577.58, 'rss_gib': 2.1865997314453125}

{'stage': 'B', 'buckets': '239/512', 'mvts': 1095721, 'detections': 1068439, 'elapsed_sec': 1890.4, 'mvts_per_sec': 579.61, 'rss_gib': 2.1865997314453125}

{'stage': 'B', 'buckets': '240/512', 'mvts': 1100362, 'detections': 1072958, 'elapsed_sec': 1891.2, 'mvts_per_sec': 581.84, 'rss_gib': 2.1865997314453125}

{'stage': 'B', 'buckets': '241/512', 'mvts': 1104921, 'detections': 1077422, 'elapsed_sec': 1895.6, 'mvts_per_sec': 582.9, 'rss_gib': 2.1865997314453125}

{'stage': 'B', 'buckets': '242/512', 'mvts': 1109583, 'detections': 1081973, 'elapsed_sec': 1901.6, 'mvts_per_sec': 583.5, 'rss_gib': 2.1865997314453125}

{'stage': 'B', 'buckets': '243/512', 'mvts': 1114121, 'detections': 1086398, 'elapsed_sec': 1904.2, 'mvts_per_sec': 585.08, 'rss_gib': 2.1865997314453125}

{'stage': 'B', 'buckets': '244/512', 'mvts': 1118667, 'detections': 1090839, 'elapsed_sec': 1904.6, 'mvts_per_sec': 587.36, 'rss_gib': 2.1865997314453125}

{'stage': 'B', 'buckets': '245/512', 'mvts': 1123245, 'detections': 1095303, 'elapsed_sec': 1907.3, 'mvts_per_sec': 588.91, 'rss_gib': 2.1865997314453125}

{'stage': 'B', 'buckets': '246/512', 'mvts': 1127868, 'detections': 1099824, 'elapsed_sec': 1907.4, 'mvts_per_sec': 591.31, 'rss_gib': 2.1865997314453125}

{'stage': 'B', 'buckets': '247/512', 'mvts': 1132459, 'detections': 1104309, 'elapsed_sec': 1910.7, 'mvts_per_sec': 592.69, 'rss_gib': 2.186614990234375}

{'stage': 'B', 'buckets': '248/512', 'mvts': 1137044, 'detections': 1108771, 'elapsed_sec': 1912.0, 'mvts_per_sec': 594.7, 'rss_gib': 2.186614990234375}

{'stage': 'B', 'buckets': '249/512', 'mvts': 1141566, 'detections': 1113178, 'elapsed_sec': 1914.9, 'mvts_per_sec': 596.16, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '250/512', 'mvts': 1146230, 'detections': 1117720, 'elapsed_sec': 1917.0, 'mvts_per_sec': 597.92, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '251/512', 'mvts': 1150875, 'detections': 1122254, 'elapsed_sec': 1921.3, 'mvts_per_sec': 599.02, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '252/512', 'mvts': 1155394, 'detections': 1126663, 'elapsed_sec': 1924.8, 'mvts_per_sec': 600.26, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '253/512', 'mvts': 1160011, 'detections': 1131143, 'elapsed_sec': 1931.6, 'mvts_per_sec': 600.55, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '254/512', 'mvts': 1164632, 'detections': 1135642, 'elapsed_sec': 1931.9, 'mvts_per_sec': 602.84, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '255/512', 'mvts': 1169270, 'detections': 1140154, 'elapsed_sec': 1932.9, 'mvts_per_sec': 604.93, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '256/512', 'mvts': 1173859, 'detections': 1144643, 'elapsed_sec': 1935.9, 'mvts_per_sec': 606.35, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '257/512', 'mvts': 1178467, 'detections': 1149140, 'elapsed_sec': 1939.8, 'mvts_per_sec': 607.53, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '258/512', 'mvts': 1183067, 'detections': 1153625, 'elapsed_sec': 1943.5, 'mvts_per_sec': 608.72, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '259/512', 'mvts': 1187578, 'detections': 1158012, 'elapsed_sec': 1943.8, 'mvts_per_sec': 610.95, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '260/512', 'mvts': 1192035, 'detections': 1162354, 'elapsed_sec': 1966.7, 'mvts_per_sec': 606.1, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '261/512', 'mvts': 1196594, 'detections': 1166788, 'elapsed_sec': 1973.3, 'mvts_per_sec': 606.39, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '261/512', 'mvts': 1196594, 'detections': 1166788, 'elapsed_sec': 2003.3, 'mvts_per_sec': 597.31, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '261/512', 'mvts': 1196594, 'detections': 1166788, 'elapsed_sec': 2033.3, 'mvts_per_sec': 588.5, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '261/512', 'mvts': 1196594, 'detections': 1166788, 'elapsed_sec': 2063.3, 'mvts_per_sec': 579.94, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '262/512', 'mvts': 1201068, 'detections': 1171157, 'elapsed_sec': 2077.1, 'mvts_per_sec': 578.25, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '263/512', 'mvts': 1205531, 'detections': 1175510, 'elapsed_sec': 2092.1, 'mvts_per_sec': 576.23, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '264/512', 'mvts': 1210113, 'detections': 1179997, 'elapsed_sec': 2095.9, 'mvts_per_sec': 577.36, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '265/512', 'mvts': 1214640, 'detections': 1184411, 'elapsed_sec': 2099.6, 'mvts_per_sec': 578.52, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '266/512', 'mvts': 1219239, 'detections': 1188911, 'elapsed_sec': 2099.6, 'mvts_per_sec': 580.69, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '267/512', 'mvts': 1223831, 'detections': 1193403, 'elapsed_sec': 2103.5, 'mvts_per_sec': 581.81, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '268/512', 'mvts': 1228393, 'detections': 1197848, 'elapsed_sec': 2103.8, 'mvts_per_sec': 583.88, 'rss_gib': 2.1865921020507812}

{'stage': 'B', 'buckets': '269/512', 'mvts': 1233090, 'detections': 1202434, 'elapsed_sec': 2105.5, 'mvts_per_sec': 585.67, 'rss_gib': 2.1865882873535156}

{'stage': 'B', 'buckets': '270/512', 'mvts': 1237683, 'detections': 1206904, 'elapsed_sec': 2109.9, 'mvts_per_sec': 586.6, 'rss_gib': 2.1865882873535156}

{'stage': 'B', 'buckets': '271/512', 'mvts': 1242343, 'detections': 1211466, 'elapsed_sec': 2112.2, 'mvts_per_sec': 588.19, 'rss_gib': 2.1865882873535156}

{'stage': 'B', 'buckets': '272/512', 'mvts': 1246860, 'detections': 1215850, 'elapsed_sec': 2115.1, 'mvts_per_sec': 589.51, 'rss_gib': 2.1865882873535156}

{'stage': 'B', 'buckets': '273/512', 'mvts': 1251523, 'detections': 1220400, 'elapsed_sec': 2118.0, 'mvts_per_sec': 590.89, 'rss_gib': 2.1865882873535156}

{'stage': 'B', 'buckets': '274/512', 'mvts': 1255931, 'detections': 1224715, 'elapsed_sec': 2120.7, 'mvts_per_sec': 592.23, 'rss_gib': 2.186595916748047}

{'stage': 'B', 'buckets': '275/512', 'mvts': 1260497, 'detections': 1229156, 'elapsed_sec': 2121.4, 'mvts_per_sec': 594.19, 'rss_gib': 2.1866607666015625}

{'stage': 'B', 'buckets': '276/512', 'mvts': 1265170, 'detections': 1233716, 'elapsed_sec': 2122.9, 'mvts_per_sec': 595.96, 'rss_gib': 2.1866607666015625}

{'stage': 'B', 'buckets': '277/512', 'mvts': 1269774, 'detections': 1238195, 'elapsed_sec': 2124.7, 'mvts_per_sec': 597.64, 'rss_gib': 2.1866607666015625}

{'stage': 'B', 'buckets': '278/512', 'mvts': 1274298, 'detections': 1242604, 'elapsed_sec': 2125.2, 'mvts_per_sec': 599.62, 'rss_gib': 2.1866607666015625}

{'stage': 'B', 'buckets': '279/512', 'mvts': 1278849, 'detections': 1247057, 'elapsed_sec': 2126.5, 'mvts_per_sec': 601.39, 'rss_gib': 2.1866607666015625}

{'stage': 'B', 'buckets': '280/512', 'mvts': 1283395, 'detections': 1251496, 'elapsed_sec': 2126.6, 'mvts_per_sec': 603.5, 'rss_gib': 2.1866607666015625}

{'stage': 'B', 'buckets': '281/512', 'mvts': 1288057, 'detections': 1256047, 'elapsed_sec': 2128.5, 'mvts_per_sec': 605.16, 'rss_gib': 2.1865386962890625}

{'stage': 'B', 'buckets': '282/512', 'mvts': 1292610, 'detections': 1260487, 'elapsed_sec': 2135.0, 'mvts_per_sec': 605.44, 'rss_gib': 2.1865386962890625}

{'stage': 'B', 'buckets': '283/512', 'mvts': 1297200, 'detections': 1264978, 'elapsed_sec': 2139.1, 'mvts_per_sec': 606.42, 'rss_gib': 2.1865386962890625}

{'stage': 'B', 'buckets': '284/512', 'mvts': 1301739, 'detections': 1269385, 'elapsed_sec': 2145.0, 'mvts_per_sec': 606.86, 'rss_gib': 2.1865386962890625}

{'stage': 'B', 'buckets': '285/512', 'mvts': 1306318, 'detections': 1273844, 'elapsed_sec': 2147.1, 'mvts_per_sec': 608.4, 'rss_gib': 2.1865386962890625}

{'stage': 'B', 'buckets': '286/512', 'mvts': 1310904, 'detections': 1278331, 'elapsed_sec': 2148.0, 'mvts_per_sec': 610.28, 'rss_gib': 2.1865386962890625}

{'stage': 'B', 'buckets': '287/512', 'mvts': 1315561, 'detections': 1282881, 'elapsed_sec': 2154.0, 'mvts_per_sec': 610.74, 'rss_gib': 2.1865386962890625}

{'stage': 'B', 'buckets': '288/512', 'mvts': 1320375, 'detections': 1287584, 'elapsed_sec': 2159.1, 'mvts_per_sec': 611.54, 'rss_gib': 2.1868209838867188}

{'stage': 'B', 'buckets': '288/512', 'mvts': 1320375, 'detections': 1287584, 'elapsed_sec': 2189.1, 'mvts_per_sec': 603.15, 'rss_gib': 2.1868209838867188}

{'stage': 'B', 'buckets': '289/512', 'mvts': 1324924, 'detections': 1292025, 'elapsed_sec': 2192.2, 'mvts_per_sec': 604.38, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '290/512', 'mvts': 1329638, 'detections': 1296625, 'elapsed_sec': 2192.7, 'mvts_per_sec': 606.4, 'rss_gib': 2.1868438720703125}

{'stage': 'B', 'buckets': '290/512', 'mvts': 1329638, 'detections': 1296625, 'elapsed_sec': 2222.7, 'mvts_per_sec': 598.21, 'rss_gib': 2.1868438720703125}

{'stage': 'B', 'buckets': '290/512', 'mvts': 1329638, 'detections': 1296625, 'elapsed_sec': 2252.7, 'mvts_per_sec': 590.24, 'rss_gib': 2.1868438720703125}

{'stage': 'B', 'buckets': '290/512', 'mvts': 1329638, 'detections': 1296625, 'elapsed_sec': 2282.8, 'mvts_per_sec': 582.45, 'rss_gib': 2.1868438720703125}

{'stage': 'B', 'buckets': '291/512', 'mvts': 1334326, 'detections': 1301186, 'elapsed_sec': 2282.9, 'mvts_per_sec': 584.49, 'rss_gib': 2.1868438720703125}

{'stage': 'B', 'buckets': '292/512', 'mvts': 1338878, 'detections': 1305632, 'elapsed_sec': 2290.6, 'mvts_per_sec': 584.5, 'rss_gib': 2.1868438720703125}

{'stage': 'B', 'buckets': '293/512', 'mvts': 1343417, 'detections': 1310064, 'elapsed_sec': 2314.8, 'mvts_per_sec': 580.35, 'rss_gib': 2.1868438720703125}

{'stage': 'B', 'buckets': '294/512', 'mvts': 1348092, 'detections': 1314603, 'elapsed_sec': 2315.8, 'mvts_per_sec': 582.12, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '295/512', 'mvts': 1352687, 'detections': 1319068, 'elapsed_sec': 2316.1, 'mvts_per_sec': 584.04, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '296/512', 'mvts': 1357332, 'detections': 1323601, 'elapsed_sec': 2316.7, 'mvts_per_sec': 585.9, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '297/512', 'mvts': 1361946, 'detections': 1328106, 'elapsed_sec': 2316.9, 'mvts_per_sec': 587.82, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '298/512', 'mvts': 1366444, 'detections': 1332492, 'elapsed_sec': 2318.6, 'mvts_per_sec': 589.34, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '299/512', 'mvts': 1371028, 'detections': 1336972, 'elapsed_sec': 2320.2, 'mvts_per_sec': 590.9, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '300/512', 'mvts': 1375588, 'detections': 1341411, 'elapsed_sec': 2323.5, 'mvts_per_sec': 592.04, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '301/512', 'mvts': 1380144, 'detections': 1345830, 'elapsed_sec': 2325.5, 'mvts_per_sec': 593.47, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '302/512', 'mvts': 1384662, 'detections': 1350249, 'elapsed_sec': 2329.9, 'mvts_per_sec': 594.29, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '303/512', 'mvts': 1389111, 'detections': 1354584, 'elapsed_sec': 2330.5, 'mvts_per_sec': 596.04, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '304/512', 'mvts': 1393652, 'detections': 1359015, 'elapsed_sec': 2330.9, 'mvts_per_sec': 597.9, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '305/512', 'mvts': 1398237, 'detections': 1363481, 'elapsed_sec': 2331.8, 'mvts_per_sec': 599.64, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '306/512', 'mvts': 1402833, 'detections': 1367958, 'elapsed_sec': 2334.4, 'mvts_per_sec': 600.94, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '307/512', 'mvts': 1407408, 'detections': 1372412, 'elapsed_sec': 2334.5, 'mvts_per_sec': 602.88, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '308/512', 'mvts': 1411943, 'detections': 1376830, 'elapsed_sec': 2339.6, 'mvts_per_sec': 603.5, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '309/512', 'mvts': 1416498, 'detections': 1381273, 'elapsed_sec': 2339.9, 'mvts_per_sec': 605.37, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '310/512', 'mvts': 1421140, 'detections': 1385793, 'elapsed_sec': 2341.9, 'mvts_per_sec': 606.83, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '311/512', 'mvts': 1425703, 'detections': 1390255, 'elapsed_sec': 2343.5, 'mvts_per_sec': 608.36, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '312/512', 'mvts': 1430296, 'detections': 1394739, 'elapsed_sec': 2344.1, 'mvts_per_sec': 610.16, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '313/512', 'mvts': 1434831, 'detections': 1399172, 'elapsed_sec': 2350.2, 'mvts_per_sec': 610.52, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '314/512', 'mvts': 1439397, 'detections': 1403630, 'elapsed_sec': 2358.9, 'mvts_per_sec': 610.2, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '315/512', 'mvts': 1443950, 'detections': 1408067, 'elapsed_sec': 2364.8, 'mvts_per_sec': 610.61, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '316/512', 'mvts': 1448552, 'detections': 1412575, 'elapsed_sec': 2367.0, 'mvts_per_sec': 611.98, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '317/512', 'mvts': 1453032, 'detections': 1416943, 'elapsed_sec': 2371.4, 'mvts_per_sec': 612.73, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '317/512', 'mvts': 1453032, 'detections': 1416943, 'elapsed_sec': 2401.4, 'mvts_per_sec': 605.08, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '318/512', 'mvts': 1457702, 'detections': 1421480, 'elapsed_sec': 2410.8, 'mvts_per_sec': 604.66, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '319/512', 'mvts': 1462378, 'detections': 1426054, 'elapsed_sec': 2411.2, 'mvts_per_sec': 606.48, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '319/512', 'mvts': 1462378, 'detections': 1426054, 'elapsed_sec': 2441.2, 'mvts_per_sec': 599.03, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '319/512', 'mvts': 1462378, 'detections': 1426054, 'elapsed_sec': 2471.2, 'mvts_per_sec': 591.76, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '320/512', 'mvts': 1466929, 'detections': 1430469, 'elapsed_sec': 2488.5, 'mvts_per_sec': 589.48, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '321/512', 'mvts': 1471437, 'detections': 1434870, 'elapsed_sec': 2489.1, 'mvts_per_sec': 591.16, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '322/512', 'mvts': 1476065, 'detections': 1439390, 'elapsed_sec': 2516.9, 'mvts_per_sec': 586.45, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '323/512', 'mvts': 1480587, 'detections': 1443808, 'elapsed_sec': 2523.8, 'mvts_per_sec': 586.64, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '324/512', 'mvts': 1485214, 'detections': 1448311, 'elapsed_sec': 2526.4, 'mvts_per_sec': 587.89, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '325/512', 'mvts': 1489640, 'detections': 1452633, 'elapsed_sec': 2526.7, 'mvts_per_sec': 589.56, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '326/512', 'mvts': 1494202, 'detections': 1457078, 'elapsed_sec': 2531.9, 'mvts_per_sec': 590.15, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '327/512', 'mvts': 1498873, 'detections': 1461642, 'elapsed_sec': 2532.2, 'mvts_per_sec': 591.92, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '328/512', 'mvts': 1503401, 'detections': 1466042, 'elapsed_sec': 2534.1, 'mvts_per_sec': 593.26, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '329/512', 'mvts': 1507924, 'detections': 1470465, 'elapsed_sec': 2535.3, 'mvts_per_sec': 594.77, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '330/512', 'mvts': 1512511, 'detections': 1474929, 'elapsed_sec': 2537.4, 'mvts_per_sec': 596.08, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '331/512', 'mvts': 1517112, 'detections': 1479422, 'elapsed_sec': 2540.0, 'mvts_per_sec': 597.29, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '332/512', 'mvts': 1521756, 'detections': 1483942, 'elapsed_sec': 2540.7, 'mvts_per_sec': 598.94, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '333/512', 'mvts': 1526476, 'detections': 1488559, 'elapsed_sec': 2544.0, 'mvts_per_sec': 600.02, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '334/512', 'mvts': 1531023, 'detections': 1493004, 'elapsed_sec': 2545.0, 'mvts_per_sec': 601.58, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '335/512', 'mvts': 1535576, 'detections': 1497446, 'elapsed_sec': 2545.6, 'mvts_per_sec': 603.22, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '336/512', 'mvts': 1540170, 'detections': 1501934, 'elapsed_sec': 2545.7, 'mvts_per_sec': 605.0, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '337/512', 'mvts': 1544687, 'detections': 1506329, 'elapsed_sec': 2548.7, 'mvts_per_sec': 606.07, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '338/512', 'mvts': 1549242, 'detections': 1510772, 'elapsed_sec': 2551.0, 'mvts_per_sec': 607.31, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '339/512', 'mvts': 1553925, 'detections': 1515331, 'elapsed_sec': 2556.0, 'mvts_per_sec': 607.95, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '340/512', 'mvts': 1558430, 'detections': 1519710, 'elapsed_sec': 2556.7, 'mvts_per_sec': 609.56, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '341/512', 'mvts': 1562951, 'detections': 1524127, 'elapsed_sec': 2558.1, 'mvts_per_sec': 610.98, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '342/512', 'mvts': 1567591, 'detections': 1528647, 'elapsed_sec': 2562.9, 'mvts_per_sec': 611.64, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '343/512', 'mvts': 1572103, 'detections': 1533043, 'elapsed_sec': 2569.3, 'mvts_per_sec': 611.87, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '344/512', 'mvts': 1576734, 'detections': 1537563, 'elapsed_sec': 2574.7, 'mvts_per_sec': 612.4, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '345/512', 'mvts': 1581215, 'detections': 1541946, 'elapsed_sec': 2582.0, 'mvts_per_sec': 612.41, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '346/512', 'mvts': 1585750, 'detections': 1546367, 'elapsed_sec': 2584.6, 'mvts_per_sec': 613.53, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '346/512', 'mvts': 1585750, 'detections': 1546367, 'elapsed_sec': 2614.6, 'mvts_per_sec': 606.49, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '347/512', 'mvts': 1590338, 'detections': 1550827, 'elapsed_sec': 2625.8, 'mvts_per_sec': 605.66, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '348/512', 'mvts': 1594825, 'detections': 1555211, 'elapsed_sec': 2628.6, 'mvts_per_sec': 606.73, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '348/512', 'mvts': 1594825, 'detections': 1555211, 'elapsed_sec': 2658.6, 'mvts_per_sec': 599.88, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '348/512', 'mvts': 1594825, 'detections': 1555211, 'elapsed_sec': 2688.6, 'mvts_per_sec': 593.19, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '349/512', 'mvts': 1599391, 'detections': 1559657, 'elapsed_sec': 2691.4, 'mvts_per_sec': 594.25, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '350/512', 'mvts': 1604000, 'detections': 1564165, 'elapsed_sec': 2708.3, 'mvts_per_sec': 592.26, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '351/512', 'mvts': 1608507, 'detections': 1568581, 'elapsed_sec': 2721.7, 'mvts_per_sec': 590.99, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '352/512', 'mvts': 1613135, 'detections': 1573108, 'elapsed_sec': 2730.8, 'mvts_per_sec': 590.73, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '353/512', 'mvts': 1617697, 'detections': 1577562, 'elapsed_sec': 2731.9, 'mvts_per_sec': 592.15, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '354/512', 'mvts': 1622364, 'detections': 1582116, 'elapsed_sec': 2739.4, 'mvts_per_sec': 592.24, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '355/512', 'mvts': 1626893, 'detections': 1586545, 'elapsed_sec': 2742.4, 'mvts_per_sec': 593.24, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '356/512', 'mvts': 1631483, 'detections': 1591019, 'elapsed_sec': 2742.5, 'mvts_per_sec': 594.9, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '357/512', 'mvts': 1636144, 'detections': 1595576, 'elapsed_sec': 2744.8, 'mvts_per_sec': 596.09, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '358/512', 'mvts': 1640638, 'detections': 1599969, 'elapsed_sec': 2745.6, 'mvts_per_sec': 597.56, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '359/512', 'mvts': 1645303, 'detections': 1604506, 'elapsed_sec': 2746.3, 'mvts_per_sec': 599.09, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '360/512', 'mvts': 1649879, 'detections': 1608976, 'elapsed_sec': 2747.5, 'mvts_per_sec': 600.51, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '361/512', 'mvts': 1654436, 'detections': 1613415, 'elapsed_sec': 2750.1, 'mvts_per_sec': 601.6, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '362/512', 'mvts': 1659062, 'detections': 1617936, 'elapsed_sec': 2756.1, 'mvts_per_sec': 601.96, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '363/512', 'mvts': 1663636, 'detections': 1622405, 'elapsed_sec': 2757.0, 'mvts_per_sec': 603.43, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '364/512', 'mvts': 1668178, 'detections': 1626818, 'elapsed_sec': 2758.6, 'mvts_per_sec': 604.72, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '365/512', 'mvts': 1672642, 'detections': 1631176, 'elapsed_sec': 2760.1, 'mvts_per_sec': 606.01, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '366/512', 'mvts': 1677235, 'detections': 1635644, 'elapsed_sec': 2765.7, 'mvts_per_sec': 606.45, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '367/512', 'mvts': 1681796, 'detections': 1640090, 'elapsed_sec': 2768.2, 'mvts_per_sec': 607.55, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '368/512', 'mvts': 1686449, 'detections': 1644637, 'elapsed_sec': 2770.7, 'mvts_per_sec': 608.67, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '369/512', 'mvts': 1691068, 'detections': 1649122, 'elapsed_sec': 2776.2, 'mvts_per_sec': 609.14, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '370/512', 'mvts': 1695566, 'detections': 1653516, 'elapsed_sec': 2777.9, 'mvts_per_sec': 610.37, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '371/512', 'mvts': 1700181, 'detections': 1658019, 'elapsed_sec': 2778.4, 'mvts_per_sec': 611.93, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '372/512', 'mvts': 1704906, 'detections': 1662608, 'elapsed_sec': 2780.4, 'mvts_per_sec': 613.18, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '373/512', 'mvts': 1709500, 'detections': 1667090, 'elapsed_sec': 2784.4, 'mvts_per_sec': 613.97, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '374/512', 'mvts': 1713949, 'detections': 1671427, 'elapsed_sec': 2792.5, 'mvts_per_sec': 613.77, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '375/512', 'mvts': 1718566, 'detections': 1675949, 'elapsed_sec': 2792.6, 'mvts_per_sec': 615.4, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '375/512', 'mvts': 1718566, 'detections': 1675949, 'elapsed_sec': 2822.6, 'mvts_per_sec': 608.86, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '376/512', 'mvts': 1723148, 'detections': 1680411, 'elapsed_sec': 2838.0, 'mvts_per_sec': 607.17, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '377/512', 'mvts': 1727718, 'detections': 1684875, 'elapsed_sec': 2846.7, 'mvts_per_sec': 606.92, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '377/512', 'mvts': 1727718, 'detections': 1684875, 'elapsed_sec': 2876.7, 'mvts_per_sec': 600.59, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '378/512', 'mvts': 1732241, 'detections': 1689287, 'elapsed_sec': 2899.0, 'mvts_per_sec': 597.52, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '379/512', 'mvts': 1736842, 'detections': 1693779, 'elapsed_sec': 2928.7, 'mvts_per_sec': 593.04, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '380/512', 'mvts': 1741496, 'detections': 1698283, 'elapsed_sec': 2935.4, 'mvts_per_sec': 593.27, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '381/512', 'mvts': 1746026, 'detections': 1702693, 'elapsed_sec': 2936.5, 'mvts_per_sec': 594.59, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '382/512', 'mvts': 1750601, 'detections': 1707154, 'elapsed_sec': 2943.2, 'mvts_per_sec': 594.79, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '383/512', 'mvts': 1755132, 'detections': 1711550, 'elapsed_sec': 2948.2, 'mvts_per_sec': 595.32, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '384/512', 'mvts': 1759765, 'detections': 1716061, 'elapsed_sec': 2951.4, 'mvts_per_sec': 596.25, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '385/512', 'mvts': 1764421, 'detections': 1720606, 'elapsed_sec': 2952.5, 'mvts_per_sec': 597.61, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '386/512', 'mvts': 1769029, 'detections': 1725081, 'elapsed_sec': 2952.9, 'mvts_per_sec': 599.09, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '387/512', 'mvts': 1773572, 'detections': 1729507, 'elapsed_sec': 2955.8, 'mvts_per_sec': 600.02, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '388/512', 'mvts': 1778147, 'detections': 1733971, 'elapsed_sec': 2957.3, 'mvts_per_sec': 601.28, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '389/512', 'mvts': 1782766, 'detections': 1738470, 'elapsed_sec': 2957.4, 'mvts_per_sec': 602.83, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '390/512', 'mvts': 1787261, 'detections': 1742867, 'elapsed_sec': 2958.3, 'mvts_per_sec': 604.15, 'rss_gib': 2.1868362426757812}

{'stage': 'B', 'buckets': '391/512', 'mvts': 1791831, 'detections': 1747327, 'elapsed_sec': 2960.9, 'mvts_per_sec': 605.16, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '392/512', 'mvts': 1796346, 'detections': 1751742, 'elapsed_sec': 2965.1, 'mvts_per_sec': 605.83, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '393/512', 'mvts': 1800920, 'detections': 1756202, 'elapsed_sec': 2968.9, 'mvts_per_sec': 606.59, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '394/512', 'mvts': 1805562, 'detections': 1760722, 'elapsed_sec': 2973.9, 'mvts_per_sec': 607.13, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '395/512', 'mvts': 1810039, 'detections': 1765075, 'elapsed_sec': 2974.0, 'mvts_per_sec': 608.62, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '396/512', 'mvts': 1814579, 'detections': 1769518, 'elapsed_sec': 2980.8, 'mvts_per_sec': 608.75, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '397/512', 'mvts': 1819091, 'detections': 1773926, 'elapsed_sec': 2981.7, 'mvts_per_sec': 610.08, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '398/512', 'mvts': 1823671, 'detections': 1778410, 'elapsed_sec': 2987.5, 'mvts_per_sec': 610.43, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '399/512', 'mvts': 1828264, 'detections': 1782899, 'elapsed_sec': 2989.4, 'mvts_per_sec': 611.59, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '400/512', 'mvts': 1832798, 'detections': 1787330, 'elapsed_sec': 2991.6, 'mvts_per_sec': 612.64, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '401/512', 'mvts': 1837342, 'detections': 1791769, 'elapsed_sec': 2994.4, 'mvts_per_sec': 613.59, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '402/512', 'mvts': 1841858, 'detections': 1796196, 'elapsed_sec': 3000.9, 'mvts_per_sec': 613.76, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '403/512', 'mvts': 1846640, 'detections': 1800866, 'elapsed_sec': 3004.8, 'mvts_per_sec': 614.57, 'rss_gib': 2.186840057373047}

{'stage': 'B', 'buckets': '404/512', 'mvts': 1851376, 'detections': 1805465, 'elapsed_sec': 3017.1, 'mvts_per_sec': 613.63, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '404/512', 'mvts': 1851376, 'detections': 1805465, 'elapsed_sec': 3047.1, 'mvts_per_sec': 607.58, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '405/512', 'mvts': 1855947, 'detections': 1809936, 'elapsed_sec': 3053.8, 'mvts_per_sec': 607.75, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '406/512', 'mvts': 1860448, 'detections': 1814335, 'elapsed_sec': 3065.2, 'mvts_per_sec': 606.97, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '406/512', 'mvts': 1860448, 'detections': 1814335, 'elapsed_sec': 3095.2, 'mvts_per_sec': 601.08, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '407/512', 'mvts': 1865009, 'detections': 1818790, 'elapsed_sec': 3112.6, 'mvts_per_sec': 599.19, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '408/512', 'mvts': 1869605, 'detections': 1823282, 'elapsed_sec': 3141.6, 'mvts_per_sec': 595.11, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '409/512', 'mvts': 1874191, 'detections': 1827757, 'elapsed_sec': 3144.0, 'mvts_per_sec': 596.11, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '410/512', 'mvts': 1878860, 'detections': 1832309, 'elapsed_sec': 3151.9, 'mvts_per_sec': 596.11, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '411/512', 'mvts': 1883397, 'detections': 1836719, 'elapsed_sec': 3157.5, 'mvts_per_sec': 596.49, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '412/512', 'mvts': 1887855, 'detections': 1841047, 'elapsed_sec': 3159.2, 'mvts_per_sec': 597.57, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '413/512', 'mvts': 1892387, 'detections': 1845475, 'elapsed_sec': 3163.2, 'mvts_per_sec': 598.25, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '414/512', 'mvts': 1897056, 'detections': 1850038, 'elapsed_sec': 3163.3, 'mvts_per_sec': 599.71, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '415/512', 'mvts': 1901611, 'detections': 1854464, 'elapsed_sec': 3164.4, 'mvts_per_sec': 600.93, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '416/512', 'mvts': 1906248, 'detections': 1858981, 'elapsed_sec': 3164.7, 'mvts_per_sec': 602.35, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '417/512', 'mvts': 1910871, 'detections': 1863502, 'elapsed_sec': 3166.3, 'mvts_per_sec': 603.5, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '418/512', 'mvts': 1915474, 'detections': 1867984, 'elapsed_sec': 3166.4, 'mvts_per_sec': 604.94, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '419/512', 'mvts': 1919983, 'detections': 1872386, 'elapsed_sec': 3167.9, 'mvts_per_sec': 606.07, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '420/512', 'mvts': 1924600, 'detections': 1876886, 'elapsed_sec': 3168.7, 'mvts_per_sec': 607.38, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '421/512', 'mvts': 1929207, 'detections': 1881366, 'elapsed_sec': 3169.0, 'mvts_per_sec': 608.77, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '422/512', 'mvts': 1933868, 'detections': 1885911, 'elapsed_sec': 3181.7, 'mvts_per_sec': 607.81, 'rss_gib': 2.186847686767578}

{'stage': 'B', 'buckets': '423/512', 'mvts': 1938497, 'detections': 1890449, 'elapsed_sec': 3182.6, 'mvts_per_sec': 609.08, 'rss_gib': 2.186847686767578}

{'stage': 'B', 'buckets': '424/512', 'mvts': 1943002, 'detections': 1894831, 'elapsed_sec': 3186.4, 'mvts_per_sec': 609.78, 'rss_gib': 2.186847686767578}

{'stage': 'B', 'buckets': '425/512', 'mvts': 1947569, 'detections': 1899308, 'elapsed_sec': 3187.5, 'mvts_per_sec': 611.01, 'rss_gib': 2.186847686767578}

{'stage': 'B', 'buckets': '426/512', 'mvts': 1952083, 'detections': 1903707, 'elapsed_sec': 3188.0, 'mvts_per_sec': 612.32, 'rss_gib': 2.186847686767578}

{'stage': 'B', 'buckets': '427/512', 'mvts': 1956556, 'detections': 1908081, 'elapsed_sec': 3197.2, 'mvts_per_sec': 611.95, 'rss_gib': 2.186847686767578}

{'stage': 'B', 'buckets': '428/512', 'mvts': 1961112, 'detections': 1912517, 'elapsed_sec': 3203.4, 'mvts_per_sec': 612.2, 'rss_gib': 2.186847686767578}

{'stage': 'B', 'buckets': '429/512', 'mvts': 1965642, 'detections': 1916934, 'elapsed_sec': 3204.5, 'mvts_per_sec': 613.4, 'rss_gib': 2.186847686767578}

{'stage': 'B', 'buckets': '430/512', 'mvts': 1970330, 'detections': 1921527, 'elapsed_sec': 3209.1, 'mvts_per_sec': 613.98, 'rss_gib': 2.186847686767578}

{'stage': 'B', 'buckets': '431/512', 'mvts': 1974905, 'detections': 1925989, 'elapsed_sec': 3211.8, 'mvts_per_sec': 614.89, 'rss_gib': 2.186847686767578}

{'stage': 'B', 'buckets': '432/512', 'mvts': 1979487, 'detections': 1930450, 'elapsed_sec': 3225.4, 'mvts_per_sec': 613.72, 'rss_gib': 2.186847686767578}

{'stage': 'B', 'buckets': '433/512', 'mvts': 1984086, 'detections': 1934951, 'elapsed_sec': 3231.6, 'mvts_per_sec': 613.96, 'rss_gib': 2.186847686767578}

{'stage': 'B', 'buckets': '433/512', 'mvts': 1984086, 'detections': 1934951, 'elapsed_sec': 3261.6, 'mvts_per_sec': 608.32, 'rss_gib': 2.186847686767578}

{'stage': 'B', 'buckets': '434/512', 'mvts': 1988696, 'detections': 1939458, 'elapsed_sec': 3267.2, 'mvts_per_sec': 608.68, 'rss_gib': 2.186847686767578}

{'stage': 'B', 'buckets': '435/512', 'mvts': 1993244, 'detections': 1943890, 'elapsed_sec': 3285.1, 'mvts_per_sec': 606.75, 'rss_gib': 2.1868629455566406}

{'stage': 'B', 'buckets': '435/512', 'mvts': 1993244, 'detections': 1943890, 'elapsed_sec': 3315.1, 'mvts_per_sec': 601.26, 'rss_gib': 2.1868629455566406}

{'stage': 'B', 'buckets': '436/512', 'mvts': 1997835, 'detections': 1948371, 'elapsed_sec': 3325.0, 'mvts_per_sec': 600.85, 'rss_gib': 2.1868629455566406}

{'stage': 'B', 'buckets': '437/512', 'mvts': 2002452, 'detections': 1952873, 'elapsed_sec': 3350.9, 'mvts_per_sec': 597.58, 'rss_gib': 2.1868629455566406}

{'stage': 'B', 'buckets': '438/512', 'mvts': 2007066, 'detections': 1957364, 'elapsed_sec': 3354.6, 'mvts_per_sec': 598.3, 'rss_gib': 2.1868629455566406}

{'stage': 'B', 'buckets': '439/512', 'mvts': 2011687, 'detections': 1961849, 'elapsed_sec': 3357.1, 'mvts_per_sec': 599.23, 'rss_gib': 2.1868629455566406}

{'stage': 'B', 'buckets': '440/512', 'mvts': 2016232, 'detections': 1966270, 'elapsed_sec': 3365.0, 'mvts_per_sec': 599.17, 'rss_gib': 2.1868629455566406}

{'stage': 'B', 'buckets': '441/512', 'mvts': 2020814, 'detections': 1970732, 'elapsed_sec': 3367.5, 'mvts_per_sec': 600.09, 'rss_gib': 2.1868629455566406}

{'stage': 'B', 'buckets': '442/512', 'mvts': 2025422, 'detections': 1975227, 'elapsed_sec': 3371.5, 'mvts_per_sec': 600.74, 'rss_gib': 2.1868629455566406}

{'stage': 'B', 'buckets': '443/512', 'mvts': 2029962, 'detections': 1979654, 'elapsed_sec': 3374.4, 'mvts_per_sec': 601.58, 'rss_gib': 2.1868629455566406}

{'stage': 'B', 'buckets': '444/512', 'mvts': 2034658, 'detections': 1984248, 'elapsed_sec': 3376.8, 'mvts_per_sec': 602.55, 'rss_gib': 2.1868629455566406}

{'stage': 'B', 'buckets': '445/512', 'mvts': 2039219, 'detections': 1988691, 'elapsed_sec': 3377.2, 'mvts_per_sec': 603.81, 'rss_gib': 2.1868629455566406}

{'stage': 'B', 'buckets': '446/512', 'mvts': 2043742, 'detections': 1993099, 'elapsed_sec': 3380.1, 'mvts_per_sec': 604.64, 'rss_gib': 2.1868629455566406}

{'stage': 'B', 'buckets': '447/512', 'mvts': 2048384, 'detections': 1997637, 'elapsed_sec': 3381.0, 'mvts_per_sec': 605.85, 'rss_gib': 2.1868629455566406}

{'stage': 'B', 'buckets': '448/512', 'mvts': 2052978, 'detections': 2002116, 'elapsed_sec': 3382.8, 'mvts_per_sec': 606.89, 'rss_gib': 2.1868629455566406}

{'stage': 'B', 'buckets': '449/512', 'mvts': 2057564, 'detections': 2006582, 'elapsed_sec': 3385.9, 'mvts_per_sec': 607.68, 'rss_gib': 2.1868629455566406}

{'stage': 'B', 'buckets': '450/512', 'mvts': 2062022, 'detections': 2010932, 'elapsed_sec': 3386.0, 'mvts_per_sec': 608.98, 'rss_gib': 2.1868629455566406}

{'stage': 'B', 'buckets': '451/512', 'mvts': 2066628, 'detections': 2015437, 'elapsed_sec': 3390.3, 'mvts_per_sec': 609.58, 'rss_gib': 2.1868629455566406}

{'stage': 'B', 'buckets': '452/512', 'mvts': 2071231, 'detections': 2019928, 'elapsed_sec': 3395.0, 'mvts_per_sec': 610.07, 'rss_gib': 2.1868629455566406}

{'stage': 'B', 'buckets': '453/512', 'mvts': 2075785, 'detections': 2024374, 'elapsed_sec': 3397.3, 'mvts_per_sec': 611.01, 'rss_gib': 2.1868629455566406}

{'stage': 'B', 'buckets': '454/512', 'mvts': 2080383, 'detections': 2028857, 'elapsed_sec': 3399.2, 'mvts_per_sec': 612.02, 'rss_gib': 2.1868629455566406}

{'stage': 'B', 'buckets': '455/512', 'mvts': 2084994, 'detections': 2033363, 'elapsed_sec': 3402.1, 'mvts_per_sec': 612.85, 'rss_gib': 2.1868629455566406}

{'stage': 'B', 'buckets': '456/512', 'mvts': 2089522, 'detections': 2037772, 'elapsed_sec': 3403.6, 'mvts_per_sec': 613.92, 'rss_gib': 2.1868629455566406}

{'stage': 'B', 'buckets': '457/512', 'mvts': 2094031, 'detections': 2042160, 'elapsed_sec': 3415.3, 'mvts_per_sec': 613.13, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '458/512', 'mvts': 2098659, 'detections': 2046676, 'elapsed_sec': 3421.2, 'mvts_per_sec': 613.42, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '459/512', 'mvts': 2103216, 'detections': 2051123, 'elapsed_sec': 3422.8, 'mvts_per_sec': 614.48, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '460/512', 'mvts': 2107767, 'detections': 2055559, 'elapsed_sec': 3432.7, 'mvts_per_sec': 614.03, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '461/512', 'mvts': 2112402, 'detections': 2060083, 'elapsed_sec': 3451.0, 'mvts_per_sec': 612.11, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '462/512', 'mvts': 2117132, 'detections': 2064689, 'elapsed_sec': 3455.3, 'mvts_per_sec': 612.72, 'rss_gib': 2.186847686767578}

{'stage': 'B', 'buckets': '462/512', 'mvts': 2117132, 'detections': 2064689, 'elapsed_sec': 3485.3, 'mvts_per_sec': 607.45, 'rss_gib': 2.186847686767578}

{'stage': 'B', 'buckets': '463/512', 'mvts': 2121843, 'detections': 2069288, 'elapsed_sec': 3503.4, 'mvts_per_sec': 605.66, 'rss_gib': 2.186847686767578}

{'stage': 'B', 'buckets': '464/512', 'mvts': 2126365, 'detections': 2073698, 'elapsed_sec': 3513.0, 'mvts_per_sec': 605.29, 'rss_gib': 2.186847686767578}

{'stage': 'B', 'buckets': '465/512', 'mvts': 2130908, 'detections': 2078119, 'elapsed_sec': 3541.6, 'mvts_per_sec': 601.69, 'rss_gib': 2.186847686767578}

{'stage': 'B', 'buckets': '466/512', 'mvts': 2135438, 'detections': 2082537, 'elapsed_sec': 3557.6, 'mvts_per_sec': 600.25, 'rss_gib': 2.186847686767578}

{'stage': 'B', 'buckets': '467/512', 'mvts': 2139933, 'detections': 2086902, 'elapsed_sec': 3563.0, 'mvts_per_sec': 600.59, 'rss_gib': 2.186847686767578}

{'stage': 'B', 'buckets': '468/512', 'mvts': 2144616, 'detections': 2091456, 'elapsed_sec': 3566.0, 'mvts_per_sec': 601.41, 'rss_gib': 2.186847686767578}

{'stage': 'B', 'buckets': '469/512', 'mvts': 2149210, 'detections': 2095926, 'elapsed_sec': 3574.3, 'mvts_per_sec': 601.3, 'rss_gib': 2.186847686767578}

{'stage': 'B', 'buckets': '470/512', 'mvts': 2153797, 'detections': 2100419, 'elapsed_sec': 3580.4, 'mvts_per_sec': 601.54, 'rss_gib': 2.186847686767578}

{'stage': 'B', 'buckets': '471/512', 'mvts': 2158339, 'detections': 2104847, 'elapsed_sec': 3582.4, 'mvts_per_sec': 602.48, 'rss_gib': 2.186847686767578}

{'stage': 'B', 'buckets': '472/512', 'mvts': 2162913, 'detections': 2109299, 'elapsed_sec': 3588.0, 'mvts_per_sec': 602.82, 'rss_gib': 2.186847686767578}

{'stage': 'B', 'buckets': '473/512', 'mvts': 2167425, 'detections': 2113706, 'elapsed_sec': 3592.3, 'mvts_per_sec': 603.35, 'rss_gib': 2.186847686767578}

{'stage': 'B', 'buckets': '474/512', 'mvts': 2172002, 'detections': 2118184, 'elapsed_sec': 3594.1, 'mvts_per_sec': 604.32, 'rss_gib': 2.186847686767578}

{'stage': 'B', 'buckets': '475/512', 'mvts': 2176546, 'detections': 2122625, 'elapsed_sec': 3598.9, 'mvts_per_sec': 604.78, 'rss_gib': 2.186847686767578}

{'stage': 'B', 'buckets': '476/512', 'mvts': 2181227, 'detections': 2127193, 'elapsed_sec': 3599.7, 'mvts_per_sec': 605.95, 'rss_gib': 2.186847686767578}

{'stage': 'B', 'buckets': '477/512', 'mvts': 2185774, 'detections': 2131618, 'elapsed_sec': 3602.5, 'mvts_per_sec': 606.74, 'rss_gib': 2.186847686767578}

{'stage': 'B', 'buckets': '478/512', 'mvts': 2190376, 'detections': 2136101, 'elapsed_sec': 3604.6, 'mvts_per_sec': 607.65, 'rss_gib': 2.186847686767578}

{'stage': 'B', 'buckets': '479/512', 'mvts': 2195120, 'detections': 2140733, 'elapsed_sec': 3608.6, 'mvts_per_sec': 608.3, 'rss_gib': 2.186847686767578}

{'stage': 'B', 'buckets': '480/512', 'mvts': 2199818, 'detections': 2145320, 'elapsed_sec': 3609.1, 'mvts_per_sec': 609.51, 'rss_gib': 2.1868629455566406}

{'stage': 'B', 'buckets': '481/512', 'mvts': 2204510, 'detections': 2149883, 'elapsed_sec': 3610.6, 'mvts_per_sec': 610.56, 'rss_gib': 2.1868629455566406}

{'stage': 'B', 'buckets': '482/512', 'mvts': 2208925, 'detections': 2154195, 'elapsed_sec': 3611.5, 'mvts_per_sec': 611.64, 'rss_gib': 2.1868629455566406}

{'stage': 'B', 'buckets': '483/512', 'mvts': 2213506, 'detections': 2158663, 'elapsed_sec': 3615.1, 'mvts_per_sec': 612.29, 'rss_gib': 2.1868629455566406}

{'stage': 'B', 'buckets': '484/512', 'mvts': 2218052, 'detections': 2163088, 'elapsed_sec': 3617.3, 'mvts_per_sec': 613.17, 'rss_gib': 2.1868629455566406}

{'stage': 'B', 'buckets': '485/512', 'mvts': 2222703, 'detections': 2167623, 'elapsed_sec': 3622.2, 'mvts_per_sec': 613.63, 'rss_gib': 2.1868629455566406}

{'stage': 'B', 'buckets': '486/512', 'mvts': 2227289, 'detections': 2172067, 'elapsed_sec': 3626.7, 'mvts_per_sec': 614.14, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '487/512', 'mvts': 2231864, 'detections': 2176522, 'elapsed_sec': 3638.9, 'mvts_per_sec': 613.34, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '488/512', 'mvts': 2236496, 'detections': 2181045, 'elapsed_sec': 3652.2, 'mvts_per_sec': 612.37, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '489/512', 'mvts': 2241171, 'detections': 2185591, 'elapsed_sec': 3654.9, 'mvts_per_sec': 613.2, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '490/512', 'mvts': 2245609, 'detections': 2189910, 'elapsed_sec': 3657.7, 'mvts_per_sec': 613.93, 'rss_gib': 2.1868515014648438}

{'stage': 'B', 'buckets': '491/512', 'mvts': 2250101, 'detections': 2194306, 'elapsed_sec': 3660.4, 'mvts_per_sec': 614.71, 'rss_gib': 2.1868743896484375}

{'stage': 'B', 'buckets': '491/512', 'mvts': 2250101, 'detections': 2194306, 'elapsed_sec': 3690.4, 'mvts_per_sec': 609.71, 'rss_gib': 2.1868743896484375}

{'stage': 'B', 'buckets': '492/512', 'mvts': 2254780, 'detections': 2198860, 'elapsed_sec': 3711.7, 'mvts_per_sec': 607.48, 'rss_gib': 2.1868743896484375}

{'stage': 'B', 'buckets': '493/512', 'mvts': 2259423, 'detections': 2203385, 'elapsed_sec': 3726.2, 'mvts_per_sec': 606.37, 'rss_gib': 2.1868743896484375}

{'stage': 'B', 'buckets': '494/512', 'mvts': 2264196, 'detections': 2208040, 'elapsed_sec': 3739.6, 'mvts_per_sec': 605.46, 'rss_gib': 2.1868743896484375}

{'stage': 'B', 'buckets': '495/512', 'mvts': 2268673, 'detections': 2212401, 'elapsed_sec': 3750.0, 'mvts_per_sec': 604.98, 'rss_gib': 2.1868743896484375}

{'stage': 'B', 'buckets': '496/512', 'mvts': 2273285, 'detections': 2216900, 'elapsed_sec': 3751.4, 'mvts_per_sec': 605.98, 'rss_gib': 2.1868743896484375}

{'stage': 'B', 'buckets': '497/512', 'mvts': 2277793, 'detections': 2221300, 'elapsed_sec': 3754.9, 'mvts_per_sec': 606.61, 'rss_gib': 2.1868743896484375}

{'stage': 'B', 'buckets': '498/512', 'mvts': 2282265, 'detections': 2225662, 'elapsed_sec': 3756.8, 'mvts_per_sec': 607.51, 'rss_gib': 2.1868743896484375}

{'stage': 'B', 'buckets': '499/512', 'mvts': 2286900, 'detections': 2230180, 'elapsed_sec': 3758.2, 'mvts_per_sec': 608.51, 'rss_gib': 2.1868743896484375}

{'stage': 'B', 'buckets': '500/512', 'mvts': 2291394, 'detections': 2234569, 'elapsed_sec': 3760.9, 'mvts_per_sec': 609.26, 'rss_gib': 2.1868858337402344}

{'stage': 'B', 'buckets': '501/512', 'mvts': 2295950, 'detections': 2239016, 'elapsed_sec': 3762.4, 'mvts_per_sec': 610.23, 'rss_gib': 2.1868858337402344}

{'stage': 'B', 'buckets': '502/512', 'mvts': 2300520, 'detections': 2243472, 'elapsed_sec': 3765.4, 'mvts_per_sec': 610.97, 'rss_gib': 2.1868858337402344}

{'stage': 'B', 'buckets': '503/512', 'mvts': 2305017, 'detections': 2247867, 'elapsed_sec': 3768.7, 'mvts_per_sec': 611.61, 'rss_gib': 2.1868858337402344}

{'stage': 'B', 'buckets': '504/512', 'mvts': 2309556, 'detections': 2252293, 'elapsed_sec': 3769.1, 'mvts_per_sec': 612.76, 'rss_gib': 2.1868858337402344}

{'stage': 'B', 'buckets': '505/512', 'mvts': 2314140, 'detections': 2256760, 'elapsed_sec': 3770.6, 'mvts_per_sec': 613.74, 'rss_gib': 2.1868858337402344}

{'stage': 'B', 'buckets': '506/512', 'mvts': 2318760, 'detections': 2261288, 'elapsed_sec': 3773.9, 'mvts_per_sec': 614.42, 'rss_gib': 2.1868858337402344}

{'stage': 'B', 'buckets': '507/512', 'mvts': 2323433, 'detections': 2265845, 'elapsed_sec': 3775.1, 'mvts_per_sec': 615.46, 'rss_gib': 2.1868858337402344}

{'stage': 'B', 'buckets': '508/512', 'mvts': 2327967, 'detections': 2270277, 'elapsed_sec': 3775.2, 'mvts_per_sec': 616.65, 'rss_gib': 2.1868858337402344}

{'stage': 'B', 'buckets': '509/512', 'mvts': 2332450, 'detections': 2274630, 'elapsed_sec': 3776.1, 'mvts_per_sec': 617.68, 'rss_gib': 2.1868858337402344}

{'stage': 'B', 'buckets': '510/512', 'mvts': 2337029, 'detections': 2279100, 'elapsed_sec': 3776.9, 'mvts_per_sec': 618.77, 'rss_gib': 2.1868858337402344}

{'stage': 'B', 'buckets': '511/512', 'mvts': 2341625, 'detections': 2283603, 'elapsed_sec': 3777.2, 'mvts_per_sec': 619.94, 'rss_gib': 2.1868858337402344}

{'stage': 'B', 'buckets': '512/512', 'mvts': 2346159, 'detections': 2288020, 'elapsed_sec': 3787.1, 'mvts_per_sec': 619.51, 'rss_gib': 2.1868858337402344}

stage                                                B
processed                               movement_1s_v5
rows                                           2346159
valid_movement_detections                      2288020
failed_movement_detections                       29473
unresolved                                       28666
coverage_percent                              97.52195
speed_threshold                                      2
time_threshold                                     30s
resample_rule                                       1s
traffic_version               2.13.post75.dev0+aee9ba0
bytes                                        353421334
dtype: object

## Coverage

In [6]:
report = workflow.diagnostics(PROCESSED, FEATURES)
display(pd.Series(report["totals"]))
display(report["coverage"]["airport"])
display(report["coverage"]["month"])
report["distribution"]

total_raw_mvts                2.346159e+06
assigned_mvts                 2.341105e+06
multiple_flights              1.212480e+05
unresolved                    2.866600e+04
persisted_mvts                2.317493e+06
valid_movement_detections     2.288020e+06
failed_movement_detections    2.947300e+04
raw_coverage_pct              9.752195e+01
persisted_coverage_pct        9.872824e+01
dtype: float64

,airport,raw_mvts,persisted_mvts,valid_detections,raw_coverage_pct,persisted_coverage_pct
0,EDDF,292530,290924,290846,99.424333,99.973189
1,EDDM,212326,210174,210097,98.950199,99.963364
2,EGLL,311270,307442,307404,98.757991,99.987640
3,EHAM,314362,309994,309926,98.588888,99.978064
4,LEBL,234198,231546,231402,98.806138,99.937809
5,LEMD,261538,256520,254894,97.459643,99.366131
6,LFPG,308487,307686,302724,98.131850,98.387317
7,LIRF,181517,179729,174108,95.918289,96.872514
8,LSZH,175085,172327,172206,98.355656,99.929785
9,LTFM,54846,51151,34413,62.744776,67.277277

,month,raw_mvts,persisted_mvts,valid_detections,raw_coverage_pct,persisted_coverage_pct
0,2025-01,127553,126270,125489,98.381849,99.381484
1,2025-02,115921,114573,112216,96.803858,97.942796
2,2025-03,144026,142214,139561,96.899865,98.134502
3,2025-04,142237,140270,137265,96.504426,97.857703
4,2025-05,151000,149352,147090,97.410596,98.485457
5,2025-06,158774,156951,155469,97.918425,99.055756
6,2025-07,163014,161587,160466,98.436944,99.306256
7,2025-08,163247,161806,159914,97.958309,98.830698
8,2025-09,157225,155632,154164,98.053109,99.056749
9,2025-10,161626,159809,158511,98.072711,99.187780
10,2025-11,140271,138761,137348,97.916177,98.981702
11,2025-12,141179,139291,138251,97.926037,99.253362
12,2026-01,132753,131087,129425,97.493089,98.732140
13,2026-02,127427,125900,123999,97.309832,98.490071
14,2026-06,153242,151160,147755,96.419389,97.747420
15,2026-07,166663,162830,161097,96.660327,98.935700
16,<missing>,1,0,0,0.000000,NaN

count     2.288020e+06
mean      3.399533e+02
std       4.559948e+02
min      -1.765000e+03
p01      -1.930000e+02
p05      -7.400000e+01
p25      -2.500000e+01
median    2.840000e+02
p75       6.000000e+02
p95       1.047000e+03
p99       1.474000e+03
max       2.159600e+04
dtype: float64

In [7]:
features = pd.read_parquet(FEATURES, columns=["ADEP_mvt", "FLIGHT_ID_mvt", "adsb_movement_status"])
features["NM flight plan"] = features["FLIGHT_ID_mvt"].notna()
pd.crosstab(features["adsb_movement_status"].str.split(":").str[0], features["NM flight plan"], margins=True)

NM flight plan         False     True      All
adsb_movement_status
detected               19998  2268022  2288020
no_sustained_movement    508    28965    29473
unresolved_selection     384    28282    28666
All                    20890  2325269  2346159